### PR TITLE
Dead and old rules removable

### PR DESCRIPTION
**Pull request by terlan2**
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

image
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

image
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | ?
Browser:                               | ?
AdGuard version:                       | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

### CODE REVIEW

**Comment by PentagramTr** [comment]
@terlan2 
Sosyal medya gibi diğer filtrelerin içinde de bu sitelere ait kurallar var.Onların da silinmesi gerekir.

<details><summary>Screenshot:</summary>

github com


</details>

**Comment by Alex-302** [comment]
Guys, better post dead domains, instead of the rules.

**Comment by terlan2** [comment]
> Guys, better post dead domains, instead of the rules.

You are right. Next time I will do like that) Thanks.

**Comment by terlan2** [comment]
> @terlan2
> Sosyal medya gibi diğer filtrelerin içinde de bu sitelere ait kurallar var.Onların da silinmesi gerekir.
> 
> Screenshot:

Haklısln en iyisi domen ismi vermek bence Alexin de söylediği gibi

**Comment by Alex-302** [comment]
Removed all these domains

**Comment by terlan2** [comment]
New domains: Please remove these.

unutulmazfilmler.co
fullfilmizlesin.com
filmlobisi.com
filmkorku.org
filmionlineizle.net
diziay.com
birdenizle.net
bicaps.net
altyazilifilmizle.org
pembetv.org

**Comment by BlazDT** [comment]
Thank you, removed.

**Comment by terlan2** [comment]
New domains: Please remove these.

hwa.com.tr
webtedizi.org
fullfilmhdizle1.net
fullhdfilmizledim.org
direkizlehd.tv
incifilm.com
filmhddizi.net
filmakinesi.org
tekfullhdfilmizle.org
720pfilmizle.tv

@BlazDT @Alex-302 @AdamWr

**Comment by Alex-302** [comment]
done

**Comment by terlan2** [comment]
New domains: Please remove these.

ultrafilmizle.com
yerlifilmiizle.net
hdfilmarenasi.com
filmihizliizle.com
720pdizi.com
noktafilmizle.net
hdfilmgecesi.co
filmifullhizliizle.com
ilkhdfilmcehennemi.com
sinegram.net
canlihddizi.co
filmhizmeti.org
burdanhdfilmizle.org
filmrax.com
filmizleburda.org

@BlazDT @Alex-302 @AdamWr @slavaleleka

**Comment by Alex-302** [comment]
ok

**Comment by terlan2** [comment]
> ok

thank you so much

**Comment by terlan2** [comment]
New domains: Please remove these.

pasgol.tv
yabancidiziizle.org
filmhizmeti1.com
filmtadim.net
bahissitesibul.com
rbet5.tv
filmakinesi2.org
hdmacyayinlari.com
fullhdfilmizleyicisi.org
gunlukfilm.net
hdfilmevreni1.com
hdfilmizle1080p.com
harikadizi15.com
hdyayinmac.com
canlimacyayini.net

@Alex-302 @AdamWr @BlazDT @slavaleleka

**Comment by Alex-302** [comment]
thanks, done

**Pull request closed without merging**
