### PR TITLE
fix #80097 koreabiomed.com (share)

### LINKED ISSUE #80097: www.koreabiomed.com
### Issue URL (Ads)
 [http://www.koreabiomed.com/news/articleView.html?idxno=10901](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwww.koreabiomed.com%2Fnews%2FarticleView.html%3Fidxno%3D10901)
### Comment
Username: @chirag127
> many ads

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.34
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (2880), <br>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances

### PR DESCRIPTION
**Pull request by wout-codes**
#80097

### CODE REVIEW

**Comment by stanislav-atr** [comment]
<details><summary>Screenshot:</summary>

http://www.koreabiomed.com/news/articleView.html?idxno=10903
image</details><br/>
How about also adding these to social
```
koreabiomed.com##.social-group > button.facebook
koreabiomed.com##.social-group > button.twitter
koreabiomed.com##.social-group > button.kakaostory
```
and others to popups?

**Comment by wout-codes** [comment]
I don't think specification is needed. Isn't this enough? `koreabiomed.com##.social-group`

**Comment by stanislav-atr** [comment]
> I don't think specification is needed. Isn't this enough? `koreabiomed.com##.social-group`. And what other popups? I can't reproduce any.

Bookmark, URL and mail buttons don't count as socials, but can be added to annoyances as floats.

**Comment by wout-codes** [comment]
> > I don't think specification is needed. Isn't this enough? `koreabiomed.com##.social-group`. And what other popups? I can't reproduce any.
> 
> Bookmark, URL and mail buttons don't count as socials, but can be added to annoyances as floats.

Ok, in that case as I can agree.

**Review by stanislav-atr — APPROVED** [review]

**Pull request merged**
