### PR TITLE
Fix #177426 levi.com.br

### LINKED ISSUE #177426: www.levi.com.br
### Issue URL (Annoyance)
 [https://www.levi.com.br/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.levi.com.br%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | Value
--- | ---
AdGuard product: | AdGuard Browser Extension v4.3.46
System version: | Windows 10
Browser: | Chrome
Stealth mode options: | Strip URLs from tracking parameters, <br>Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Block trackers
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Spanish/Portuguese

### PR DESCRIPTION
**Pull request by AntonVoronkin**
Fix [#177426](https://github.com/AdguardTeam/AdguardFilters/issues/177426)

### CODE REVIEW

**Review by piquark6046 — CHANGES_REQUESTED** [review]
I think that using `div[class$="-x-consentLgpd"]` as the selector is better for another website filtering.
Example: `loja.se.com##.lojaschneider-store-0-x-consentLgpd` in `easylist_cookie/easylist_cookie_international_specific_hide.txt`.

**Comment by piquark6046** [comment]
CC: @ryanbr

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/177803#issuecomment-2074967921
Yes.

**Review by piquark6046 — CHANGES_REQUESTED** [review]
please move to the top section.

**Review by piquark6046 — APPROVED** [review]

**Review by AdamWr — APPROVED** [review]

**Pull request merged**
