### PR TITLE
fix #77402 statisticshowto.com

### LINKED ISSUE #77402: www.statisticshowto.com
### Issue URL (Incorrect Blocking)
 [https://www.statisticshowto.com/probability-and-statistics/correlation-coefficient-formula/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.statisticshowto.com%2Fprobability-and-statistics%2Fcorrelation-coefficient-formula%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>
<details>
  <summary>Screenshot 2</summary>

  Screenshot 2
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.31
Browser: | Chrome
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> ABPVN List

### PR DESCRIPTION
**Pull request by wout-codes**
#77402
Whitelist is enough.

### CODE REVIEW

**Comment by Alex-302** [comment]
Not enough on my end

**Comment by wout-codes** [comment]
What do you recommend then?

**Comment by Alex-302** [comment]
On my end it works when `cookiebot.com` is whitelisted.
`@@||cookiebot.com^$domain=statisticshowto.com`
`statisticshowto.com###CybotCookiebotDialog`

**Comment by wout-codes** [comment]
> On my end it works when `cookiebot.com` is whitelisted.
> `@@||cookiebot.com^$domain=statisticshowto.com`
> `statisticshowto.com###CybotCookiebotDialog`

The whitelist is enough on my end. But I'll add it anyway.

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
