### PR TITLE
fix #37157 narodna-pravda.ua

### LINKED ISSUE #37157: narodna-pravda.ua
### Issue URL (Ads)
[https://narodna-pravda.ua/ru/2019/07/07/nas-obmanyvali-drevnij-mif-o-windows-okazalsya-pravdivym/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fnarodna-pravda.ua%2Fru%2F2019%2F07%2F07%2Fnas-obmanyvali-drevnij-mif-o-windows-okazalsya-pravdivym%2F)
### Comment
Username: @spok1
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 3.2.1
Browser: | Chrome
Stealth mode options: | Hide your search queries, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Hide your Referrer from third-parties
Filters: | AdGuard Russian,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

### PR DESCRIPTION
**Pull request by zloyden**
https://github.com/AdguardTeam/AdguardFilters/issues/37157

### CODE REVIEW

**Review by BlazDT — COMMENTED** [review]
Unsure about the last two (I do not see the items from them visible):

||agroday.com.ua^$domain=narodna-pravda.ua
||smi.today^$domain=narodna-pravda.ua
||dert.pro^$domain=narodna-pravda.ua

**Comment by zloyden** [comment]
> Unsure about the last two (I do not see the items from them visible)

Last two rules hide left-over from blocked urls `загрузка...`
<details><summary>Screenshots:</summary>

Снимок экрана 2019-07-23 в 12 21 46
Снимок экрана 2019-07-23 в 12 24 15

</details><br/>

**Comment by BlazDT** [comment]
@zloyden 
I was talking about the last two url blocks I posted.

**Comment by zloyden** [comment]
Ok. I can't see them too - only in journal. I guess we should block this.

**Review by BlazDT — APPROVED** [review]

**Comment by Alex-302** [comment]
I can't reproduce that ad.

**Pull request merged**
