### PR TITLE
shikanoou-movie.jp

### PR DESCRIPTION
**Pull request by spiri-leo**
Issue: #108639

### CODE REVIEW

**Review by Yuki2718 — CHANGES_REQUESTED** [review]
Rather than adding a new ruke, change an existing rule `shikanoou-movie.jp###sharaTxt2` to `shikanoou-movie.jp##div[id^="sharaTxt"]`

**Comment by spiri-leo** [comment]
> Rather than adding a new ruke, change an existing rule `shikanoou-movie.jp###sharaTxt2` to `shikanoou-movie.jp##div[id^="sharaTxt"]`

Fixed.

**Review by zloyden — CHANGES_REQUESTED** [review]
You didn't remove the old rule.
https://github.com/AdguardTeam/AdguardFilters/blob/3fe1c11026a792f3788cfca4338f1601cd518a09/SocialFilter/sections/specific.txt#L195

**Comment by spiri-leo** [comment]
> You didn't remove the old rule.
> 
> https://github.com/AdguardTeam/AdguardFilters/blob/3fe1c11026a792f3788cfca4338f1601cd518a09/SocialFilter/sections/specific.txt#L195

Fixed.

**Review by Yuki2718 — APPROVED** [review]

**Review by zloyden — APPROVED** [review]

**Pull request merged**
