### PR TITLE
fix #80181 m.sport1.de

### LINKED ISSUE #80181: m.sport1.de
### Issue URL (Anti Adblock Script)
 [https://m.sport1.de/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fm.sport1.de%2F)
### Comment
Username: `@lkstnr`
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.1.1
Browser: | Safari
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard German

### PR DESCRIPTION
**Pull request by stanislav-atr**
#80181

@Sergey-Lyapin, check this one on Mac, please. Does antiadb message blocks the scroll too?

### CODE REVIEW

**Comment by Sergey-Lyapin** [comment]
I was not able to reproduce antiadblock (AG for Mac and iOS)

**Comment by BlazDT** [comment]
Can you determine which element they checked? In the past they checked if `https://consentv2.sport1.de/wrapperMessagingWithoutDetection.js` was blocked.

**Comment by stanislav-atr** [comment]
@BlazDT, sadly, i am not able to see network/filtering log on my iOS device :(

**Comment by Alex-302** [comment]
@stanislav-atr you can see blocked requests in console.

**Comment by stanislav-atr** [comment]
@Alex-302, Networtk tab is not acessible when debugging iOS through webkit adapter

**Comment by Alex-302** [comment]
https://www.browserstack.com/guide/how-to-debug-on-iphone

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
