### PR TITLE
fix #33713 waiset.su

### LINKED ISSUE #33713: waiset.su
### Issue URL (Ads)
[NSFW][http://waiset.su/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwaiset.su%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | v3.0.297 (1.3.207cl)
Browser: | Chrome
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing first-party cookies (4320), Self-destructing third-party cookies (180), Block WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties (), Hide your Referrer from third-parties, Hide your IP address (209.141.53.254)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Russian,<br>EasyList,<br>AdGuard Mobile Ads,<br>EasyPrivacy,<br>Fanboy's Social Blocking List,<br>AdGuard Annoyances,<br>AdGuard Base,<br>Peter Lowe's list,<br>Malware Domains,<br>Spam404,<br>Fanboy's Enhanced Tracking List,<br>Fanboy Anti-Facebook List,<br>Fanboy's Anti-thirdparty Fonts,<br>NoCoin Filter List,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

### PR DESCRIPTION
**Pull request by zloyden**
https://github.com/AdguardTeam/AdguardFilters/issues/33713

### CODE REVIEW

**Review by BlazDT — APPROVED** [review]

**Review by AdamWr — APPROVED** [review]

**Comment by AdamWr** [comment]
By the way, I think that this website can be also added to this rule:
https://github.com/AdguardTeam/AdguardFilters/blob/6cc24432191dc3098bbd8e88a41ac8f3414ea767/RussianFilter/sections/general_extensions.txt#L77-L78

**Comment by Alex-302** [comment]
> added to this rule

yes

**Review by Alex-302 — CHANGES_REQUESTED** [review]
add domain to suggested rule

**Comment by zloyden** [comment]
Added domain to suggested rule.

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
