### PR TITLE
carscoops.com Ad-Shield recovery

### PR DESCRIPTION
**Pull request by JobcenterTycoon**
https://github.com/uBlockOrigin/uAssets/issues/23920

### CODE REVIEW

**Comment by JobcenterTycoon** [comment]
wait please

**Comment by JobcenterTycoon** [comment]
@Alex-302 `$$script:contains(error-report.com)` doesn’t work and just causing infinity loading now but `$$script[tag-content="error-report.com"]` works fine with Firefox

**Comment by Alex-302** [comment]
Hmm. Where can I check?

**Comment by JobcenterTycoon** [comment]
1. Add `allthetests.com,javatpoint.com,globalrph.com,carscoops.com$$script:contains(error-report.com)` to user filter (Firefox)
2. open `https://www.carscoops.com/`

It will causing infinity loading or a empty page. The old syntax works fine.

**Comment by Alex-302** [comment]
Thanks, good catch! Will file a bug. Then better use old syntax :harold.jpg:

**Comment by JobcenterTycoon** [comment]
Reverted back.

**Review by Alex-302 — APPROVED** [review]

**Comment by Alex-302** [comment]
Thanks!

**Pull request merged**
