### PR TITLE
sakpot.com

### PR DESCRIPTION
**Pull request by gork7777**
issue: #115826

### CODE REVIEW

**Review by Sergey-Lyapin — CHANGES_REQUESTED** [review]
Please check the rules under this comment:
`! AdUnblocker ('blanket' popup)`

**Comment by gork7777** [comment]
How can I check them?

**Comment by Sergey-Lyapin** [comment]
@gork7777 
I mean we should use the rules under `! AdUnblocker ('blanket' popup)` here

**Review by zloyden — COMMENTED** [review]
It's already fixed.

**Pull request closed without merging**
