### PR TITLE
www.engelhorn.de

### PR DESCRIPTION
**Pull request by spiri-leo**
Issue: #109597

### CODE REVIEW

**Review by gork7777 — CHANGES_REQUESTED** [review]
Remove `cmpbox` rules and add domain to here:
`##div[id^="cmpbox"]`

**Comment by spiri-leo** [comment]
> Remove `cmpbox` rules and add domain to here: `##div[id^="cmpbox"]`

Fixed.

**Comment by gork7777** [comment]
Hm it's better to add to existing rule: `kicker.de##div[id^="cmpbox"]`

**Comment by spiri-leo** [comment]
> Hm it's better to add to existing rule: `kicker.de##div[id^="cmpbox"]'

Fixed

**Review by zloyden — COMMENTED** [review]
@gork7777 @spiri-leo please take a look at my commit https://github.com/AdguardTeam/AdguardFilters/commit/01c477df187fa328d69524a835b72e04cf7e39d8 - this is how it has to be.
There had also been some issue with store, fixed directly.

**Pull request closed without merging**
