### PR TITLE
siberkalem.com

### LINKED ISSUE #71037: siberkalem.com
### Issue URL (Annoyance)
 [https://siberkalem.com/cyberpunk-2077-pcde-performans-arttirma-yontemi-16131/#close](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fsiberkalem.com%2Fcyberpunk-2077-pcde-performans-arttirma-yontemi-16131%2F%23close)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.31
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Remove X-Client-Data header from HTTP requests, <br/>Strip URLs from tracking parameters, <br/>Self-destructing third-party cookies (1440)
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Security:</b><br/> NoCoin Filter List<br/><br/><b>Language-specific:</b><br/> AdGuard Turkish

### PR DESCRIPTION
**Pull request by gork7777**
https://github.com/AdguardTeam/AdguardFilters/issues/71037

### CODE REVIEW

**Review by zloyden — COMMENTED** [review]
Please also add these rules to the `popups.txt` in the AdGuard Annoyances and the AdGuard Social filters.
```
siberkalem.com#$##popup-box { display: none !important; }
siberkalem.com#$#body { overflow: visible !important; }
```

**Comment by zloyden** [comment]
@gork7777  also please review your PR's and change their title, description (first post) - below is the template.
Title `example.com`.
Description (generally, just the task link) `https://github.com/AdguardTeam/AdguardFilters/issues/00000`. But if you want to ask us something - there is a nice place to do it.

Commit name for the future PR's `fix #00000 example.com`.

**Comment by gork7777** [comment]
siberkalem.com https://github.com/AdguardTeam/AdguardFilters/issues/71037
Like that?

**Review by zloyden — APPROVED** [review]

**Comment by zloyden** [comment]
> siberkalem.com #71037
> Like that?

If you meant the commit name, the first one should be `fix #71037 siberkalem.com`.

**Pull request merged**
