### PR TITLE
aztecapornohd.xxx

### PR DESCRIPTION
**Pull request by jellizaveta**
https://github.com/AdguardTeam/AdguardFilters/issues/102419

### CODE REVIEW

**Review by Yuki2718 — CHANGES_REQUESTED** [review]
Please add `aztecapornohd.xxx##.lst_ft_bn` to Spanish filters.

**Comment by Sergey-Lyapin** [comment]
И эти тоже в испанский:
```
aztecapornohd.xxx###videoss > section:not([class])
aztecapornohd.xxx##div[id^="dvtop"]
```

**Comment by Yuki2718** [comment]
@Sergey-Lyapin On my end `##div[id^="dvtop"]` doesn't hit, instead `##div[id^="dvsingle"]` hits.

**Comment by Sergey-Lyapin** [comment]
@Yuki2718
It seems they use `.dvcss` for ads only so we can use `aztecapornohd.xxx##.dvcss` (also instead of `##.lst_ft_bn`)

**Comment by Yuki2718** [comment]
> It seems they use `.dvcss` for ads only so we can use `aztecapornohd.xxx##.dvcss` (also instead of `##.lst_ft_bn`)

Yep, you're right.

**Comment by Sergey-Lyapin** [comment]
@jellizaveta 
Please remove `aztecapornohd.xxx##.lst_ft_bn` , `aztecapornohd.xxx##div[id^="dvtop"]` and add `aztecapornohd.xxx##.dvcss`

**Pull request merged**
