### PR TITLE
fix #79516

### LINKED ISSUE #79516: uniqueten.net
### Issue URL (Annoyance)
 [https://uniqueten.net/?link=CBjyh67h5ov](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Funiqueten.net%2F%3Flink%3DCBjyh67h5ov)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.34
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (2880), <br>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection, <br/>EasyPrivacy<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Turkish, <br/>AdGuard Russian, <br/>AdGuard Spanish/Portuguese

### PR DESCRIPTION
**Pull request by wout-codes**
https://github.com/AdguardTeam/AdguardFilters/issues/79516#issuecomment-816672313

### CODE REVIEW

**Comment by Sergey-Lyapin** [comment]
```
uniqueten.net#%#//scriptlet('abort-on-property-read', 'adBlockDetected')
uniqueten.net###adb
```
is enough
and `||icgrohbeory.com^$third-party` to adservers

**Comment by wout-codes** [comment]
Yeah, you are right.

**Comment by Sergey-Lyapin** [comment]
@wout-codes please remove the domain from antiadblock section

**Comment by Sergey-Lyapin** [comment]
@wout-codes 
I don't see adBlockDetected function on ultraten.net and I don't see antiadblock there
Please remove ultraten.net

**Comment by wout-codes** [comment]
The sites are similar, so they can similar code after on.

**Pull request merged**
