### PR TITLE
s.animeanime.jp

### LINKED ISSUE #107949: s.animeanime.jp
### Issue URL (Social Widget)
 [https://s.animeanime.jp/article/2021/11/05/65171.html?pickup_list_click1=true](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fs.animeanime.jp%2Farticle%2F2021%2F11%2F05%2F65171.html%3Fpickup_list_click1%3Dtrue)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.3.2
Browser: | Safari
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Other:</b><br/>AdGuard Experimental<br/><br/><b>Language-specific:</b><br/>AdGuard Japanese, <br/>AdGuard Chinese

### PR DESCRIPTION
**Pull request by SKEIDs**
Fix #107949

### CODE REVIEW

**Review by Yuki2718 — CHANGES_REQUESTED** [review]
Please add `animeanime.jp` to existing `###pb_hidden` rule in JPF.

**Comment by SKEIDs** [comment]
@Yuki2718 
For some reason I can't merge the latest rules into this branch and I can't fix it. 
I am sorry, can you please fix it directly?

**Comment by Yuki2718** [comment]
> For some reason I can't merge the latest rules into this branch and I can't fix it. I am sorry, can you please fix it directly?

Done https://github.com/AdguardTeam/AdguardFilters/issues/107949 I suggest to use and learn some Git client. I use Git for Windows (command line interface) but others use some GUI client.

**Comment by SKEIDs** [comment]
> > For some reason I can't merge the latest rules into this branch and I can't fix it. I am sorry, can you please fix it directly?
> 
> Done [b51a6bd](https://github.com/AdguardTeam/AdguardFilters/commit/b51a6bdcc822b8e044d9edc1ca37202e88a5db23) I suggest to use and learn some Git client. I use Git for Windows (command line interface) but others use some GUI client.

i see. thank you for teach me.

**Review by Yuki2718 — APPROVED** [review]

**Review by zloyden — APPROVED** [review]

**Pull request merged**
