### PR TITLE
Update img*.xyz

### PR DESCRIPTION
**Pull request by wout-codes**
`http://imgfrost.net/aucw5bhn`

### CODE REVIEW

**Comment by wout-codes** [comment]
@Yuki2718 Should the domains be added to the rule `###pbe`?

**Comment by Yuki2718** [comment]
@wout-codes I missed your PR, already added these domain.

**Comment by Yuki2718** [comment]
@wout-codes Now `imgex.xyz` (`http://imgfrost.net/aucw5bhn`)

**Comment by wout-codes** [comment]
I wonder how they change domains very fast.

**Comment by Yuki2718** [comment]
> I wonder how they change domains very fast.

Yeah, now it's nearly hourly basis.

**Comment by zloyden** [comment]
@wout-codes is this pr in progress or finished?

**Comment by Yuki2718** [comment]
@zloyden It can never be finished, they react too fast. I tend to suggest merge it anyway.

**Review by zloyden — APPROVED** [review]

**Pull request merged**
