### PR TITLE
end-harem-anime.com

### PR DESCRIPTION
**Pull request by SKEIDs**
https://github.com/AdguardTeam/AdguardFilters/issues/103388

### CODE REVIEW

**Comment by Sergey-Lyapin** [comment]
Please also add this rule `end-harem-anime.com##.twTimelineWrap` for twitter widget.
and add end-harem-anime.com to the rules under this comment
`! ##.twitter-timeline + widgets.js`

**Comment by SKEIDs** [comment]
> Hi @SKEIDs Please also add this rule `end-harem-anime.com##.twTimelineWrap` for twitter widget. and add end-harem-anime.com to the rules under this comment `! ##.twitter-timeline + widgets.js`



https://github.com/AdguardTeam/AdguardFilters/pull/103438/commits/12cd42c629a4285058b438d221c90eb046461f04
https://github.com/AdguardTeam/AdguardFilters/pull/103438/commits/acfb92e5a0756d63ef98a3d1442b477a4322ba50

Are these right?

**Comment by Sergey-Lyapin** [comment]
@SKEIDs
I also add the domain to `##.twitter-timeline` rule, this rule and the rule above should have the same domain list.

**Comment by SKEIDs** [comment]
> I also add the domain to ##.twitter-timeline rule, this rule and the rule above should have the same domain list.

sorry.

**Pull request merged**
