### PR TITLE
fix #77903 gadgetsnow.com

### LINKED ISSUE #77903: www.gadgetsnow.com
### Issue URL (Ads)
 [https://www.gadgetsnow.com/slideshows/how-redmis-first-smart-tv-compares-with-rivals-from-nokia-realme-and-mi/photolist/81577867.cms](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.gadgetsnow.com%2Fslideshows%2Fhow-redmis-first-smart-tv-compares-with-rivals-from-nokia-realme-and-mi%2Fphotolist%2F81577867.cms)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.31
Browser: | Firefox
Stealth mode: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>Peter Lowe's Blocklist<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Dutch

### PR DESCRIPTION
**Pull request by wout-codes**
#77903

The strings have random names and it changes by region.

### CODE REVIEW

**Comment by wout-codes** [comment]
I will add a hint to the rule in css_extended.txt, EasyList has a fix which would solve for the extensions. The leftover is still there with AdGuard Apps.

**Comment by Alex-302** [comment]
added a bit diferent rules

**Comment by wout-codes** [comment]
@Alex-302 Maybe you do not understand English, or you are blind.

**Comment by wout-codes** [comment]
@zloyden Please take a look, I can still reproduce the leftover with AdGuard Apps.

**Comment by wout-codes** [comment]
@Alex-302 The rule you added, `||timesofindia.indiatimes.com/affiliate_new.cms$domain=gadgetsnow.com` is already in Easylist, didn't you read what I have commented earlier? 

<details>

image
</details>

**Comment by wout-codes** [comment]
@zloyden Can you please reopen this?

**Comment by zloyden** [comment]
Added https://github.com/AdguardTeam/AdguardFilters/commit/c6b54a528984fc3af02bcff4778cb95a0166aceb

**Comment by wout-codes** [comment]
Remove this: `||timesofindia.indiatimes.com/affiliate_new.cms$domain=gadgetsnow.com`. Already in EasyList.

**Comment by zloyden** [comment]
Ok, done.

**Pull request closed without merging**
