### PR TITLE
fix #56315 llabtooflatot.blog.fc2.com

### LINKED ISSUE #56315: llabtooflatot.blog.fc2.com
### Issue URL (Annoyance)
 [https://llabtooflatot.blog.fc2.com/?sp](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fllabtooflatot.blog.fc2.com%2F%3Fsp)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>
<details>
  <summary>Screenshot 2</summary>

  Screenshot 2
</details>

### System configuration

Information | value
--- | ---
Platform: | And 10
AdGuard version: | 3.5 nightly 2 (14)
Browser: | Chrome (data compression)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Japanese
Custom filter subscriptions: |

### PR DESCRIPTION
**Pull request by Yuki2718**
https://github.com/AdguardTeam/AdguardFilters/issues/56315

Not wanted to create a new category in widgets.txt but there's no proper existing category for this widget - do you prefer "Countdown/Countup widgets"?

### CODE REVIEW

**Comment by Alex-302** [comment]
What the purpose of that widget? Google translate is not clear.

**Comment by Yuki2718** [comment]
> 
> 
> What the purpose of that widget? 

Generally it's for countdown/countup e.g. for an future event or time-limited sale, but the blog uses it literally for nonsense or no purpose.

**Comment by Alex-302** [comment]
What the purpose of this widget? I am not sure if all widgets must be blocked(as annoyance).

**Comment by Yuki2718** [comment]
@Alex-302 The widget should not be blocked globally as it can be useful if used on-purpose. The thing is the blog of the matter doesn't. My best translation of the sentences on the widget which web master can freely edit according to the widget author: "We are counting up without any purpose or usage, it's 98 days and XX since we started it. If you are to post comments here hurry up (though there's no time limit or early bonus for it)"
Only concern is it may be possible the blog owner starts to use the widget on-purpose in future, but given it is not displayed on PC it's unlikely to happen soon.

**Pull request closed without merging**
