### PR TITLE
Ad-Servers

### PR DESCRIPTION
**Pull request by wout-codes**
+ `https://mangaclash.com/` - Galaksion Ads

Screenshot -> https://github.com/AdguardTeam/AdguardFilters/pull/83356#issuecomment-842149853

### CODE REVIEW

**Comment by zloyden** [comment]
@wout-codes can you provide a screenshot? I don't see ads with US IP.

**Comment by wout-codes** [comment]
Which site? `mangaclash.com`?

**Comment by zloyden** [comment]
> `mangaclash.com`?

Yes.

**Comment by wout-codes** [comment]
@zloyden 
image

**Review by zloyden — APPROVED** [review]

**Pull request merged**
