### PR TITLE
Update https://github.com/AdguardTeam/AdguardFilters/issues/70031

### PR DESCRIPTION
**Pull request by Yuki2718**
https://github.com/AdguardTeam/AdguardFilters/pull/70219#discussion_r545828733
Please wait before merging, I'll check script too. In some cases visiting HP is not enough, only shown when redirected from sister sites.

### CODE REVIEW

**Comment by zloyden** [comment]
Ok, when your PR is ready to review, just removed `[WIP]` from the title.

**Comment by Yuki2718** [comment]
I didn't see any `/strp_v` script.

**Comment by zloyden** [comment]
> I didn't see any `/strp_v` script.

Do you mean in new domains or generally?

**Comment by Yuki2718** [comment]
> > I didn't see any `/strp_v` script.
> 
> Do you mean in new domains or generally?

Generally, unless I missed.

**Comment by zloyden** [comment]
Hm, for example
<details><summary>Screenshot:</summary>

image

</details><br/>

**Comment by Yuki2718** [comment]
I'll investigate, will add WIP back.

**Comment by zloyden** [comment]
Just in case, this `/strp_v` script may not appear immediately, but after some page refresh.

**Comment by Yuki2718** [comment]
Yes, it seems loaded quite conditionally via loadTool. I guess scriptlet can also be used, they may change path in future.

**Comment by zloyden** [comment]
> Yes, it seems loaded quite conditionally via loadTool. I guess scriptlet can also be used, they may change path in future.

That's a good point. Please also add necessary domains to the our scriptlet rule.

**Comment by Yuki2718** [comment]
Is `#%#//scriptlet("abort-on-property-read", "loadTool")` okay? I only found `#%#//scriptlet("abort-current-inline-script", "loadTool", "/'popping'/")` in common scriptlet filters but there's no popping in these cases. Or do you prefer "abort-current-inline-script" with a new third parameter?

**Comment by Yuki2718** [comment]
Added a few domain. It's really not straightforward thx to their random redirect and its conditional nature, I'm almost giving up. Sorry but please add an according scriptlet on your side - all domains in /strp_v rule should be added. Also upon investigation I came across `https://www.novojoy.com/gorgeous-blonde-nicole-neal` and `https://www.novoporn.com/hannah` which require `#%#//scriptlet('abort-current-inline-script', 'document.querySelectorAll', 'popMagic')`.

**Comment by zloyden** [comment]
> Is `#%#//scriptlet("abort-on-property-read", "loadTool")` okay? I only found `#%#//scriptlet("abort-current-inline-script", "loadTool", "/'popping'/")` in common scriptlet filters but there's no popping in these cases. Or do you prefer "abort-current-inline-script" with a new third parameter?

`#%#//scriptlet("abort-on-property-read", "loadTool")` is ok on my end or you can add another value to the old rule.

**Comment by Yuki2718** [comment]
Where to add? It's the first time I add a new common scriptlet filter.

**Comment by zloyden** [comment]
> Also upon investigation I came across `https://www.novojoy.com/gorgeous-blonde-nicole-neal` and `https://www.novoporn.com/hannah` which require `#%#//scriptlet('abort-current-inline-script', 'document.querySelectorAll', 'popMagic')`.

Added them, thanks.



> Where to add? It's the first time I add a new common scriptlet filter.

To the same place, I mean you can exchange this old rule with a new one (if it works for old domains) **or** just add a new scriptlet with domains that required.

**Comment by zloyden** [comment]
I guess it's ok now, but I don't see these requests. Also you can make it via one rule using Regex.
```
/smallfr/*$subdocument,domain=babeimpact.com|decorativemodels.com|sexykittenporn.com
/smallfr2/*$subdocument,domain=babeimpact.com|decorativemodels.com
```

**Comment by Yuki2718** [comment]
You can see here: `https://www.decorativemodels.com/galleries/hanna-looks-pretty-hazed-to-me/` but `babeimpact.com`  and `sexykittenporn.com` were only when navigated thorough redirect. Okay I'll make them a single rule - is regex preferred than `/smallfr*/*`?

**Comment by zloyden** [comment]
> You can see here: `https://www.decorativemodels.com/galleries/hanna-looks-pretty-hazed-to-me/` but `babeimpact.com` and `sexykittenporn.com` were only when navigated thorough redirect. Okay I'll make them a single rule - is regex preferred than `/smallfr*/*$subdocument,domain=babeimpact.com|decorativemodels.com|sexykittenporn.com`?

I prefer Regex because it's more accurate than using such solutions, but in this case `/smallfr*/*$subdocument,domain=babeimpact.com|decorativemodels.com|sexykittenporn.com` is ok and one more point - it will be processed faster than regex. Could you also add `babeimpact.com,decorativemodels.com,sexykittenporn.com##iframe[src^="/smallfr"]`? it's is necessary for app.

**Comment by Yuki2718** [comment]
Yeah, I thought so as in this case domain is limited - but for generic rule I'd prefer regex like you. Ok, a second.

**Review by zloyden — APPROVED** [review]

**Comment by zloyden** [comment]
Thanks, nice work here:)

**Pull request merged**
