### PR TITLE
mihentai.com

### PR DESCRIPTION
**Pull request by gork7777**
##### To avoid invalid pull requests, please check and confirm following checkboxes:

  - [x] This is not an ad/bug report;
  - [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
  - [x] I have performed a self-review of my own changes;
  - [x] My changes do not break web sites, apps and files structure.

##### If the problem does not fall under any category that is listed here, please contact our tech support: `support@adguard.com`

  - [x] Missed ads or ad leftovers;
  - [ ] Website or app doesn't work properly;
  - [x] AdGuard gets detected on a website;
  - [ ] Missed analytics or tracker;
  - [ ] Social media buttons — share, like, tweet, etc;
  - [ ] Annoyances — pop-ups, cookie warnings, etc.

### What issue is being fixed?
https://github.com/AdguardTeam/AdguardFilters/issues/119096

### Add your comment and screenshots

**1.** `Also blocked "close" ad`

**2.** Screenshots

<details><summary>Screenshot 1:</summary>

image

</details>

### Terms

  - [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met.

### CODE REVIEW

**Comment by Alex-302** [comment]
Cannot reproduce anti-adblock in opere or chrome.

**Comment by Yuki2718** [comment]
I can reproduce on Brave (Shield disabled of course), you have to move to each contents.

**Review by Yuki2718 — CHANGES_REQUESTED** [review]
Add to `$$script[wildcard="*eval*babasbmsgx*"][min-length="5000"][max-length="20000"]` as well, this is an old bab.

**Review by zloyden — APPROVED** [review]

**Comment by zloyden** [comment]
> Add to `$$script[wildcard="*eval*babasbmsgx*"][min-length="5000"][max-length="20000"]` as well, this is an old bab.

Yep, its is.

**Pull request merged**
