### PR TITLE
fix #86021 www.last.fm

### LINKED ISSUE #86021: www.last.fm
### Issue URL (Ads)
 [https://www.last.fm/zh/home](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.last.fm%2Fzh%2Fhome)
### Comment
Username: @shenzhiming88
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.6.6
Browser: | Edge
Stealth mode: | disabled
Filters: | <b>Ad Blocking:</b><br/>EasyList<br/><br/><b>Language-specific:</b><br/>AdGuard Chinese

### PR DESCRIPTION
**Pull request by DeepChirp**
#86021

### CODE REVIEW

**Comment by zloyden** [comment]
@shenzhiming88 we have those rules in AdGuard Base and Annoyances filters.

**Comment by shenzhiming88** [comment]
> @shenzhiming88 we have those rules in AdGuard Base and Annoyances filters.

Hello

But I use ubo, so could you tell me what can I do?

**Comment by zloyden** [comment]
In this case, you can enable them in uBlock Origin and **don't disable** Easylist - this advice is only for our products.
<details><summary>Screenshot:</summary>

image

</details><br/>

**Comment by shenzhiming88** [comment]
@zloyden Thank you for your help!

**Comment by zloyden** [comment]
You are welcome.

**Pull request closed without merging**
