### PR TITLE
fix #41922 imagebam.com

### LINKED ISSUE #41922: imagebam.com
### Issue URL (Ads)
[NSFW][http://www.imagebam.com/image/a2c6ea171888549](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwww.imagebam.com%2Fimage%2Fa2c6ea171888549)
### Comment
Username: @gintokihub
> 
> --
> The information below is automatically generated. Do not delete it.
> 
> Referrer:
> http://www.imagebam.com/image/a97fd4171888540
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.2.2936.0
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (180), Disable cache for third-party requests, Block WebRTC, Block Push API, Block Location API, Block Flash, Hide your Referrer from third-parties (www.imagebam.com)
Filters: | AdGuard Annoyances,<br>AdGuard Simplified domain names,<br>AdGuard Base,<br>Peter Lowe's list,<br>Adblock Warning Removal List,<br>I don't care about cookies,<br>BarbBlock,<br>NoCoin Filter List,<br>AdGuard Tracking Protection,<br>AdGuard Social Media,<br>AdGuard Dutch

### PR DESCRIPTION
**Pull request by zloyden**
https://github.com/AdguardTeam/AdguardFilters/issues/41922

### CODE REVIEW

**Review by BlazDT — CHANGES_REQUESTED** [review]
||bestcontentfood.top^$third-party
||tsyndicate.com/iframes2^$important

Without $important is was not blocked for me.

Iframe is not always exosrv.com

**Comment by Alex-302** [comment]
@BlazDT on my end it is blocked by `||tsyndicate.com^$third-party`. Please check again. tsyndicate.com is unblocked in safe browsing now.

**Comment by BlazDT** [comment]
Sadly the referrer is tsyndicate.com itself, see screenshot:

t-syndicate

**Review by BlazDT — APPROVED** [review]

**Comment by Alex-302** [comment]
@BlazDT @zloyden 
https://github.com/AdguardTeam/CoreLibs/issues/682#issuecomment-539925997
better add temporary `||tsyndicate.com^$important` rule for apps and check it later, when `popup` rule will block frames.

@AdamWr @slavaleleka

**Comment by zloyden** [comment]
Added temporary section for this rule.

**Review by Alex-302 — APPROVED** [review]

**Comment by GintokiHub** [comment]
interesting to read the follow up

**Pull request merged**
