### PR TITLE
fix #80040 torguard.net

### LINKED ISSUE #80040: torguard.net
### Issue URL (Ads)
 [https://torguard.net/blog/how-to-block-ads-with-torguard-vpn/#:~:text=To%20block%20ads%20with%20TorGuard%20on%20Android%20or%20iOS%2C%20simply,select%20%E2%80%9CAd%20blocking%20DNS%E2%80%9D.](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Ftorguard.net%2Fblog%2Fhow-to-block-ads-with-torguard-vpn%2F%23%3A~%3Atext%3DTo%2520block%2520ads%2520with%2520TorGuard%2520on%2520Android%2520or%2520iOS%252C%2520simply%2Cselect%2520%25E2%2580%259CAd%2520blocking%2520DNS%25E2%2580%259D.)
### Comment
Username: @chirag127
> newsletter

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>
<details>
  <summary>Screenshot 2</summary>

  Screenshot 2
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.34
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (2880), <br>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances

### PR DESCRIPTION
**Pull request by wout-codes**
#80040

### CODE REVIEW

**Comment by Alex-302** [comment]
added different rules

**Comment by wout-codes** [comment]
@Alex-302

**Comment by wout-codes** [comment]
These rules will can be changed very easily. This is not a longtime fix.
` ||torguard.net/blog/wp-content/uploads/2018/09/torguard-090418-300x250.gif`
` ||torguard.net/blog/wp-content/uploads/2019/10/PrivateMail-Neon-300x250.gif`

**Comment by Alex-302** [comment]
Every banner can by easily changed)

**Pull request closed without merging**
