### PR TITLE
filmsezonu.com

### PR DESCRIPTION
**Pull request by gork7777**
##### To avoid invalid pull requests, please check and confirm following checkboxes:

        
  - [x] This is not an ad/bug report;
  - [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
  - [x] I have performed a self-review of my own changes;
  - [x] My changes do not break web sites, apps and files structure.

##### If the problem does not fall under any category that is listed here, please contact our tech support: `support@adguard.com`

  - [x] Missed ads or ad leftovers;
  - [ ] Website or app doesn't work properly;
  - [ ] AdGuard gets detected on a website;
  - [ ] Missed analytics or tracker;
  - [ ] Social media buttons — share, like, tweet, etc;
  - [ ] Annoyances — pop-ups, cookie warnings, etc.
  
### What issue is being fixed?
[##### Enter the issue address:

Example: https://github.com/AdguardTeam/AdguardFilters/issues/100000
](https://github.com/AdguardTeam/AdguardFilters/issues/118533)

### Terms

  - [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met.

### CODE REVIEW

**Review by zloyden — APPROVED** [review]

**Comment by gork7777** [comment]
@zloyden You can add this too please?

**Comment by zloyden** [comment]
@gork7777 what do you mean?)

**Comment by gork7777** [comment]
@zloyden I mean "Removed old domain" commit, I added later after your merge.

**Comment by zloyden** [comment]
I see. Yep, I did it.

**Pull request merged**
