### PR TITLE
cartoonprn.com

### PR DESCRIPTION
**Pull request by gork7777**
issue: #88949

### CODE REVIEW

**Comment by Yuki2718** [comment]
The top banner is self-promo so should be addressed in Annoyances.

**Comment by Sergey-Lyapin** [comment]
> The top banner is self-promo so should be addressed in Annoyances.

I agree
@gork7777

**Comment by gork7777** [comment]
@Sergey-Lyapin Do I add the same rules like these?

**Comment by Sergey-Lyapin** [comment]
@gork7777 
hmm i think better `cartoonprn.com##a[href="https://cartoonprn.com/link/prngames/"] > img` to self promo
(and remove the domain from `##.top`)

**Comment by gork7777** [comment]
Done.

**Review by zloyden — APPROVED** [review]

**Pull request merged**
