### PR TITLE
fix #40825 extreme-down.xyz

### LINKED ISSUE #40825: extreme-down.xyz
### Issue URL (Incorrect Blocking)
[https://www.extreme-down.xyz/home.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.extreme-down.xyz%2Fhome.html)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>
<details>
  <summary>Screenshot 2</summary>

  Screenshot 2
</details>

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 1.5.4
Browser: | Safari
Filters: | AdGuard Base
Other extensions used: | aucun

### PR DESCRIPTION
**Pull request by zloyden**
https://github.com/AdguardTeam/AdguardFilters/issues/40825

### CODE REVIEW

**Comment by BlazDT** [comment]
Did you test for popunders? The unblocked script contains code for popunders (puShown). Maybe simply $empty,important may work too.

**Comment by zloyden** [comment]
Yes, I noticed that. Also tested with `empty` like `||pubdirecte.com^$empty,important`. The page didn't open.

**Comment by AdamWr** [comment]
I think that this rule should be added also for iOS platform.

**Comment by zloyden** [comment]
I made the rule more specific and added iOS platform.

**Review by AdamWr — APPROVED** [review]

**Review by BlazDT — APPROVED** [review]

**Pull request merged**
