### PR TITLE
cengage - tracking

### PR DESCRIPTION
**Pull request by shreyasminocha**
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Cengage makes several tracking and analytics requests.

Reproducing this is gatekept behind having an account and probably even an expensive subscription, so here are some screenshots of the offending requests in dev tools. 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshots:</summary>

activity
profile
resource-interactions
analytics

</details><br/>

### CODE REVIEW

**Comment by Alex-302** [comment]
Which site?

**Comment by Alex-302** [comment]
I don't see these requests.

**Comment by shreyasminocha** [comment]
> Reproducing this is gatekept behind having an account and probably even an expensive subscription

It's probably because they're made only when a user is signed in. Here's a video demo:

https://user-images.githubusercontent.com/11537232/152407486-151b6fa3-c118-4f7d-a628-a6eb926b1163.mp4

**Review by Alex-302 — CHANGES_REQUESTED** [review]
Wrong file. Please move to Tracking Protection filter

**Pull request closed without merging**
