### PR TITLE
fix #54999 mac-torrent-download.net

### LINKED ISSUE #54999: mac-torrent-download.net
### Issue URL (Incorrect Blocking)
 [https://mac-torrent-download.net/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fmac-torrent-download.net%2F)
### Comment
Username: @Oleg-Chashko
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>
<details>
  <summary>Screenshot 2</summary>

  Screenshot 2
</details>

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 1.7.4
Browser: | Safari
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Russian, <br/>AdGuard German

### PR DESCRIPTION
**Pull request by Sergey-Lyapin**
#54999

### CODE REVIEW

**Comment by AdamWr** [comment]
Does this old/previous rule (`#%#//scriptlet("abort-on-property-read", "scpLoadCh")`) break something or just doesn't work with AdGuard extension for Safari?

**Comment by Sergey-Lyapin** [comment]
> Does this old/previous rule (`#%#//scriptlet("abort-on-property-read", "scpLoadCh")`) break something or just doesn't work with AdGuard extension for Safari?

The old scriptlet just doesn't work

**Comment by AdamWr** [comment]
Ok, thank you for your answer :)

**Review by AdamWr — APPROVED** [review]

**Comment by Sergey-Lyapin** [comment]
You are welcome =)

**Pull request merged**
