### PR TITLE
Fix typo in Base filter

### PR DESCRIPTION
**Pull request by Yuki2718**
Unescaped period in regex

### CODE REVIEW

**Comment by Alex-302** [comment]
This is not a typo) Easier to search.

**Comment by Yuki2718** [comment]
> This is not a typo) Easier to search.

You mean it's better for management/maintenance?

**Comment by Alex-302** [comment]
invoke.js visually better distinguishable

**Comment by gwarser** [comment]
This will not help - character sets will prevent tokenization - `...[a-z0-9]...` uBO simply looks for `[` and `(` (`this.reRegexTokenAbort = /[([]/;`) and breaks.

**Comment by Yuki2718** [comment]
@gwarser Thanks for pointing my misunderstand out!
@Alex-302 Sorry, please forget about this!

**Pull request closed without merging**
