### PR TITLE
konyaninnabzi.web.tr

### PR DESCRIPTION
**Pull request by gork7777**
issue: #94153

Not sure this rule is correct: `konyaninnabzi.web.tr##div.haberpaylas > span:first-child` (share title "paylaş")

### CODE REVIEW

**Review by zloyden — COMMENTED** [review]
This website has low visitors.

**Comment by gork7777** [comment]
How can I check for there's how many visitors?

**Comment by zloyden** [comment]
You can use resources like `similarweb` for this. According to Alexa, they have 4780 visitors.

**Comment by zloyden** [comment]
> Not sure this rule is correct: `konyaninnabzi.web.tr##div.haberpaylas > span:first-child` (share title "paylaş")

According to their code, you can use these rules.
```
konyaninnabzi.web.tr##.haberpaylas > span
konyaninnabzi.web.tr##.haberpaylas > span + div.habersosyalpaylas
```

**Pull request closed without merging**
