### PR TITLE
fix #29104 nomanssky.com

### LINKED ISSUE #29104: nomanssky.com
### Issue URL (Incorrect Blocking)
[https://www.nomanssky.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.nomanssky.com%2F)
### Comment
Username: @MindTooth
> Seems that the've added a new cookie warning.  And this breaks the site.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>
<details>
  <summary>Screenshot 2</summary>

  Screenshot 2
</details>

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 1.2.1
Browser: | Safari
Filters: | EasyList,<br>AdGuard Safari,<br>AdGuard Annoyances,<br>AdGuard Base,<br>Dandelion Sprout's Norwegian Filters,<br>AdGuard Spyware,<br>AdGuard Social Media
Other extensions used: | 1Password

### PR DESCRIPTION
**Pull request by slavaleleka**
https://github.com/AdguardTeam/AdguardFilters/issues/29104

### CODE REVIEW

**Comment by BlazDT** [comment]
Why not this rule to hide overlay? Scrolling worked fine on my iPad or is scrolling not working on Safari extension?

`nomanssky.com##.cli-show`

**Comment by slavaleleka** [comment]
scrolling isn't working on Safari extension and on Android with AG Content Blocker, but works fine on my iPad too

**Comment by BlazDT** [comment]
Then please modify the platform to not include iOS and add the rule I mentioned for overlay ( best to exclude safari extension and content blocker then)

**Comment by slavaleleka** [comment]
`!+ PLATFORM(ios)`
`nomanssky.com##.cli-show`

if I do so I guess there is no need for exluding safari ext and cb, isn't it?

**Review by Alex-302 — APPROVED** [review]

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
