### PR TITLE
inshorts.com #93833

### PR DESCRIPTION
**Pull request by ghost**
Added to `mobile-app.txt` without comment.

### CODE REVIEW

**Comment by Sergey-Lyapin** [comment]
@Mennaruuk 
please place your rule under this rule: abema.tv##.com-application-MobileHeaderAppButton
(you can do it in thе current branch, just make a new commit and push)

**Comment by Mennaruuk** [comment]
Thanks for being patient with me. Really appreciate it. I put the line under the abema.tv one.

**Comment by Sergey-Lyapin** [comment]
@Mennaruuk
No problem, you forget to remove the rule at the bottom =)

**Comment by Sergey-Lyapin** [comment]
@Mennaruuk
BTW please name your commits (first commit at least) like this: `fix #93833 inshorts.com` (then the tasks will automatically close after the merge) and your branches like: `fix/#93833_inshorts.com`. And please don't forget to add a link to the issue to PR's description.

**Comment by Mennaruuk** [comment]
I most definitely will!!

**Pull request merged**
