### PR TITLE
#71968 withukor.com (Spyware Filters)

### PR DESCRIPTION
**Pull request by wout-codes**
#71968

### CODE REVIEW

**Comment by piquark6046** [comment]
`http://t1.daumcdn.net/kas/static/ba.min.js`
https://github.com/AdguardTeam/AdguardFilters/pull/71970#issuecomment-757481348

**Comment by wout-codes** [comment]
> 
> 
> `http://t1.daumcdn.net/kas/static/ba.min.js`
> [#71970 (comment)](https://github.com/AdguardTeam/AdguardFilters/pull/71970#issuecomment-757481348)

? What should I do?

**Comment by piquark6046** [comment]
> 
> 
> > `http://t1.daumcdn.net/kas/static/ba.min.js`
> > [#71970 (comment)](https://github.com/AdguardTeam/AdguardFilters/pull/71970#issuecomment-757481348)
> 
> ? What should I do?

Just a reference.

**Comment by wout-codes** [comment]
> 
> 
> > > `http://t1.daumcdn.net/kas/static/ba.min.js`
> > > [#71970 (comment)](https://github.com/AdguardTeam/AdguardFilters/pull/71970#issuecomment-757481348)
> > 
> > 
> > ? What should I do?
> 
> Just a reference.

Oh okay thanks.

**Pull request closed without merging**
