### PR TITLE
youtube.com - Social

### PR DESCRIPTION
**Pull request by 4n7hony**
### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

## What problem does the pull request fix?

It removes a social icon from the share popup in the shorts player.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [x] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

## What issue is being fixed?

<https://github.com/AdguardTeam/AdguardFilters/issues/150758#issuecomment-1547061729>

### Add your comment and screenshots

I modified a filter to remove every social icon except for the "Embed" icon in the share panel. The share panel in the shorts player doesn't have an embed button and a social icon (either WhatsApp if you're logged out or Facebook if you're logged in) wasn't being affected by the old filter. With this fix it should work both on the normal and the shorts player. I also removed the filter: `youtube.com##button[title="WhatsApp"]` because it shouldn't be needed anymore.

<details>

<summary>Before:</summary>

</details>

<details>

<summary>After:</summary>

</details>

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Review by krystian3w — APPROVED** [review]

**Comment by krystian3w** [comment]
> ```adb
> youtube.com##button[title="WhatsApp"]
> ```

These can be forced for legacy supported iOS 14 and iPadOS 14: https://adguard.com/en/blog/adguard-4-3-for-ios.html

Until google turns it off watch YT on Safari 14.

> screen from devtools, not real iPhone/iPad

**Comment by Alex-302** [comment]
Can't reproduce

<details>
<summary>Details</summary>

image


</details>

We use two rules to awoid of using extended css. Firefox has no `:has()` native support.

**Comment by 4n7hony** [comment]
I just tested it again and I am still able to reproduce this issue. While logged off I get the same result you got, but if I log in I get a Facebook icon there. Could it be that YouTube changes the order of the icons for different users? ¯\_(ツ)_/¯

<details>
<summary>When I'm logged in</summary>

</details>

<details>
<summary>When I'm not logged in</summary>

</details>

That WhatsApp icon was removed using this filter: `youtube.com##button[title="WhatsApp"]` which was added in this commit https://github.com/AdguardTeam/AdguardFilters/commit/f58179f5c1cb8c85ac6ebb3e6cf061e827ba7652 to fix this issue https://github.com/AdguardTeam/AdguardFilters/issues/149322#issuecomment-1526871167. 

Should this filter be added too? `youtube.com##button[title="Facebook"]`

Also sorry I had completely forgot that Firefox doesn't support the :has() pseudo-class natively. I tried to write a filter that removes the social icons, while leaving there the "Embed" one, and that doesn't involve extended css but I'm afraid it is not possible, at least according to my brain.

**Comment by Alex-302** [comment]
Ok, added `youtube.com##button[title="Facebook"]`

**Pull request closed without merging**
