### PR TITLE
Fix #168316 www.base64decode.org

### LINKED ISSUE #168316: www.base64decode.org
### Issue URL (Annoyance)
 [https://www.base64decode.org/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.base64decode.org%2F)

### [NSFW] Screenshots
<details>
  <summary>Screenshot 1</summary>

  [Screenshot 1](https://cdn.adguard.info/sitereports/h01irh0pz9k48s0wgo4ocgwwkkos044olcrhqzauj4.png?nc=1)
</details>

### System configuration

Information | Value
--- | ---
AdGuard product: | AdGuard for Windows v7.14
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Block WebRTC, <br>Block Push API, <br>Block Location API, <br>Strip URLs from tracking parameters, <br>Hide your search queries, <br>Hide your Referrer from third-parties, <br>Hide your User-Agent, <br>Remove X-Client-Data header from HTTP requests, <br>Protect against DPI, <br>Self-destructing third-party cookies (180), <br>Disable cache for third-party requests, <br>Block third-party Authorization header, <br>Disable Windows Telemetry, <br>Turn off Advertising ID
DNS filtering: | server: `System`<br>
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>Web Annoyances Ultralist<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js

### PR DESCRIPTION
**Pull request by xglossyntx**
# Creating the pull request

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [x] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

### Enter the issue address

#168316 

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Comment by BlazDT** [comment]
Hidden by generic rule in base filter:
`##.adsbypublift`

**Comment by Alex-302** [comment]
Same. 
@xglossyntx Is HTTPS filtering works?

**Comment by xglossyntx** [comment]
> Same. @xglossyntx Is HTTPS filtering works?

I was using the browser extension on Firefox, and I dont not believe there is an option called "HTTPS filtering".

**Comment by xglossyntx** [comment]
image

**Comment by xglossyntx** [comment]
It only happens on Firefox. When I tried on Brave, it was blocked.

**Comment by Alex-302** [comment]
Clean in FF on my end:

<details>
<summary>Details</summary>

image


</details>

**Comment by xglossyntx** [comment]
> Clean in FF on my end:
> Details

It must just not be like me because it's doing it on my phone as well.

**Comment by xglossyntx** [comment]
@zloyden could you take a look?

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/168370#issuecomment-2139314280 I see the element in the code, but it's blocked by the rule below.
```adblock
##ins.adsbygoogle[data-ad-slot]
```

**Comment by zloyden** [comment]
Show the code of the element here. That rule should be fine for this.
```adblock
base64decode.org##.ad_corner
```

**Comment by xglossyntx** [comment]
That rule fixes it.

**Comment by xglossyntx** [comment]
Saved page

[Base64 Decode and Encode - Online.zip](https://github.com/AdguardTeam/AdguardFilters/files/15499986/Base64.Decode.and.Encode.-.Online.zip)

**Comment by Alex-302** [comment]
It is an edge case. No one uses browser with 741x546 resolution.

**Comment by xglossyntx** [comment]
It also does it at larger resolutions; it just seems to do it more often at smaller ones.

**Comment by xglossyntx** [comment]
At 1920x1080 or higher, it does not seem to do it at all.

**Comment by xglossyntx** [comment]
These could also be added to the rule; they all do the same thing.

``https://www.urldecoder.org/``
``https://www.urlencoder.org/``
``https://www.minifyjson.org/``
``https://www.beautifyjson.org/``
``https://www.uglifyjs.net/``
``https://www.prettifyjs.net/``
``https://www.uglifycss.com/``
``https://www.prettifycss.com/``

**Comment by Alex-302** [comment]
It looks like extra minor problem. I can reproduce with size, when these tools are literally not usable.

Btw I prefer their tools https://www.site24x7.com/tools/

**Comment by xglossyntx** [comment]
idk about the other tools about base64decode works fine at smaller window sizes 
<details>
  <summary>Screenshot</summary>
  
image

**Pull request closed without merging**
