### PR TITLE
fix #79851 dashdot.de

### LINKED ISSUE #79851: dashdot.de
### Issue URL (Incorrect Blocking)
 [https://dashdot.de/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdashdot.de%2F)
### Comment
Username: @Morku
> Unblocked cookie grey

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>
<details>
  <summary>Screenshot 2</summary>

  Screenshot 2
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.3
Browser: | Firefox
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters
DNS filtering: | server: `Cloudflare DNS-over-HTTPS`<br>filters: `"AdGuard DNS filter" with AdGuard Home`
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Russian, <br/>AdGuard German
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js

### PR DESCRIPTION
**Pull request by wout-codes**
#79851

### CODE REVIEW

**Comment by wout-codes** [comment]
@BlazDT You're bias.

**Comment by BlazDT** [comment]
Only saw your pull after doing commit, therefore closed without comment.

**Comment by wout-codes** [comment]
Then tell me, what's the purpose of creating PR's if it get closed for useless reasons like yours?

**Comment by BlazDT** [comment]
There are some cases in which we see the issue and fixing it and then when closing the issue via button we only see the pull request.
I am sorry. I will check issues for pull requests first and then fixing them if none is shown.

**Pull request closed without merging**
