### PR TITLE
Fix cafe.naver.com & blog.naver.com

### LINKED ISSUE #69674: cafe.naver.com
### Issue URL (Incorrect Blocking)
 [https://cafe.naver.com/joonggonara](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fcafe.naver.com%2Fjoonggonara)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>
<details>
  <summary>Screenshot 2</summary>

  Screenshot 2
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.3
Browser: | Chrome
AdGuard driver: | WFP
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> List-KR, <br/>AdGuard Japanese

### PR DESCRIPTION
**Pull request by ghost**
#69674 #69524 #69733

### CODE REVIEW

**Comment by Yuki2718** [comment]
I think in this case it's better to fine-tune the block rule than adding exception. E.g. limit to $image

**Comment by piquark6046** [comment]
> I think in this case it's better to fine-tune the block rule than adding exception. E.g. limit to $image

OK. I will check these.

**Comment by Sergey-Lyapin** [comment]
Strange, but I can't reproduce.
Btw I support @Yuki2718, It's better to narrow the blocking rule

**Comment by Yuki2718** [comment]
@Sergey-Lyapin Follow the instruction here: https://github.com/AdguardTeam/AdguardFilters/issues/69674#issuecomment-742590721

**Comment by piquark6046** [comment]
@Yuki2718 
Tracker Type: image
Non-Tracker Type: Subdocument

**Comment by AdamWr** [comment]
@piquark6046 Okay, so could you please add `$image` modifier to this rule:
https://github.com/AdguardTeam/AdguardFilters/blob/c474b6fb13291a383390a310c03b7e0b5d936c46/SpywareFilter/sections/specific.txt#L29
instead of adding exception?

I mean `||cc.naver.com/cc$image`, like proposed in this comment - https://github.com/AdguardTeam/AdguardFilters/pull/69724#issuecomment-743062438

**Comment by piquark6046** [comment]
> 
> 
> @piquark6046 Okay, so could you please add `$image` modifier to this rule:
> 
> https://github.com/AdguardTeam/AdguardFilters/blob/c474b6fb13291a383390a310c03b7e0b5d936c46/SpywareFilter/sections/specific.txt#L29
> 
> instead of adding exception?
> 
> I mean `||cc.naver.com/cc$image`, like proposed in this comment - [#69724 (comment)](https://github.com/AdguardTeam/AdguardFilters/pull/69724#issuecomment-743062438)

Okay. Please wait.

**Comment by piquark6046** [comment]
Updated at e8dd714dfd6417bd0e92c82f2710a85fd09fac9b. please check it out.

> 
> 
> @piquark6046 Okay, so could you please add `$image` modifier to this rule:
> 
> https://github.com/AdguardTeam/AdguardFilters/blob/c474b6fb13291a383390a310c03b7e0b5d936c46/SpywareFilter/sections/specific.txt#L29
> 
> instead of adding exception?
> 
> I mean `||cc.naver.com/cc$image`, like proposed in this comment - [#69724 (comment)](https://github.com/AdguardTeam/AdguardFilters/pull/69724#issuecomment-743062438)

**Review by zloyden — APPROVED** [review]

**Review by AdamWr — APPROVED** [review]

**Comment by AdamWr** [comment]
Thank you :)

**Pull request merged**
