### PR TITLE
iqiyi, sohu & youku tracking params

### PR DESCRIPTION
**Pull request by MkQtS**
Add iqiyi, sohu & youku tracking params.

### CODE REVIEW

**Comment by Alex-302** [comment]
Hi. 
Need sample links with parameters and pages where we can check.

**Comment by MkQtS** [comment]
Hi, here are some sample links:

```
https://www.iqiyi.com/v_22vgsxoairc.html?vfrm=pcw_home&vfrmblk=712211_cainizaizhui&vfrmrst=712211_cainizaizhui_title3
https://www.sohu.com/a/539109343_116237?scm=1004.759738464039272448.0.0.0&spm=smpc.home.business-news12.4.1650333115143547IHFl
https://m.sohu.com/a/539176908_116237?_trans_=010004_pcwzy
https://mp.sohu.com/profile?xpt=c29odXptdGp4emFlc0Bzb2h1LmNvbQ==&_f=index_pagemp_1&spm=smpc.content.author.2.1650333170951Rdnd4qz
https://v.youku.com/v_show/id_XNTIwNTM1NzI4MA==.html?spm=a2ha1.14919748_WEBHOME_GRAY.homepage_vipyindao.d_zj2_2&s=fceeead25d2a4a86951b&scm=20140719.rcmd.27501.show_fceeead25d2a4a86951b
https://v.youku.com/v_show/id_XNTg1NzQyNjMxMg==.html?ptag=vsogou
```

**Comment by Alex-302** [comment]
Ok, and everything works fine?

**Review by Alex-302 — APPROVED** [review]

**Comment by Yuki2718** [comment]
Is there a reason not to trim www on `iqiyi.com`? Also does `$removeparam=/^vfrm/` break something?

**Comment by MkQtS** [comment]
> Is there a reason not to trim www on `iqiyi.com`? Also does `$removeparam=/^vfrm/` break something?

There is no absolute reason. My initial purpose is removing unwanted params on the video playing page, and within my reach, all videos on iqiyi are sited as `www.iqiyi.com/xxx.html`. I didn't try `$removeparam=/^vfrm/`, and I use 3 seperated rules just out of habit.

`||iqiyi.com^$removeparam=/^vfrm/` works fine in my limited number of tests. No other background connection url are changed except the target, and videos can be played as normal.

**Comment by Yuki2718** [comment]
@MkQtS Thx, was just curious. I'll only trim www down and keep vfrm* parameters in case of unexpected trouble.

**Pull request merged**
