### PR TITLE
Addressed in PersianBlocker

### PR DESCRIPTION
**Pull request by MasterKia**
1- Remove Persian filters from AdGuard Base Ads filterlist, addressed in PersianBlocker https://github.com/MasterKia/PersianBlocker/commit/a749742d6b67fcdf9d50c3f5ac09418018494b71

2- Remove unbreak filters from AdGuard Whitelist, addressed in PersianBlocker, revert https://github.com/AdguardTeam/AdguardFilters/commit/61a71a67c40c30dba39e01033c19a1c3544f46fd
Please keep the `tamin.ir` filters since it's an important government site, but EasyList refused to fix it.
https://github.com/easylist/easylist/issues/12152

https://github.com/AdguardTeam/FiltersRegistry/pull/623
https://github.com/MasterKia/PersianBlocker

### CODE REVIEW

**Comment by MasterKia** [comment]
Feel free to tag me if users send report for Persian sites here and I'll add the filters to PersianBlocker.

**Review by zloyden — APPROVED** [review]

**Comment by Alex-302** [comment]
Better leave it as is for the first time.

**Comment by MasterKia** [comment]
Alright, though I didn't check the filters in AdGuard Base list for breakage/conflicts with PersianBlocker.

**Comment by Alex-302** [comment]
Obsolete. Many changes.

**Comment by MasterKia** [comment]
Then please manually remove these filters to prevent conflict with the regional list.

**Comment by Alex-302** [comment]
ok.

**Pull request closed without merging**
