### PR TITLE
update #75796 masalaseen.net

### PR DESCRIPTION
**Pull request by wout-codes**
#75796

### CODE REVIEW

**Comment by Yuki2718** [comment]
You can either remove `[src]` and `[href]` or attribute null string and simplify the path. Since `a` tag almost always has `href` attribute and `img` does `src`, these don't narrow down targets but null string is not so common.

**Comment by wout-codes** [comment]
> 
> 
> You can either remove `[src]` and `[href]` or attribute null string and simplify the path. Since `a` tag almost always has `href` attribute and `img` does `src`, these don't narrow down targets but null string is not so common.

You mean the unknown?

**Comment by Yuki2718** [comment]
`href=""`

**Comment by wout-codes** [comment]
@Yuki2718 `masalaseen.net##center > div > a[href=""][target="_blank"] > img`

**Review by Yuki2718 — APPROVED** [review]

**Pull request closed without merging**
