### PR TITLE
Fix #148831 obozrevatel.com

### LINKED ISSUE #148831: war.obozrevatel.com
### Issue URL (Social Widget)
 [https://war.obozrevatel.com/ukr/namagayutsya-ne-vidstavati-yak-dvijniki-putina-izdyat-na-front-i-do-chogo-tut-zelenskij.htm](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwar.obozrevatel.com%2Fukr%2Fnamagayutsya-ne-vidstavati-yak-dvijniki-putina-izdyat-na-front-i-do-chogo-tut-zelenskij.htm)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.4.6
Browser: | Safari
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media, <br/>Fanboy's Social Blocking List<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>AdGuard Cookie Notices, <br/>AdGuard Popups, <br/>AdGuard Mobile App Banners, <br/>AdGuard Other Annoyances, <br/>AdGuard Widgets, <br/>Adblock Warning Removal List, <br/>Fanboy's Annoyances, <br/>Web Annoyances Ultralist<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>AdGuard Ukrainian

### PR DESCRIPTION
**Pull request by gork7777**
### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [x] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [x] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

### Enter the issue address

https://github.com/AdguardTeam/AdguardFilters/issues/148831

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Review by piquark6046 — CHANGES_REQUESTED** [review]
It can be merged with `obozrevatel.com##.headerBiding` in AdGuard Russian filter.
Please move the rule existing in AdGuard Russian filter into `/CyrillicFilters/common-sections/specific.txt`.

**Comment by gork7777** [comment]
@piquark6046 Should I remove `obozrevatel.com##.headerBiding` rule from Russian and Ukranian?

**Comment by piquark6046** [comment]
`obozrevatel.com##.headerBiding` does not exist in AdGuard Ukranian filter.

**Comment by gork7777** [comment]
> `obozrevatel.com##.headerBiding` does not exist in AdGuard Ukranian filter.

Yeah, I mean in this PR rule.

**Comment by piquark6046** [comment]
Yes. During that AdGuard filter compiler complies them, the rules existing in `/CyrillicFilters/common-sections/` will be included.

https://github.com/AdguardTeam/FiltersRegistry/blob/f893bc3636015541e4f5b64a5fa8b7c58ad9f21b/filters/filter_23_Ukrainian/template.txt#L37

**Review by piquark6046 — APPROVED** [review]

**Pull request merged**
