### PR TITLE
fix #80460 watchseries.ninja

### LINKED ISSUE #80460: www4.watchseries.ninja
### Issue URL (Ads)
 [https://www4.watchseries.ninja/episode/castle-season-5-episode-17/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww4.watchseries.ninja%2Fepisode%2Fcastle-season-5-episode-17%2F)
### Comment
Username: @nschdeva
> Clickprovider style ads anytime I click anywhere it opens a new window/tab.
> It also repeats re generating all these ads after a while

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.3
Browser: | Edge 89.0.774.76 (Chromium-based)
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Self-destructing first-party cookies (4320), <br>Self-destructing third-party cookies (180), <br>Block Push API, <br>Block Location API
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances
Userscripts: | https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
Referrer: | [https://www4.watchseries.ninja/episode/castle-season-5-episode-16/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww4.watchseries.ninja%2Fepisode%2Fcastle-season-5-episode-16%2F)

### PR DESCRIPTION
**Pull request by wout-codes**
#80460

### CODE REVIEW

**Comment by Yuki2718** [comment]
@wout-codes Add _pop filters too?

**Comment by wout-codes** [comment]
Which one @Yuki2718 ? the json-prune one or aopw, _pop?

**Comment by Yuki2718** [comment]
aopw and HTML filter

**Comment by wout-codes** [comment]
Ok.

**Review by AdamWr — APPROVED** [review]

**Pull request merged**
