### PR TITLE
Disabling overwriting clipboard

### PR DESCRIPTION
**Pull request by BlazDT**
More details here: https://bugs.chromium.org/p/chromium/issues/detail?id=1334203
Test page: https://output.jsbin.com/yuliwoz/quiet

Feature can be used to put advertising in clipboard.

### CODE REVIEW

**Review by zloyden — APPROVED** [review]

**Comment by AdamWr** [comment]
I suppose that it also can be used to useful things (like, for example, button to copy image/text to clipboard, or something similar), maybe it would be better to add it to `Tracking Protection` filter, though I'm still not sure.
By the way, it seems that there is also `navigator.clipboard.writeText` which can also be abused.

**Comment by BlazDT** [comment]
I added to main filter as it can be abused for every purpose.

**Comment by Alex-302** [comment]
Many users use password managers. How will this protect them?

**Comment by BlazDT** [comment]
Added other method to write and both .read (reading rules should be removed when Chrome fixed the issue).

**Comment by krystian3w** [comment]
Demo no longer work in Canary 107.

**Comment by BlazDT** [comment]
So seems to be fixed by Google :)

**Comment by krystian3w** [comment]
Or Chromium community or MS team (this is not related with Alphabet corporation) and planned publish on 25 October.

**Pull request closed without merging**
