### PR TITLE
fix #70080 hitbits.io

### LINKED ISSUE #70080: hitbits.io
### Issue URL (Anti Adblock Script)
 [https://hitbits.io/slk/adblock](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fhitbits.io%2Fslk%2Fadblock)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.25
Browser: | Chrome
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Adblock Warning Removal List<br/><br/><b>Security:</b><br/> Online Malicious URL Blocklist, <br/>NoCoin Filter List<br/><br/><b>Other:</b><br/> BarbBlock<br/><br/><b>Language-specific:</b><br/> Liste AR

### PR DESCRIPTION
**Pull request by barhamkbarham**
https://github.com/AdguardTeam/AdguardFilters/issues/70080

### CODE REVIEW

**Comment by Alex-302** [comment]
What is the purpose of this rule?

**Comment by BarhamBasha** [comment]
Fix the issue that prevents the visitor from browsing the site while the adblocker is running.

**Comment by Yuki2718** [comment]
The filter itself is okay, but do not merge with a filter for another issue just because they share the same component - in some cases you should actually do so (e.g. common scriptlet filters) but this is not the case. Also we have to take Content blocker into account where neither of redirect, scriptlet, or css filter is available. In this case make it like this (I would omit `ad` subdomain but it may be a matter of preference) as I didn't see ads even if the request is allowed:
```
! https://github.com/AdguardTeam/AdguardFilters/issues/70080
||a-ads.com/*?size=$xmlhttprequest,redirect=nooptext,domain=hitbits.io,important
@@||a-ads.com/*?size=$xmlhttprequest,domain=hitbits.io
```
Put them on top of other individual issue solution. Also you can just put a issue link as you correctly named the commit title.

**Review by zloyden — APPROVED** [review]

**Comment by zloyden** [comment]
Ok, I made a changes directly to this PR. @BarhamBasha @Yuki2718 thanks :)

**Pull request merged**
