### PR TITLE
Fix nicochannel design websites - social (/news page)

### PR DESCRIPTION
**Pull request by SKEIDs**
# Creating the pull request

> Please include a summary of the change and which issue is fixed\
> If the related issue does not exist in our repository, please create it before making pull request\
> It is highly recommended to use our [Web Reporting Tool](https://kb.adguard.com/technical-support/reporting-tool) instead of creating an issue on GitHub directly\
> Please note, that we verify every pull request manually, so it may take time to apply it

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [x] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

### Add your comment and screenshots

These websites have a common design with nicochannel.

<details><summary>screenshot(example) - qrpf1.com</summary>

</details><br/>

```
https://qrpf1.com/articles/news/arLPD4jZNBxfHLynE3Ppbr23
https://hyakuta.com/articles/news/arrtHmh4XcFCRXevSeEo3MHg
https://banbanzai-fc.com/articles/news/arBcBQnsB6ewXPcftk6vzHSE
https://pizzaradio.jp/articles/news/ar5AaLPXayaDHujtfkSDJi2d
https://gs-ch.com/articles/information/arGecNgrCeFErHyyD8jWWj2U
https://p-jinriki-fc.com/articles/news/arn2bFcMAjzeaJHyyGm27qb5
```

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Review by zloyden — CHANGES_REQUESTED** [review]
The domains below have low visitors. Please remove them from the pull request.
```
p-jinriki-fc.com,pizzaradio.jp,banbanzai-fc.com,hyakuta.com,qrpf1.com
```

**Comment by SKEIDs** [comment]
> The domains below have low visitors. Please remove them from the pull request.
> 
> ```
> p-jinriki-fc.com,pizzaradio.jp,banbanzai-fc.com,hyakuta.com,qrpf1.com
> ```

I know that has low visitor.
But,I have seen issues about these websites for some time.
I think that the issues will be posted repeatedly until they are supported.
I think it would be better for the future to add them all together, in my opinion.

**Comment by zloyden** [comment]
I got it, but those sites can't be added due to our filters policy.

**Comment by SKEIDs** [comment]
> I got it, but those sites can't be added due to our filters policy.

I see. how about move to generic rule?

**Comment by zloyden** [comment]
I assume we will consider this later on.
You can keep, as I recall, one domain here for now.

**Comment by SKEIDs** [comment]
I understand. I will wait.

As far as I can tell from my light research, the following four domains have enough visitors.
`gs-ch.com,canan8181.com,rnqq.jp,nicochannel.jp`
I also think that the number of websites with nicochannel designs will continue to grow.

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/155755#issuecomment-1629180974 could you provide URLs of the domains? Also add them to the description.

**Comment by SKEIDs** [comment]
> https://github.com/AdguardTeam/AdguardFilters/pull/155755#issuecomment-1629180974 could you provide URLs of the domains? Also add them to the description.

These domains are already added for the rule.

**Review by zloyden — APPROVED** [review]

**Pull request merged**
