### PR TITLE
QQMusic ads

### PR DESCRIPTION
**Pull request by DeepChirp**
When you open QQ Music, you will find that the app has opening screen ads.
Ad address example: http://pgdt.gtimg.cn/141/20204/snscosdownload/SZ/reserved/60fff7c10000e95800000000261156090000008d00004eec?m=428400df768d80ecb881677ed75370ca&ck=428400df768d80ecb881677ed75370ca
Screenshot_2021-08-04-08-41-53-804_com tencent qqmusic
Screenshot_2021-08-03-19-16-52-727_com adguard android

### CODE REVIEW

**Review by Alex-302 — APPROVED** [review]

**Review by Alex-302 — CHANGES_REQUESTED** [review]
please add `$app` modifier

**Comment by Alex-302** [comment]
or maybe more specific rule:
`||pgdt.gtimg.cn/*/snscosdownload/*/reserved/$app=`

**Comment by Alex-302** [comment]
As I see in https://raw.githubusercontent.com/zqzess/rule_for_quantumultX/master/QuantumultX/rewrite/MyRewrite.conf
pgdt.gtimg.cn should not be blocked completely.

**Comment by shenzhiming88** [comment]
> or maybe more specific rule:
> `||pgdt.gtimg.cn/*/snscosdownload/*/reserved/$app=`

Fine. I'm going to edit it now. Thanks

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
