### PR TITLE
fix #77121 nrl.com

### LINKED ISSUE #77121: nrl.com
### Issue URL (Anti Adblock Script)
 [https://www.nrl.com/news/2021/03/05/storm-v-rabbitohs-heavyweights-looking-to-land-first-blow/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.nrl.com%2Fnews%2F2021%2F03%2F05%2Fstorm-v-rabbitohs-heavyweights-looking-to-land-first-blow%2F)
### Comment
Username: @TesterMan247
> 
> --
> The information below is automatically generated. Do not delete it.
> 
> Referrer:
> 
> 
> Custom userscripts:
> https://userscripts.adtidy.org/beta/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/beta/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.6 nightly 22
Browser: | Chrome
AdGuard driver: | WFP
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Security:</b><br/> Online Malicious URL Blocklist, <br/>NoCoin Filter List<br/><br/><b>Other:</b><br/> AdGuard Experimental

### PR DESCRIPTION
**Pull request by wout-codes**
#77121

### CODE REVIEW

**Comment by Sergey-Lyapin** [comment]
these rules don't work

**Comment by wout-codes** [comment]
@Sergey-Lyapin it works fine on my end. Try like two times.

**Comment by wout-codes** [comment]
I saw it in the code @Sergey-Lyapin. What do you recommend?

**Comment by Sergey-Lyapin** [comment]
@wout-codes
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=nrl.com`

**Pull request merged**
