### PR TITLE
fireforce-anime.jp 

### PR DESCRIPTION
**Pull request by SKEIDs**
https://github.com/AdguardTeam/AdguardFilters/issues/103674
 `fireforce-anime.jp###twidget`
<details><summary>Before</summary>

</details><br/>
<details><summary>After</summary>

</details><br/>

### CODE REVIEW

**Comment by Sergey-Lyapin** [comment]
@SKEIDs
Please name your first commit as `fix numberOfIssue domain`, for example for this issue: `fix #103674 fireforce-anime.jp`

**Comment by SKEIDs** [comment]
> @SKEIDs Please name your first commit as `fix numberOfIssue domain`, for example for this issue: `fix #103674 fireforce-anime.jp`

ok. I understand.

**Comment by SKEIDs** [comment]
> @SKEIDs In this case the issue will be closed automatically after merging PR.

I see.

**Comment by Sergey-Lyapin** [comment]
@AdamWr @zloyden Should we block the twitter widget here? Could you take a look? I'm not sure.

**Comment by AdamWr** [comment]
To be honest, I don't know.
I'm not sure what is a purpose of this website, if this twitter widget is not an important element, then I guess it can be blocked.

**Review by zloyden — COMMENTED** [review]
I think we should block it in the `AdGuard Social Media`, but what about the visitors? I don't see any statistics.

**Comment by Sergey-Lyapin** [comment]
Ok, we need a separate rule to block this widget completely, so it shouldn't be added because of visitors. I'll keep the rule for share leftover.

**Comment by zloyden** [comment]
@Sergey-Lyapin I'd found on their twitter enough followers, added the rules directly.

**Comment by Yuki2718** [comment]
> I don't know. I'm not sure what is a purpose of this website, if this twitter widget is not an important element, then I guess it can be blocked.

I'm not inclined to block this in this case even if the site had enough visitors. This is an official page of an anime and the widget serves as "What's new?".

**Comment by zloyden** [comment]
> I'm not inclined to block this in this case even if the site had enough visitors. The site is an official page of an anime and the widget serves as "What's new?".

Well, the user can just press the twitter button or disable AdGuard Social Media.
<details><summary>Screenshot:</summary>

image

</details><br/>

**Comment by Yuki2718** [comment]
> Well, the user can just press the twitter button or disable AdGuard Social Media.

Yep, redundancy is one thing - if user bothered to do so. This is probably grey zone and blocking the widget only makes the top image bigger while doesn't save scroll or something other than a little bandwidth. But it's not a too big matter anyway.

**Pull request merged**
