### PR TITLE
Fix #177597 jutarnji.hr

### LINKED ISSUE #177597: www.jutarnji.hr
### Issue URL (Ads)
 [https://www.jutarnji.hr/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.jutarnji.hr%2F)
Username: `@lica98`

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | Value
--- | ---
AdGuard product: | AdGuard for Android v4.4 Nightly 41
System version: | Android 13
Browser: | Chrome
AdGuard mode: | VPN
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Cookie Notices, <br/>AdGuard Popups, <br/>AdGuard Mobile App Banners, <br/>AdGuard Other Annoyances, <br/>AdGuard Widgets<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Spanish/Portuguese, <br/>AdGuard French, <br/>AdGuard Ukrainian, <br/>Official Polish filters for AdBlock, uBlock Origin & AdGuard, <br/>EasyList Czech and Slovak, <br/>Adblock List for Finland, <br/>Polish Anti Adblock Filters
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js<br>https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js

### PR DESCRIPTION
**Pull request by artemiv4nov**
Fix for #177597

### CODE REVIEW

**Review by piquark6046 — DISMISSED** [review]
Please rename title of the PR to `Fix #177597 jutarnji.hr`.

**Review by piquark6046 — COMMENTED** [review]
Please rename title of the PR to `Fix #177597 jutarnji.hr`.

**Review by piquark6046 — CHANGES_REQUESTED** [review]
Please move to `MobileFilter/sections/specific_web.txt`.

**Review by piquark6046 — APPROVED** [review]

**Review by AdamWr — APPROVED** [review]

**Comment by DandelionSprout** [comment]
I've been unusually busy with all sorts of projects so far this week, am hoping I'll handle it soon enough.

**Pull request merged**
