### PR TITLE
fix #77488 femdomtb.com

### LINKED ISSUE #77488: www.femdomtb.com
### Issue URL (Incorrect Blocking)
[NSFW] [http://www.femdomtb.com/videos/16088/ellakross-will-you-be-my-new-toilet-slave/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwww.femdomtb.com%2Fvideos%2F16088%2Fellakross-will-you-be-my-new-toilet-slave%2F)

### [NSFW] Screenshots
<details>
  <summary>Screenshot 1</summary>

  [Screenshot 1](https://reports-img.adguard.com/kqZkPJO.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  [Screenshot 2](https://reports-img.adguard.com/EDMDFJl.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.31
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (2880), <br>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Fanboy's Annoyances, <br/>Web Annoyances Ultralist, <br/>Adblock Warning Removal List<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard Turkish

### PR DESCRIPTION
**Pull request by wout-codes**
#77488

### CODE REVIEW

**Review by zloyden — APPROVED** [review]

**Comment by wout-codes** [comment]
@zloyden Do you think I can have write access? I will add commits for emergency issues only.

**Comment by zloyden** [comment]
We can consider this in perspective, but you need a little more practice.

**Comment by wout-codes** [comment]
> We can consider this in perspective, but you need a little more practice.

Yes, I agree, I need a bit more practice. As stated, I would only solve issues which I am quite sure of, and issues that are emergency or needs a fix immediately.

**Comment by wout-codes** [comment]
@zloyden To add more, I would mostly create Pull requests for issues that requires advanced syntax for example, `#$#` , `#?#`, etc and rules that I am not sure.

**Comment by ameshkov** [comment]
We are considering splitting the repo into two parts - one for basic rules and the other one - for more powerful rules, which can only be added through a pull request. Once this happens, write access can be a possibility.

**Comment by wout-codes** [comment]
> We are considering splitting the repo into two parts - one for basic rules and the other one - for more powerful rules, which can only be added through a pull request. Once this happens, write access can be a possibility.

Ok.

**Pull request merged**
