### PR TITLE
fix #79906 konosubamanga.com

### LINKED ISSUE #79906: konosubamanga.com
### Issue URL (Anti Adblock Script)
 [https://konosubamanga.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fkonosubamanga.com%2F)
### Comment
Username: @ahmad-wahyudin
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.34
Browser: | Firefox
Stealth mode: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Adblock Warning Removal List<br/><br/><b>Language-specific:</b><br/> AdBlockID

### PR DESCRIPTION
**Pull request by wout-codes**
#79906

### CODE REVIEW

**Comment by wout-codes** [comment]
@Sergey-Lyapin cybermania updated its script. That's why I added the domain there.

**Comment by Sergey-Lyapin** [comment]
@wout-codes
It looks like we need new rules for all platforms for cybermania, could you please add them in separate PR?

**Comment by wout-codes** [comment]
I will check and fix.

**Comment by wout-codes** [comment]
@Sergey-Lyapin I can fix it with a HTML Rules for other platforms easily. But I am not sure for platforms without HTML support. Could you please take a look?

**Comment by Sergey-Lyapin** [comment]
@wout-codes for platforms with scriptlets support:  https://github.com/AdguardTeam/AdguardFilters/commit/c625c9b12dabe8b4c954dc0490f55dc6f05531b7
rules for contents blockers still work

**Comment by wout-codes** [comment]
Thank you. I was sleepy that time.

**Pull request merged**
