### PR TITLE
 Anti-RightClick: cafe.naver.com

### PR DESCRIPTION
**Pull request by ghost**
### URLs (contain comparing URLs)
https://cafe.naver.com/bloodang/9942
https://cafe.naver.com/chamcham2/31945

https://cafe.naver.com/sbstvdocu/96301
https://cafe.naver.com/shibadokun/17477

### CODE REVIEW

**Comment by Yuki2718** [comment]
```
cafe.naver.com#%#//scriptlet('set-constant', 'document.oncontextmenu', 'null')
cafe.naver.com#%#//scriptlet('set-constant', 'document.onselectstart', 'null')
cafe.naver.com#%#//scriptlet('set-constant', 'document.ondragstart', 'null')
cafe.naver.com#$#body[style="user-select: none;"] { user-select: auto!important; }
```
work without causing contents hidden. BTW correct file is tweaks.txt

**Comment by piquark6046** [comment]
@Yuki2718 Thanks. Your contribution is recorded at https://github.com/AdguardTeam/AdguardFilters/pull/85068/commits/eaf2d58b26eccdb67d2d3416114272aca89f48b0 commit.

**Comment by Yuki2718** [comment]
@piquark6046 Don't forget to move to tweaks.txt ;) In the file comment line is not needed.

**Comment by AdamWr** [comment]
Does this rule - `cafe.naver.com#$#body[style="user-select: none;"] { user-select: auto!important; }` is really needed?
If so, could you please share/post a link to website which need this rule?

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/85068#issuecomment-857560172
Yes. If the rule does not applied, then a visitor cannot drag.
https://cafe.naver.com/bloodang/9942

Screenshot
(Browser: Firefox Developer Edition 90.0b5)

@AdamWr

**Review by AdamWr — APPROVED** [review]

**Comment by AdamWr** [comment]
Okay, I can reproduce it in Firefox, but not in Chrome (I mean `body[style="user-select: none;"]`).
Thank you for your reply.

**Pull request merged**
