### PR TITLE
fix #75857 lookmovie.io

### LINKED ISSUE #75857: lookmovie.io [Pop-Up]
https://lookmovie.io/

Popups seen on the page when clicking on the search icon. Checked with Chrome browser on Android. Please fix

### PR DESCRIPTION
**Pull request by wout-codes**
#75857
They changed their code a little which is causing pop-ups.

### CODE REVIEW

**Comment by wout-codes** [comment]
@zloyden Can I craft rules like this, or is there a common rule? If there is I couldn't find.

**Comment by zloyden** [comment]
We have common rules for this popups, but I'll change it directly.

**Comment by wout-codes** [comment]
None of them works I think. The current common rule doesn't work. They changed their code.

**Comment by wout-codes** [comment]
Try it yourself with AdGuard for Windows.

**Comment by zloyden** [comment]
I already checked it with our products.


> None of them works I think. The current common rule doesn't work. They changed their code.

I know that. I'll change the rules a bit.

**Comment by wout-codes** [comment]
What is wrong here?

**Pull request closed without merging**
