### PR TITLE
Add tracking domains used by Japanese TV stations

### PR DESCRIPTION
**Pull request by kou-kee**
### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [x] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

### Add your comment and screenshots

1. Your comment

Some official statements regarding this tracking (both in Japanese):
https://www.ytv.co.jp/privacy/experiments2022/index.html
https://www.tv-asahi.co.jp/tvdata/

The statements say that viewers are opted in for the analytics collecting watching durations, postal code, identifiers, and software information preinstalled on a TV and they may be shared with third parties.

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Comment by Alex-302** [comment]
Hi. I don't see requests to these domains.
Could you please export HARs with these requests and attach here as zip archive?

**Comment by kou-kee** [comment]
Hi, I’m sorry but currently I don’t have equipments to do that. I will close this pull request for now and reopen this in the future once I get everything ready.

**Comment by Yuki2718** [comment]
@kou-kee But how you found these domain? I don't see in the links. All we need is just some sort of evidence that they are actually in use, so screenshot(s) of logs of anything will be suffice.

**Comment by Yuki2718** [comment]
https://github.com/easylist/easylist/issues/14169

**Comment by kou-kee** [comment]
@Yuki2718 Thank you for the reply!
I found these domains being made from my smart TVs when I was monitoring all DNS queries made by my devices as I always do. 
As for the proof, I do have logs of the queries in my NextDNS account but I can inspect the packets if you could give me some days.

**Comment by kou-kee** [comment]
I have inspected the packets using Wireshark and I found that:
there is missing domain (beat.yourtv.jp), and all telemetries except one were sent in plaintext.

0A6EE658-7B29-46A6-993E-5CB5CF410AA7
54B3C4D6-EAF2-497F-A8D5-31D4208B7F3D

The underlined DNS queries are all telemetry made by my smart TV. I also have Wireshark log which can be sent directly to you upon request. I decided not to upload it here because it contains my TV’s identifies as well as postal code (although it’s fake).

**Comment by Yuki2718** [comment]
@Alex-302 I think that's enough.
cc: @ryanbr (for https://github.com/easylist/easylist/issues/14169)

**Comment by kou-kee** [comment]
Thank you!

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
