### PR TITLE
#71968 withukor.com

### PR DESCRIPTION
**Pull request by wout-codes**
#71968

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
This rule does not block ads on the website.

What do you think of my rules?
`withukor.com#%#//scriptlet('abort-current-inline-script', 'document.addEventListener', '/google_ad_client/')`

**Comment by wout-codes** [comment]
> 
> 
> This rule does not block ads on the website.
> 
> What do you think of my rules?
> `withukor.com#%#//scriptlet('abort-current-inline-script', 'document.addEventListener', '/google_ad_client/')`

He reported about Anti AdBlock Script. The rule I created worked perfectly.

**Comment by wout-codes** [comment]
@piquark6046 He reported about Anti AdBlock Script. The rule I created worked perfectly. So how about my rule?

**Comment by piquark6046** [comment]
> 
> 
> @piquark6046 He reported about Anti AdBlock Script. The rule I created worked perfectly. So how about my rule?

That rule written by me blocks Anti-Adblock Script.
If your rule is applied, it will modify something on the website that we don't have to block.

**Comment by wout-codes** [comment]
@piquark6046 I see. I will change to the suggested one created by you.

**Comment by wout-codes** [comment]
@piquark6046 is it okay now?

**Comment by piquark6046** [comment]
> 
> 
> @piquark6046 is it okay now?

It's OK.
But, it will be great if you add it into `EnglishFilter/sections/antiadblock.txt` like 5651aaccb5510dec39be2c2a1f7fb23350defdba and 532345f1c2905fccbbcd9459330c6202b890af45.

**Comment by wout-codes** [comment]
@piquark6046 should I also add in the Content Blocker txt?

**Comment by piquark6046** [comment]
> 
> 
> @piquark6046 should I also add in the Content Blocker txt?

If you want to add it into Content Blocker txt, i want to tell you what you add `@@||withukor.com^$generichide` into Content Blocker txt.

**Comment by wout-codes** [comment]
Two pull requests were created since I don't know how to merge all commits into one.

**Comment by piquark6046** [comment]
> 
> 
> Two pull requests were created since I don't know how to merge all commits into one.

If so, you can use [GitHub CLI](https://cli.github.com/). 
OR use [GitHub Desktop(GUI)](https://desktop.github.com/)

**Comment by wout-codes** [comment]
> 
> 
> > Two pull requests were created since I don't know how to merge all commits into one.
> 
> If so, you can use [GitHub CLI](https://cli.github.com/).
> OR use [GitHub Desktop(GUI)](https://desktop.github.com/)
> 
> If you want to push a commit signed with PGP, please ask me.

Thanks for the tip! 
Only for this case 2 Pull Requests were created.

**Comment by Yuki2718** [comment]
> Two pull requests were created since I don't know how to merge all commits into one.

No need to merge, any PR can includes whatever numbers of commits.

**Comment by wout-codes** [comment]
> 
> 
> > Two pull requests were created since I don't know how to merge all commits into one.
> 
> No need to merge, any PR can includes whatever numbers of commits. So please close one and leave the other by adding another commit.

What if I choose another file?

**Comment by Yuki2718** [comment]
> What if I choose another file?

No problem.

**Comment by wout-codes** [comment]
@Yuki2718 How am I supposed to do it?

**Comment by Yuki2718** [comment]
I don't know what environment you use, but if it's command line, checkout the branch you will keep, change an according file, commit as usual, then push the commit. No different from usual procedure. You don't need to open new PR, your push will automatically be added to the existing PR.

**Comment by Yuki2718** [comment]
Apparently on Firefox generichide is not enough (Firefox TPL turned off ofc) while works on Chrome. But as it's for Contents Blocker, needs to be tested on Safari or Samsung Browser.

**Comment by wout-codes** [comment]
> 
> 
> Apparently on Firefox generichide is not enough (Firefox TPL turned off ofc) while works on Chrome. But as it's for Contents Blocker, needs to be tested on Safari or Samsung Browser.
> [Update] okay, generichide works on Safari.

What id Firefox TPL? and ofc? I am currently using Firefox.

**Comment by Yuki2718** [comment]
> What is Firefox TPL? and ofc? I am currently using Firefox.

Sorry, TPL means Tracking Protection List built into Firefox and ofc is a slang meaning "Of course". Maybe something is wrong on my Firefox.

Can you add
`withukor.com##.kakao_ad_area`
to Korean section of foreign.txt in English filter and
`||daumcdn.net^*/ba.min.js` to specific.txt in Spyware filter?

**Comment by wout-codes** [comment]
I need to create another 2 more pull requests then. Guide me on how to make commits from different file into one PR.

**Comment by Yuki2718** [comment]
Sorry for my [poor explanation](https://github.com/AdguardTeam/AdguardFilters/pull/71970#issuecomment-757470440) (no ironic), but PR nor "git push" doesn't care how many files you changed. Checkout an according branch, change as many files as you like, then `git commit -am "your commit message"` and `git push origin yourbranch`, this is all needed. Only difference is now you don't need to open PR.

**Comment by wout-codes** [comment]
> 
> 
> Sorry for my [poor explanation](https://github.com/AdguardTeam/AdguardFilters/pull/71970#issuecomment-757470440) (no ironic), but PR nor "git push" doesn't care how many files you changed. Checkout an according branch, change as many files as you like, then `git commit -am "your commit message"` and `git push origin yourbranch`, this is all needed. Only difference is now you don't need to open PR.

Will this work in GitHub Web Version in Firefox?

**Comment by Yuki2718** [comment]
Just replided:
> I haven't used web interface so can't help if you use this.

@piquark6046 Do you know?

**Comment by wout-codes** [comment]
Github Desktop or CLI?

**Comment by Yuki2718** [comment]
I use Git for Windows.

**Comment by piquark6046** [comment]
> 
> 
> Just replided:
> 
> > I haven't used web interface so can't help if you use this.
> 
> @piquark6046 Do you know?

I heard only this: https://github.com/features/codespaces.

**Comment by piquark6046** [comment]
@wout-codes
I recommend GitHub Desktop if you can't use Console Line Interface like this:
Screensh1ot

**Comment by wout-codes** [comment]
I made a total of 4 Pull Requests.

**Comment by piquark6046** [comment]
> 
> 
> > What is Firefox TPL? and ofc? I am currently using Firefox.
> 
> Sorry, TPL means Tracking Protection List built into Firefox and ofc is a slang meaning "Of course". Maybe something is wrong on my Firefox.
> 
> Can you add
> `withukor.com##.kakao_ad_area`
> ~[Update] Sorry, maybe no need.~
> to Korean section of foreign.txt in English filter and
> `||daumcdn.net^*/ba.min.js` to specific.txt in Spyware filter?

Please give me original URL of `||daumcdn.net^*/ba.min.js`?

**Comment by Yuki2718** [comment]
@piquark6046 `http://t1.daumcdn.net/kas/static/ba.min.js` you can find in the source.

**Comment by wout-codes** [comment]
> http://t1.daumcdn.net/kas/static/ba.min.js

Yes, this is definitely a tracker.

**Comment by wout-codes** [comment]
I created a total of 4 pull requests now? Is it okay @piquark6046 @Yuki2718 ?

**Comment by piquark6046** [comment]
> 
> 
> I created a total of 4 pull requests now? Is it okay @piquark6046 @Yuki2718 ?

Hmm... i am OK, but I don't know what AdGuard maintainer think of that.

**Comment by Yuki2718** [comment]
> 
> Yes, this is definitely a tracker.

Not in pure sense tho.

**Comment by piquark6046** [comment]
> 
> 
> @piquark6046 `http://t1.daumcdn.net/kas/static/ba.min.js` you can find in the source.

Okay.

**Comment by wout-codes** [comment]
> 
> 
> > Yes, this is definitely a tracker.
> 
> Not in pure sense tho.

Yes.

> 
> 
> > I created a total of 4 pull requests now? Is it okay @piquark6046 @Yuki2718 ?
> 
> Hmm... I am OK, but I don't know what AdGuard maintainer think of that.

Haha. I do not use the Desktop version.

**Pull request closed without merging**
