### PR TITLE
altyazi.net

### PR DESCRIPTION
**Pull request by gork7777**
issue: #88573

### CODE REVIEW

**Comment by Sergey-Lyapin** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/559c039f75970fa2393b1883142c1f7214c249f0
I've replaced the old rule

**Comment by gork7777** [comment]
@Sergey-Lyapin sorry for ping, is there any problem creating pull request about submitted issues? Because a Turk insults me and my friend(he just opens new report not open PR) when I make a pull request in his reports.

**Comment by Sergey-Lyapin** [comment]
@gork7777 No problem, feel free to make new pull requests, we review all PRs and bad rules don't make it into the filters.
Btw please be more attentive and check few pages for ads and annoyances.

**Comment by gork7777** [comment]
@Sergey-Lyapin Okay, what can be done for the one who insults me? You can find it in the comments on these reports: 1. https://github.com/AdguardTeam/AdguardFilters/issues/86583 2. https://github.com/AdguardTeam/AdguardFilters/issues/88585

**Comment by baronexy** [comment]
Yes, he is a toxic user and does not accept help.

**Pull request merged**
