### PR TITLE
fix damoh video ads on familie.de

### PR DESCRIPTION
**Pull request by JobcenterTycoon**
### Please include a summary of the change and which issue is fixed.

fixed video ads on `https://www.familie.de/familienleben/gesellschaft/video-luis-die-aliens/`

---

##### To avoid invalid pull requests, please check and confirm following checkboxes:

  - [x] This is not an ad/bug report;
  - [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
  - [x] I have performed a self-review of my own changes;
  - [x] My changes do not break web sites, apps and files structure.

##### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

  - [x] Missed ads or ad leftovers;
  - [ ] Website or app doesn't work properly;
  - [ ] AdGuard gets detected on a website;
  - [ ] Missed analytics or tracker;
  - [ ] Social media buttons — share, like, tweet, etc;
  - [ ] Annoyances — pop-ups, cookie warnings, etc;
  - [ ] Filters maintenance.

##### Enter the issue address:

no issue in the issue tracker

##### If possible, a screenshot of a page or application should not be cropped too much. Otherwise, it is not always clear where the element is located.

see https://github.com/uBlockOrigin/uAssets/issues/6541

### Terms

  - [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met.

### CODE REVIEW

**Review by zloyden — APPROVED** [review]

**Review by zloyden — COMMENTED** [review]
@JobcenterTycoon I guess you only need to redirect `XHR` request, is that right?

**Comment by JobcenterTycoon** [comment]
@zloyden no it doesn’t work on all sites like on `giga.de` or `vip.de`

**Comment by zloyden** [comment]
I got it, but I meant the current rule with slide changes such as
```
||damoh.*.de^$xmlhttprequest,redirect=nooptext,domain=stern.de|desired.de|pcgames.de|t-online.de|vox.de|spieletipps.de|wetter.de|golem.de|autobild.de|buffed.de|gamesaktuell.de|kino.de|pcgameshardware.de|videogameszone.de|familie.de
```

**Comment by JobcenterTycoon** [comment]
Yes.

But im wondering about `!+ NOT_PLATFORM(windows, mac, android, ext_ff)` why is firefox excluded?

**Comment by zloyden** [comment]
It may have been necessary for the old extension, but now it works fine on Firefox and the rule does not need for apps - removed this limitation.
@BlazDT please also check this, I see that you added the rule in the past.

**Comment by BlazDT** [comment]
Replace rule was not applied when it was blocked.

**Pull request merged**
