### PR TITLE
fix #70577 fishingsib.ru

### LINKED ISSUE #70577: fishingsib.ru
### Issue URL (Ads)
 [https://www.fishingsib.ru/video/view/141061/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.fishingsib.ru%2Fvideo%2Fview%2F141061%2F)
### Comment
Username: @spok1
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.25
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Remove X-Client-Data header from HTTP requests, <br/>Strip URLs from tracking parameters, <br/>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> AdGuard Experimental<br/><br/><b>Language-specific:</b><br/> AdGuard Russian

### PR DESCRIPTION
**Pull request by gork7777**
#70577

### CODE REVIEW

**Comment by Yuki2718** [comment]
Just a tip - unlike EasyList, AdGuard prefers to add a new rule on top of each section. In other words they're not sorted alphabetically, at least on each specific.txt - other files may have other order rule tho.

**Comment by zloyden** [comment]
Additional changes are needed here. I will do it directly, thanks for your participating:)

**Comment by Yuki2718** [comment]
Yeah, please don't feel bad - we always welcome new contributor.

**Comment by gork7777** [comment]
I wanna ask something. (fishingsib.ru #70577) how can you make this pressable link? I tried but it looks like this (AdguardTeam#70577 fishingsib.ru)

**Comment by Yuki2718** [comment]
@gork7777 I'm not sure if I got what you mean and why you want that, but if you want to make a clickable link with arbitrary text make it like this:
`[text](url)`
For example, [fishingsib.ru #70577](https://github.com/AdguardTeam/AdguardFilters/issues/70577)

**Comment by gork7777** [comment]
I asking that: Like zloyden did here https://github.com/AdguardTeam/AdguardFilters/issues/70577
(fishingsib.ru #70577)

**Comment by zloyden** [comment]
Do you mean the title of the commit? Just `fishingsib.ru #70577`, but for the pull requests we use `fix #70577 fishingsib.ru`

**Pull request closed without merging**
