### PR TITLE
fix #55632 asahi.com

### LINKED ISSUE #55632: asahi.com
### Issue URL (Annoyance)
 [https://www.asahi.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.asahi.com%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.4 RC 2
Browser: | Firefox
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Block third-party Authorization header, Self-destructing third-party cookies (180), Disable cache for third-party requests, Block Push API, Block Location API, Hide your IP address (209.141.53.254)
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> EasyList China, <br/>AdGuard Japanese
Other extensions used: | Norton ,adblock

### PR DESCRIPTION
**Pull request by Yuki2718**
https://github.com/AdguardTeam/AdguardFilters/issues/55632

### CODE REVIEW

**Review by Sergey-Lyapin — COMMENTED** [review]
I can't reproduce it

**Comment by zloyden** [comment]
Not reproduced on my end even with Japanese IP.
@Yuki2718 could you please share a screenshot with issue from your end and Filter log with blocked request `asahi.com/brave/`?

**Comment by Yuki2718** [comment]
@zloyden Now I can't reproduce neither. I guess they removed the anti-adblock because this very issue brought severe criticism yesterday on Japanese Internet society. You can close the issue and PR, I'll notify you if I see the anti-adblock again.

**Comment by zloyden** [comment]
Ok, thanks:)

**Pull request closed without merging**
