### PR TITLE
dizimax.plus

### PR DESCRIPTION
**Pull request by gork7777**
### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [x] Annoyances — pop-ups, cookie warnings, etc;
- [x] Filters maintenance.

### Enter the issue address
https://github.com/AdguardTeam/AdguardFilters/issues/124014

### Add your comment and screenshots

1. Your comment

I know a pull request has been opened for this issue, here: https://github.com/AdguardTeam/AdguardFilters/pull/124015
But the rules in this pull request don't work for this new domain because such rules don't exist on the website. So I deleted the old rules and just blocked the modal popup (Annoyances)

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Comment by Alex-302** [comment]
Which new domain?

**Comment by gork7777** [comment]
@Alex-302 `dizimax.plus` is new domain, and I explained in the comments section this PR.

**Comment by Alex-302** [comment]
Better do not make a lot of `*` TLDs. `.plus` is not working in Safari, for example.

**Comment by gork7777** [comment]
@Alex-302 I mean, in the other pull request the obsolete rules are not available in the new domain. In the new domain, there are just these rules available:
`#$#body { overflow: visible !important; padding-right: 0 !important; }`
`#$#.swal2-container { display: none !important; }`

Obsolete rules shouldn't be removed?

**Comment by Alex-302** [comment]
Ok, but please change `.*` to `.plus` (at least for the first time)

**Comment by gork7777** [comment]
Done.

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
