### PR TITLE
obsolete filter part 2

### PR DESCRIPTION
**Pull request by JobcenterTycoon**
Same as: https://github.com/AdguardTeam/AdguardFilters/pull/117492

### CODE REVIEW

**Comment by Alex-302** [comment]
It is really not the best idea to remove URL blocking rules with dead domains.
Example:
tracking domain `vgs-collect-keeper.apps.verygood.systems` 
it can be blocked by `||verygood.systems^` or `||apps.verygood.systems^`
In this case DNS checker will report about dead domain - not resolved by DNS. But `vgs-collect-keeper.apps.verygood.systems` - working, and tracking will be unblocked after removing "obsolete" rule.

**Comment by JobcenterTycoon** [comment]
It does not, it checks if the domain is really avaiable (to rent)

**Comment by Alex-302** [comment]
What site do you use for checking?

**Comment by JobcenterTycoon** [comment]
`https://www.eurodns.com/de/bulk-search` exacly the same as https://github.com/AdguardTeam/AdguardFilters/pull/117492

**Comment by Alex-302** [comment]
I don't trust to this service. Need time to check.

**Review by zloyden — APPROVED** [review]

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
