### PR TITLE
Tracker: KakaoPixel API

### PR DESCRIPTION
**Pull request by piquark6046**
#### To avoid invalid pull requests, please check and confirm following terms

- [X] This is not an ad/bug report;
- [X] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [X] I have performed a self-review of my own changes;
- [X] My changes do not break web sites, apps and files structure.

#### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [X] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

#### Enter the issue address

 - https://kakaoad.github.io/kakao-pixel/send-add-to-cart-event.html
 - https://kakaobusiness.gitbook.io/main/tool/pixel-sdk/and#2-2-sdk
 - https://kakaobusiness.gitbook.io/main/tool/pixel-sdk/and

### Add your comment and screenshots

This is a SDK of tracking feature operated by Kakao Corp.
It should be blocked.

### Terms

- [X] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Comment by Yuki2718** [comment]
Is this really used everywhere? Generic scriptlet injection should be avoided if possible.

**Comment by seia-soto** [comment]
> Is this really used everywhere? Generic scriptlet injection should be avoided if possible. `t1.daumcdn.net/adfit/static/kp.js` in your link is blocked by EL rule `/adfit/*` (e.g. `www.cafe24.com`) and it seems as far as it's blocked scriptlet is not needed.

Kakao Crop is operating a messenger and monopolist in Korea. In one word, every one is using Kakao's messenger, Kakao Talk. Extending their feature, Kakao oAuth and things are used everywhere in Korea.

For Koreans, it's reasonable to block it. Since Kakao is monopolist, there are many marketing companies and firms applying their pixel api too.

**Comment by seia-soto** [comment]
If it already blocked, it's not required at all time due to performance reason.

**Review by Yuki2718 — CHANGES_REQUESTED** [review]
Add missed analytics `||teralog.techhub.co.kr^` at `m.card-gorilla.com`.

**Review by zloyden — APPROVED** [review]

**Review by Yuki2718 — APPROVED** [review]

**Pull request merged**
