### PR TITLE
fix #37480 nerodiskrasivoitv.ru

### LINKED ISSUE #37480: nerodiskrasivoitv.ru
### Issue URL (Ads)
[http://www.nerodiskrasivoitv.ru/online/nrk_online_121-140.php](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwww.nerodiskrasivoitv.ru%2Fonline%2Fnrk_online_121-140.php)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>
<details>
  <summary>Screenshot 2</summary>

  Screenshot 2
</details>

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 3.2.1
Browser: | Chrome
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (2880), Block WebRTC, Hide your Referrer from third-parties
Filters: | AdGuard Russian,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media,<br>AdGuard Spanish/Portuguese
Other extensions used: | Нету

### PR DESCRIPTION
**Pull request by tvinzz**
https://github.com/AdguardTeam/AdguardFilters/issues/37480

### CODE REVIEW

**Review by Alex-302 — CHANGES_REQUESTED** [review]
search for `window.RESOURCE` in the filters

**Comment by tvinzz** [comment]
@Alex-302,
added domain to existing rule.

**Comment by Alex-302** [comment]
block ad server

**Comment by tvinzz** [comment]
blocked mobile ad server

**Comment by tvinzz** [comment]
added `milliardytv.ru` to adservers

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
