### PR TITLE
Fix for www.postronienatury.pl #177409

### LINKED ISSUE #177409: www.postronienatury.pl
### Issue URL (Annoyance)
 [https://www.postronienatury.pl/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.postronienatury.pl%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | Value
--- | ---
AdGuard product: | AdGuard Browser Extension v4.3.46
Browser: | Chrome
Stealth mode: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking, <br/>Legitimate URL Shortener<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media, <br/>Fanboy's Social Blocking List<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/>Online Malicious URL Blocklist<br/><br/><b>Language-specific:</b><br/>Official Polish filters for AdBlock, uBlock Origin & AdGuard, <br/>Polish Social Filters, <br/>KAD - Anti-Scam, <br/>Polish Annoyances Filters, <br/>Polish Anti Adblock Filters

### PR DESCRIPTION
**Pull request by Deneno**
Fix [177409](https://github.com/AdguardTeam/AdguardFilters/issues/177409)

### CODE REVIEW

**Comment by Sergey-Lyapin** [comment]
This site has no traffic, so there's no point in adding rules for it.

**Comment by Deneno** [comment]
@Sergey-Lyapin Am I closing the poolquest?
what should I write in the issue?

**Comment by Sergey-Lyapin** [comment]
@Deneno
Yes, just close it.
And close the issue with the comment: 
```
This site has too little traffic. Please add to user rules: postronienatury.pl##div[class^="TheCookieBar"]
```

**Comment by Sergey-Lyapin** [comment]
@Deneno 
Хотя можем домен добавить к этому правилу
`ekosystem.wroc.pl,ton.eu##div[class*="cookie-bar"]`

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
