### PR TITLE
Fix arca.live

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/AdguardTeam/AdguardFilters/issues/82466

### CODE REVIEW

**Comment by Sergey-Lyapin** [comment]
not reproduced

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/82500#issuecomment-834225404

Please enable `Hide your Referrer form third-parties` and set the value to the one of 3rd services.

scree12
scre1

**Comment by stanislav-atr** [comment]
https://arca.live/b/live/25840366?p=1
Images load correctly on my side with korean VPN and `Hide referrer`.

**Comment by piquark6046** [comment]
Screenshot
The images are not loaded correctly on my side with Google Chrome.

**Review by zloyden — APPROVED** [review]

**Comment by piquark6046** [comment]
PS.I reproduced it with non-Korean IP.

**Pull request merged**
