### PR TITLE
Trackers: sportsworldi.com

### PR DESCRIPTION
**Pull request by ghost**
### URL: `https://www.sportsworldi.com/newsView/20210110505218`

Screenshot:
Screenshot

### Network Logs
network1

### Code
`https://img.sportsworldi.com/static/w_sportsworld/common/js/analytics.js`

### CODE REVIEW

**Review by wout-codes — APPROVED** [review]

**Comment by Alex-302** [comment]
Cannot reproduce. Please upload HAR.

**Comment by piquark6046** [comment]
@Alex-302 
Please delete this comment, if you download the HAR file.
[HAR_wcyr93fxaoe99i8ivd535wq5.zip](https://github.com/AdguardTeam/AdguardFilters/files/5796035/HAR_wcyr93fxaoe99i8ivd535wq5.zip)

**Comment by piquark6046** [comment]
Please give me your email address...

**Comment by Alex-302** [comment]
@piquark6046 filters@adguard.com

**Comment by piquark6046** [comment]
> @piquark6046 filters@adguard.com

Sent. please check it out.

**Comment by Alex-302** [comment]
I need HAR of the page, not one record only.

**Comment by piquark6046** [comment]
> I need HAR of the page, not one record only.

oh, i will resend to you.

**Comment by Alex-302** [comment]
Thanks, added.

**Pull request closed without merging**
