### PR TITLE
www.instiz.net - Annoyances 

### PR DESCRIPTION
**Pull request by green1052**
URL: https://www.instiz.net/pt/7138479

IMAGE: 
image

### CODE REVIEW

**Review by piquark6046 — CHANGES_REQUESTED** [review]
It seems that an extended CSS injection rule does not required.

**Review by green1052 — COMMENTED** [review]
fix

**Comment by Alex-302** [comment]
I see no difference. What the purpose of the rule?
(btw. `www` usually not required)

**Comment by green1052** [comment]
its remove water mark

before:
image

after:
image

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
