### PR TITLE
gemius.pl

### PR DESCRIPTION
**Pull request by cronlabspl**

### CODE REVIEW

**Comment by Alex-302** [comment]
We already have the necessary rules.
Where is it missed?

**Comment by cronlabspl** [comment]
> We already have the necessary rules.
> Where is it missed?

Everywhere. Gemius is malicious crap ( tracking shit ) and should be avoided at all cost

**Comment by chirag127** [comment]
> > We already have the necessary rules.
> > Where is it missed?
> 
> Everywhere. Gemius is malicious crap ( tracking shit ) and should be avoided at all cost

http://www.gemius.pl/reklamodawcy-aktualnosci/najwiecej-wydaja-na-obuwie-placa-szybkim-przelewem.html seems like a good site to me and most uppermost it have millions of monthly user how can we block it completely.

**Comment by chirag127** [comment]
> > > We already have the necessary rules.
> > > Where is it missed?
> > 
> > 
> > Everywhere. Gemius is malicious crap ( tracking shit ) and should be avoided at all cost
> 
> http://www.gemius.pl/reklamodawcy-aktualnosci/najwiecej-wydaja-na-obuwie-placa-szybkim-przelewem.html seems like a good site to me and most uppermost it have millions of monthly user how can we block it completely.

I don't know why @Alex-302 even entertained this pull request.

**Comment by urvbcn88** [comment]
> > We already have the necessary rules.
> > Where is it missed?
> 
> Everywhere. Gemius is malicious crap ( tracking shit ) and should be avoided at all cost

There are already general rules for `Gemius`

https://github.com/AdguardTeam/AdguardFilters/blob/8dbda532a1fb99b044654d7ec5326737de9b6ac6/SpywareFilter/sections/general_url.txt#L237
https://github.com/AdguardTeam/AdguardFilters/blob/8dbda532a1fb99b044654d7ec5326737de9b6ac6/SpywareFilter/sections/general_url.txt#L238
https://github.com/AdguardTeam/AdguardFilters/blob/8dbda532a1fb99b044654d7ec5326737de9b6ac6/SpywareFilter/sections/general_url.txt#L308
https://github.com/AdguardTeam/AdguardFilters/blob/8dbda532a1fb99b044654d7ec5326737de9b6ac6/SpywareFilter/sections/tracking_servers.txt#L1980

**Comment by Alex-302** [comment]
> Gemius is malicious crap

I agree, but our filter shoud not break the sites(exclusions, which you want to delete).

**Pull request closed without merging**
