### PR TITLE
fix #77430 manhuascan.com

### LINKED ISSUE #77430: manhuascan.com
### Issue URL (Annoyance)
 [https://manhuascan.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fmanhuascan.com%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>
<details>
  <summary>Screenshot 2</summary>

  Screenshot 2
</details>
<details>
  <summary>Screenshot 3</summary>

  Screenshot 3
</details>
<details>
  <summary>Screenshot 4</summary>

  Screenshot 4
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.31
Browser: | Firefox
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion
Other extensions used: | mcafee

### PR DESCRIPTION
**Pull request by wout-codes**
#77430

### CODE REVIEW

**Review by Yuki2718 — APPROVED** [review]

**Comment by Yuki2718** [comment]
@wout-codes another crap script: `||manhuascan.com^*/popads.js`.

**Review by zloyden — APPROVED** [review]

**Comment by zloyden** [comment]
> @wout-codes another crap script: `||manhuascan.com^*/popads.js`.

I'll add it.

**Comment by wout-codes** [comment]
@Yuki2718 @zloyden I am currently working a quite big project in my company, so I am a lot busy. Make the changes for me if you are okay (:

**Comment by Yuki2718** [comment]
@wout-codes Fingers crossed ;)

**Comment by wout-codes** [comment]
> Fingers crossed

Thanks.

**Pull request merged**
