### PR TITLE
fix #75679 myflixerhd.ru

### LINKED ISSUE #75679: myflixerhd.ru
### Issue URL (Ads)
 [https://www.myflixerhd.ru/watch-tv/the-ripper-66491.3989606](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.myflixerhd.ru%2Fwatch-tv%2Fthe-ripper-66491.3989606)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.5.2.946 nightly
Browser: | Safari
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Adblock Warning Removal List<br/><br/><b>Language-specific:</b><br/> AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Dutch, <br/>AdGuard Spanish/Portuguese, <br/>AdGuard French, <br/>AdGuard Chinese, <br/>Bulgarian list, <br/>EasyList Czech and Slovak, <br/>AdBlockID, <br/>Official Polish filters for AdBlock, uBlock Origin & AdGuard
Other extensions used: | ABP for Mac

### PR DESCRIPTION
**Pull request by wout-codes**
#75679

### CODE REVIEW

**Comment by Sergey-Lyapin** [comment]
I can't reproduce new-tab popups, but I see the request to this domain which looks like adserver

**Comment by wout-codes** [comment]
> I can't reproduce new-tab popups, but I see the request to this domain which looks like adserver

Use AdGuard for Mac or Windows.

**Comment by Sergey-Lyapin** [comment]
I've checked in Safari with AG for Mac too

**Comment by wout-codes** [comment]
> I've checked in Safari with AG for Mac too

I get popups even with the extension. Maybe you are not getting because of IP.

**Pull request merged**
