### PR TITLE
The third large cleanup of Base

### PR DESCRIPTION
**Pull request by Yuki2718**
If test URL of dead domain is identical to the domain, it means no subdomain found - but at least URL in the original Issue report was checked if available, i.e. no such request anymore.
```
! ---------- In EL
||adcalm.com^$third-party
||adxoo.com^$third-party
||boyaidare.club^
||capsfogpeck.com^
||clearadnetwork.com^
||doufoacu.net^
||faigroas.net^
||mimilcnf.pro^
||noproblfr.com^
||ponchowafesargb.com^$third-party
||tubecorporate.com^$third-party
||velocitycdn.com^$third-party
||visariomedia.com^
||yieldlove.com^$third-party

||d13k7prax1yi04.cloudfront.net^
||d36zfztxfflmqo.cloudfront.net^
||tm-offers.gamingadult.com^

||bdsmstreak.com/fr37.js
msn.com##.ad
! as generic ##.block-fusion-ads
newsweek.com##.block-fusion-ads


! ---------- Dead domains
! https://joq.al/artikull/543266.html
joq.al

! http://talkshowyoutube.blogspot.com/2013/06/21-6-2013_5342.html
talkshowyoutube.blogspot.com

! http://satal.az/addnews.html
satal.az

! https://www.kenquru.az/lists?page=37
kenquru.az

! http://www.biznesinfo.az/company/card78410/params/ln/ru
biznesinfo.az

! https://mp3.sun.az/index.php?sid=6847
mp3.sun.az

! http://film.joy.az/crime/6211-uaq-srcs.html
film.joy.az

! http://skrom.net/2017/08/11/h%C9%99kim-s%C9%99hl%C9%99nkarligi-dunyaya-g%C9%99l%C9%99c%C9%99k-korp%C9%99nin-h%C9%99yatina-son-qoydu/
skrom.net

! http://topxeber.az/2017/06/17/bakinin-m%C9%99rk%C9%99zin%C9%99-giris-baglandi/
topxeber.az

! http://surf.az/site/surf_news/33275
surf.az

! http://www.ailem.az/read/12945
ailem.az

! https://placeholdit.imgix.net/~text?w=16&h=9&txtpad=0
placeholdit.imgix.net

! http://goldnews.az/az/news/51aa586d-d643-4c3a-900c-5790289abaa8/ilham-liyev-mullimlrin-mkhaqq-il-bagl-srncam-verdi/read/
goldnews.az

! http://mail.minion.az/xeberler/2257-yeni-energetika-naziri-aciqlama-verdi.html
minion.az

! http://politico.az/xeber/16099
politico.az

! http://media24.az/news/25742
media24.az

! saygac.az
saygac.az

! http://ceeb.mobi/loads/
ceeb.mobi

! http://skyline.az/az/
skyline.az

! http://mp3.ses.az/bi1rxhMP2HY/mp3-indir/basqalasirsan.html
mp3.ses.az

! http://m.52qumao.com/zixun/54320287.html
m.52qumao.com

! https://m.81new.com/95/95885/32202537.html
m.81new.com

! m652a.cn
m652a.cn

! m.805zx.cn/uu.php?
m.805zx.cn

! bbs.alxx520.com
bbs.alxx520.com

! jx.yy6080.info
jx.yy6080.info

! pic.qlp9.cn
pic.qlp9.cn

! https://sese-777.com/vodplayhtml/1518.html?1518-1-1
sese-777.com

! https://www.dashishipin.com/vodplay/391237-1-1/
dashishipin.com

! http://www.lsj2017.com/
lsj2017.com

! atoncengreige.com
atoncengreige.com

! stp.qiansi.pw
stp.qiansi.pw

! photo.52nvyou.cn
photo.52nvyou.cn

! https://bt.cosxcos.xyz/
bt.cosxcos.xyz

! https://qing.gq/search.html
qing.gq

! js.meitulu.com
js.meitulu.com

! m.fbaix.com
m.fbaix.com

! https://www.av78.vip/?7dsw
av78.vip


! ---------- Redundant
fcine.net#@#.adsbygoogle

hdblog.it#@#.ads_block

! arabseed.net##center > a[rel="nofollow"] > img
arabseed.net##center > a[href][rel="nofollow"] > img

! fins.az##.banner
turizm.fins.az##.banner

! big.az##a[href="http://unvan.az"]
mp3.big.az##body > a[href="http://unvan.az"][target="_blank"]

! 139.99.120.222##.navbar-brand
139.99.120.222##.navbar-brand#fbawah

! m.comic.naver.com##body > div#ly_dim
m.comic.naver.com##body > div#ly_dim > div.bg

! vg.no##.ad
vg.no##.appnexus.ad

! filmweb.pl#@#.ws__wrapper
www.filmweb.pl#@#.ws__wrapper

! elektroda.pl##a[href^="https://jlcpcb.com/"] > img
elektroda.pl##.widgets a[href^="https://jlcpcb.com/"] > img

! @@||apitvh.net/embed/*ads_code_*.js
@@||apitvh.net/embed/ads_code_1.js$domain=apitvh.net

! ||bp.blogspot.com^$image,domain=movie303.com|nontonmovie33.net
||bp.blogspot.com^$image,domain=nontonmovie33.net

! @@||googletagservices.com/tag/js/gpt.js$domain=wp.pl|dobreprogramy.pl|o2.pl|pudelek.pl|so-magazyn.pl
!+ NOT_PLATFORM(windows, mac, android)
@@||googletagservices.com/tag/js/gpt.js$domain=pilot.wp.pl

! ||alio.lt^$domain=delfi.lt
||alio.lt/info*.html$domain=delfi.lt
```

### CODE REVIEW

**Comment by Yuki2718** [comment]
Also please check these, didn't include PR to avoid conflicts:
```
! ---------- Obsolete

manga1000.com#%#//scriptlet('abort-current-inline-script', '$', 'disableadblock')
waaw.to#%#//scriptlet("set-constant", "adBlockDetected", "noopFunc")

9tsu.net#%#//scriptlet("abort-current-inline-script", "String.fromCharCode", "delete window")
egyanime.com$$script[tag-content="zfgloaded"][min-length="30000"][max-length="80000"]
egyanime.com#%#//scriptlet("abort-on-property-read", "zfgformats")
imhentai.com#%#//scriptlet("abort-on-property-read", "z7OO")
pussyspace.com#%#//scriptlet("abort-current-inline-script", "document.cookie", "popMagic")
waaw.to#%#//scriptlet("abort-on-property-read", "BetterJsPop")
yaoimangaonline.com$$script[tag-content="zfgloaded"][min-length="30000"][max-length="80000"]
yaoimangaonline.com#%#//scriptlet("abort-current-inline-script", "String.fromCharCode", "zfgloaded")
```

**Review by Alex-302 — APPROVED** [review]

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/70150#issuecomment-746528498 removed them from our filters, thanks.

**Comment by Yuki2718** [comment]
Thx too!

**Comment by AdamWr** [comment]
It seems that the rules for `waaw.to` are still needed - https://github.com/AdguardTeam/AdguardFilters/issues/69884#issuecomment-747644318
I re-added them.

**Comment by zloyden** [comment]
Hm, it worked fine on my end when I had checked the website without those rules. Thanks @AdamWr

**Comment by Yuki2718** [comment]
Hmm...I can reproduce that grey warning only if I disabled `waaw.to#%#//scriptlet("abort-on-property-read", "BetterJsPop")`. Even then `waaw.to#%#//scriptlet("set-constant", "adBlockDetected", "noopFunc")` doesn't help. Weird.
(Sure BetterJsPop is there - it appears only if query parameters are appended to URL, which I missed. Thx @zloyden for not removing it!)

**Comment by AdamWr** [comment]
>Hmm...I can reproduce that grey warning only if I disabled waaw.to#%#//scriptlet("abort-on-property-read", "BetterJsPop"). Even then waaw.to#%#//scriptlet("set-constant", "adBlockDetected", "noopFunc") doesn't help. Weird.

I know that `adBlockDetected` doesn't work in this case and `BetterJsPop` is enough, but as I recall, there was also a different adblock detection which does't present on all videos, so I re-added both rules just in case.

**Comment by Yuki2718** [comment]
Okay, thanks for clarification!

**Pull request merged**
