### PR TITLE
Social: m.comic.naver.com

### PR DESCRIPTION
**Pull request by ghost**
### URLs
https://m.comic.naver.com/webtoon/detail?titleId=734574&no=3&week=mon&listSortOrder=DESC&listPage=1#nafullscreen
https://m.comic.naver.com/webtoon/detail?titleId=758662&no=31

### Screenshots
scre2
scre445

### CODE REVIEW

**Comment by piquark6046** [comment]
#89838 `cc.naver.com` Tracker.

**Review by zloyden — APPROVED** [review]

**Comment by Apious** [comment]
blocked as do under below

||app.link^
||ssl.pstatic.net/static/m/comic/im/app_banner_list.jpg
m.comic.naver.com$@$div[id="ppl_default_section"]
m.comic.naver.com##.cont_app_banner
@@||ssl.pstatic.net^$domain=m.comic.naver.com

**Comment by piquark6046** [comment]
> blocked as do under below
> 
> ||app.link^
> ||ssl.pstatic.net/static/m/comic/im/app_banner_list.jpg
> m.comic.naver.com$@$div[id="ppl_default_section"]
> m.comic.naver.com##.cont_app_banner
> @@||ssl.pstatic.net^$domain=m.comic.naver.com
> 
> it's on my list
> https://github.com/Apious/Ads_Filter_Contents/blob/1st/Ads_Filter_Contents.txt
> https://github.com/Apious/Ads_Filter_DNS/blob/1st/Ads_Filter_DNS.txt

What do you mean?

**Comment by Apious** [comment]
> [#91449 (comment)](https://github.com/AdguardTeam/AdguardFilters/pull/91449#issuecomment-906188349)
> 
> What is `@@||ssl.pstatic.net^$domain=m.comic.naver.com` rule?

  - pstatic.net is image server. so not blocked when m.comic.naver.com opened

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/91449#issuecomment-908127246
My meaning is that `ssl.pstatic.net/static/m/comic/im/app_banner_list.jpg` is only used on mobile environment.
But, Why do you unblock the entire of transferred data from `ssl.pstatic.net` if a visitor visits mobile version of [Naver Webtoon](https://comic.naver.com).

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/91449#issuecomment-905281598
And, Why do you unblock the embedded marketing on [Naver Webtoon](https://comic.naver.com)?

https://shared-comic.pstatic.net/fileShare/Webtoon_guide_ver2.9.10.pdf
https://displayad.naver.com/info/guide

**Comment by Apious** [comment]
> [#91449 (comment)](https://github.com/AdguardTeam/AdguardFilters/pull/91449#issuecomment-908127246)
> I am sorry for misunderstanding.
> My meaning is that `ssl.pstatic.net/static/m/comic/im/app_banner_list.jpg` is only used on mobile environment.
> But, Why do you unblock the entire of transferred data from `ssl.pstatic.net` if a visitor visits mobile version of [Naver Webtoon](https://comic.naver.com).

playing here on working time to late :)
Explain to SSL.PSTATIC.NET

1. this is image server. but naver company uploaded ads image also / Result = image server and sometimes upload ads images
2. blocked naver domain of category with unblock another page / block only this image with not block toon images

*Adguard not blocked frame. so image or contents only block 1st. and then unblock page domain

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/91449#issuecomment-909718205

Okay. Then, Why didn't you write your rule like `@@||ssl.pstatic.net/<something>`?

**Comment by Apious** [comment]
as i wrote
1. Adguard isn't blocked of content frame.
2. Block Contents 1st.
3. Unblock Image Server with that Pages

so @@||ssl.pstatic.net^$domain=m.comic.naver.com meaning...
- Blocked Images or Ads Images but Not Blocked domain
- if not used it then not show the images(toons, Comics images)

**Comment by Apious** [comment]
> [#91449 (comment)](https://github.com/AdguardTeam/AdguardFilters/pull/91449#issuecomment-909718205)
> 
> Okay. Then, Why didn't you write your rule like `@@||ssl.pstatic.net/<something>`?

as i wrote

Adguard isn't blocked of content frame.
Block Contents 1st.
Unblock Image Server with that Pages
so @@||ssl.pstatic.net^$domain=m.comic.naver.com meaning...

Blocked Images or Ads Images but Not Blocked domain
if not used it then not show the images(toons, Comics images)

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/91449#issuecomment-909876637

I cannot understand your comment.
Please open a pull request to avoid changing to off-topic.

**Pull request merged**
