### PR TITLE
Fix #175860 nungde.com

### LINKED ISSUE #175860: nungde.com
### Issue URL (Ads)
 [https://nungde.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fnungde.com%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | Value
--- | ---
AdGuard product: | AdGuard for Mac v2.14.0.1568 nightly
Browser: | Edge
License type: | paid
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>EasyPrivacy<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard German, <br/>EasyList Thailand
Userscripts: | disabled
Referrer: | [https://nungde.com/movies/strange-tales-of-a-lonely-studio/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fnungde.com%2Fmovies%2Fstrange-tales-of-a-lonely-studio%2F)

### PR DESCRIPTION
**Pull request by SpicySpaceman**
# Creating the pull request

> Please include a summary of the change and which issue is fixed\
> If the related issue does not exist in our repository, please create it before making pull request\
> It is highly recommended to use our [Web Reporting Tool](https://kb.adguard.com/technical-support/reporting-tool) instead of creating an issue on GitHub directly\
> Please note, that we verify every pull request manually, so it may take time to apply it

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [x] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

### Enter the issue address

Fixes #175860

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Comment by piquark6046** [comment]
@danidoedel I think that contributing to [EasyList thailand](https://github.com/easylist-thailand/easylist-thailand) is better.
The filter is a regional filter for Thai websites.

**Comment by danidoedel** [comment]
@piquark6046 what's the purpose of the Thai section in the foreign filter then? ;) Also I am not sure how well maintained that EasyList filter is with one commit every 6 moths and unsolved issues which have been open for almost a year. I don't really want to wait for a year until a website gets fixed :D

**Comment by piquark6046** [comment]
Fixed by https://github.com/easylist-thailand/easylist-thailand/commit/760bbc0f0bf5b2bb9904f9e4c67a0633cb4972e8.

**Comment by danidoedel** [comment]
@piquark6046 that doesn't answer my question though :)

**Pull request closed without merging**
