### PR TITLE
fix #71138

### LINKED ISSUE #71138: smallseotools.com
### Issue URL (Ads)
 [https://smallseotools.com/alexa-ranking/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fsmallseotools.com%2Falexa-ranking%2F)
### Comment
Username: @RealJohnBaker
> Keep seeing grammarly ads here, even with new firefox profile. Testing with uBlock Origin the ads are blocked.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.31
Browser: | Firefox
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Security:</b><br/> NoCoin Filter List<br/><br/><b>Language-specific:</b><br/> RU AdList

### PR DESCRIPTION
**Pull request by ghost**
#71138

[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

image
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

image
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | ?
Browser:                               | ?
AdGuard version:                       | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

### CODE REVIEW

**Comment by Talented-X-Coder-X** [comment]
If correct, please take the second commit (Update specific.txt).

**Comment by Yuki2718** [comment]
> If correct, please take the second commit (Update specific.txt).

Ah, I guess I found one reason why we can't communicate well. PR does't work like that - repository owner can't choose specific commit, but all your commits will be cumulated and only the final results will be chosen.

I'm not sure if they should be addressed as ads or annoyances. In any case, better to change to
```
||smallseotools.com/teriiii_
smallseotools.com##div[id^="hmmmm_"]
```

**Comment by Talented-X-Coder-X** [comment]
How should I change? If I edit, one more commit will be opened, just like before. Right?

**Comment by Yuki2718** [comment]
> How should I change? If I edit, one more commit will be opened, just like before. Right?

Uh, I'm not sure if I get what you mean. PR won't be opened until you explicitly make PR, but one PR can include many commits, which is no problem at all. If you want to change something, just checkout an according branch (in this case patch-12), edit files, add a new commit, and push the commit. You don't need to open new PR, your change will automatically be added to the existing PR.

**Comment by Talented-X-Coder-X** [comment]
Thanks for your assistance! Glad you helped ;). I get it.

**Pull request closed without merging**
