### PR TITLE
skip the timer #58044

### PR DESCRIPTION
**Pull request by Sergey-Lyapin**
#58044

### CODE REVIEW

**Comment by Alex-302** [comment]
I see error message when timer is adjusted.

**Comment by Sergey-Lyapin** [comment]
> I see error message when timer is adjusted.

strange, I don't see any errors

**Comment by Alex-302** [comment]
image

**Comment by Sergey-Lyapin** [comment]
still can't reproduce the error
@zloyden please take a look

**Comment by zloyden** [comment]
I have the same error as Alex-302
<details><summary>Screenshot:</summary>

image
</details><br/>

**Comment by Alex-302** [comment]
Ok. Better leave is as is.

**Pull request closed without merging**
