### PR TITLE
fix #76805 haberconnect.net

### LINKED ISSUE #76805: haberconnect.net
### Issue URL (Anti Adblock Script)
 [https://haberconnect.net/istanbullu-65-yas-ustu-vatandaslara-ve-20-yas-alti-genclere-mujdeli-haber](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fhaberconnect.net%2Fistanbullu-65-yas-ustu-vatandaslara-ve-20-yas-alti-genclere-mujdeli-haber)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.31
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (2880)
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Security:</b><br/> NoCoin Filter List<br/><br/><b>Language-specific:</b><br/> AdGuard Turkish

### PR DESCRIPTION
**Pull request by wout-codes**
#76805

### CODE REVIEW

**Comment by Yuki2718** [comment]
This is a Turkish site so has to be addressed in Turkish filter. Also please fix cookie pop too.

**Comment by wout-codes** [comment]
@Yuki2718 I was told to always put in common rules whether in English Filter or any other filter.

**Comment by Yuki2718** [comment]
Sorry, you're right.

**Comment by wout-codes** [comment]
@Yuki2718 cookie Popup is already fixed in AdGuard Annoyances Filter, check the filtering log.

**Comment by Yuki2718** [comment]
Not on my end:

<details>

haberconnect

</details>

**Comment by wout-codes** [comment]
@Yuki2718 Please update your filters and check.
<details>

image
</details>

**Comment by Yuki2718** [comment]
I got it, this is because I have your `$generichide` for test. If generic hide is used specific hiding rule is still needed.

**Comment by wout-codes** [comment]
@Yuki2718 That's for content blockers. For extensions use `bab`.

**Comment by Yuki2718** [comment]
Content blocker user still use Annoyances filters.

**Comment by wout-codes** [comment]
@Yuki2718 Haha I know. I wanted to tell to the devs, but I didn't tell. But what to do? They told us to do it like that.

**Comment by Yuki2718** [comment]
There are already some such duplicates (i.e. specific rules covered by generic counterparts) in Social and Annoyances filters, so simply adding the specific rule is okay I guess, but you can wait for reply from the official AG members.

**Pull request merged**
