### PR TITLE
fix: `pixiv.net` cookie notices and infinite reload due to rules conflict

### PR DESCRIPTION
**Pull request by JasonKhew96**
### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads or ad leftovers;
- [x] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [x] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

## What issue is being fixed?

- fix `pixiv.net` cookie notices rule, the cookie value should be `6`
- fix infinite reload if enabled with `EasyList - Cookie Notices` since this filter set cookie value to `5` and `EasyList - Cookie Notices` set cookie value to `6`

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Review by Yuki2718 — APPROVED** [review]

**Comment by Yuki2718** [comment]
@Alex-302 Hard breakage on a very popular site, it's not something to be left for days.

**Comment by JasonKhew96** [comment]
context:
https://www.reddit.com/r/Pixiv/comments/1cia7rx/people_who_cant_load_pixiv_pixiv_doesnt_like/
https://www.reddit.com/r/Pixiv/comments/1chioso/i_finally_got_pixiv_to_load_but_why_is_it_using_a/
https://www.reddit.com/r/Pixiv/comments/1cg2bq5/pixiv_is_not_loading/

**Review by AdamWr — APPROVED** [review]

**Comment by jackrjli** [comment]
This breakage will happen again if Pixiv changes the cookie value (which I guess they do when they update their privacy policy and need to notify everyone again) and the lists update to reflect that. I wonder whether it is necessary to set the cookie at all, since even without this rule the privacy policy update banner is hidden by a cosmetic filter:
```
pixiv.net##div > div:not([class]) > div[class^="sc-"]:has(> div > p > span > a[href^="https://policies.pixiv.net"])
```
https://github.com/AdguardTeam/AdguardFilters/blob/9bb7c0054eb436e51692b07db4f5baef7f82b5c0/AnnoyancesFilter/Cookies/sections/cookies_specific.txt#L6855

**Comment by krystian3w** [comment]
If can by hidden instead `trusted-click-element` if button are stable.

**Comment by AtomicLugia** [comment]
Pixiv is at it again, the filter doesn't work anymore, infinite reload is back

**Comment by Yuki2718** [comment]
> Pixiv is at it again, the filter doesn't work anymore, infinite reload is back

I can't reproduce.

**Comment by Catman-232** [comment]
Found my way here due to searching this issue, sorry for bumping. I don't remember how long it's been the case but this happens to me when going to gallery pages that have been deleted, which is a "Page not found" page, but on the original `/artworks/1234567etc` url. So for example this one that just got me thinking about this: https://www.pixiv.net/en/artworks/55438630

In uBO's logger I don't really know what to look for but I do see the `pixiv.net##+js(set-cookie-reload, privacy_policy_agreement, 6)` rule, followed by EasyList - Cookie Notices `pixiv.net##+js(set-cookie, privacy_policy_agreement, 6, , reload, 1)`

Actually even stranger is that I opened it in a private browsing window and it reloads over and over just the same, so maybe it's actually something about the web browser config or just something on Pixiv's end.

**Comment by JasonKhew96** [comment]
> Found my way here due to searching this issue, sorry for bumping. I don't remember how long it's been the case but this happens to me when going to gallery pages that have been deleted, which is a "Page not found" page, but on the original `/artworks/1234567etc` url. So for example this one that just got me thinking about this: https://www.pixiv.net/en/artworks/55438630
> 
> In uBO's logger I don't really know what to look for but I do see the `pixiv.net##+js(set-cookie-reload, privacy_policy_agreement, 6)` rule, followed by EasyList - Cookie Notices `pixiv.net##+js(set-cookie, privacy_policy_agreement, 6, , reload, 1)`
> 
> Actually even stranger is that I opened it in a private browsing window and it reloads over and over just the same, so maybe it's actually something about the web browser config or just something on Pixiv's end.

@Catman-232 reproduced without any extension, with some early investigation, pixiv frontend try to redirect between `https://www.pixiv.net/artworks/55438630` and `https://www.pixiv.net/{language}/artworks/55438630` if you don't have Japanese language selected.

**Comment by krystian3w** [comment]
> reproduced without any extension

So page logic is broken in that case.

**Pull request merged**
