### PR TITLE
Partial fix #76235 file-upload.net (leftovers)

### LINKED ISSUE #76235: file-upload.net
### Issue URL (Anti Adblock Script)
 [https://www.file-upload.net/download-14505811/LoremIpsum.txt.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.file-upload.net%2Fdownload-14505811%2FLoremIpsum.txt.html)
### Comment
Username: `@andy-kl`
> 
> --
> Die folgenden Informationen werden automatisch generiert. Bitte löschen Sie sie nicht.
> 
> Referrer:
> 
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.3
Browser: | Chrome
AdGuard driver: | WFP
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> Fanboy's Anti-Facebook List, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> Fanboy's Social Blocking List, <br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> Adblock Warning Removal List, <br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/> NoCoin Filter List<br/><br/><b>Other:</b><br/> AdGuard Experimental<br/><br/><b>Language-specific:</b><br/> AdGuard Russian, <br/>AdGuard German
Custom filter subscriptions: | https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

### PR DESCRIPTION
**Pull request by wout-codes**
#76235
Leftovers at last page. Site changes ad-servers frequently so putting `src^=` is not helpful.

### CODE REVIEW

**Comment by Alex-302** [comment]
I see only one ad, which can be blocked by `||file-upload.net/include/mitte-orig.php`

**Comment by wout-codes** [comment]
@Alex-302 Did you go to the last page (download page)?

**Comment by wout-codes** [comment]
Your rule doesn't block.

**Comment by wout-codes** [comment]
@Alex-302 Check with AdGuard for Windows. It doesn't work on my end.

**Comment by wout-codes** [comment]
@Alex-302 

<details>

image
</details

**Comment by Alex-302** [comment]
This is just not collapsed iframe. My rule blocks content.
`file-upload.net##iframe` is too wide. Why not `file-upload.net###dwdiv2-ads`?

**Comment by wout-codes** [comment]
> file-upload.net###dwdiv2-ads

Okay changed.

**Pull request merged**
