### PR TITLE
The second large cleanup of JP filters

### PR DESCRIPTION
**Pull request by Yuki2718**
```
! Obsolete elements
sponichi.co.jp###relation-block
ameblo.jp###resPointAreaWrapper
nifty.com###sexy
jiji.com###shopping_2nd
muzie.ne.jp###sideb
warnermycal.com###skyBnr
imageporter.com###slashpage
rakuten.co.jp###sponcerMain
newsonjapan.com###squarebanner_text300x250
rakuten.co.jp###srEsper
rakuten.co.jp###srEsperHead
rakuten.co.jp###srNaviSponcer
infoseek.co.jp###srchls
jiji.com###sumai_banner
! should be covered by ###tadsb[aria-label] in EL
google.co.jp###tadsb
mocovideo.jp###toprightad_m_r
nicovideo.jp###web_pc_premium
nicovideo.jp###web_pc_prime
sponichi.co.jp###yaad4
mainichi.jp##.AdAA
mainichi.jp##.ArticleAd
asahi.com##.BnrLnkLct
asahi.com##.BnrLnkSbs
asahi.com##.BoxFeatPlan
mainichi.jp##.Campaign
lifehacker.jp##.EntryMoreBanner
! The rule below is more of FP. Test on https://www.nikkei.com/article/DGXMZO65071870W0A011C2MM0000/
nikkei.com##.JSID_tagFooter

! New cosmetic rules
asahi.com###NativePr
asahi.com###Outbrain_Osusume
dic.nicovideo.jp###right-column > div[style*="height:250px; width:300px;"]
dic.nicovideo.jp##.ad-bannar-maincolumn-top
dic.nicovideo.jp##.adsense-728
dot.asahi.com##.atclTitleAreaRecommendarticle
koneta.nifty.com###custom_html-2
plaza.rakuten.co.jp###commonAdsParts
websearch.rakuten.co.jp###ads-billboard
websearch.rakuten.co.jp###teamsite-mid-pickup
websearch.rakuten.co.jp##.section-title1[style="margin-bottom: 10px;"]


! New basic rules
! https://www.sponichi.co.jp/entertainment/news/2020/10/16/kiji/20201016s00041000171000c.html
||d2-apps.net^$third-party
||sponichi.co.jp/adds/*/shopping/sannex_

! https://ameblo.jp/mathisii/
||ad.pr.ameba.jp^
```

### CODE REVIEW

**Review by Alex-302 — APPROVED** [review]

**Comment by Alex-302** [comment]
Thanks. Looks good)

**Comment by Alex-302** [comment]
@AdguardTeam/filters-maintainers

**Comment by zloyden** [comment]
I just finished reviewing this pull request. Great job)

**Review by zloyden — APPROVED** [review]

**Comment by chirag127** [comment]
By the way, how do you make a list of obsolete rules.

**Comment by Yuki2718** [comment]
@chirag127 
https://github.com/AdguardTeam/AdguardFilters/pull/65635
`I tracked (parts of) the oldest rules in JP filter taken over from Fanboy Japanese and checked each, removed obsolete, and added new rules`

**Comment by chirag127** [comment]
> tracked (parts of) the oldest rules in JP 

so you mean to say that you go to each and every site one by one and then note down the rules . which are not used and then posted them here.

it is very labour intensive work to just like that if tried to done it by only looking at the filtering logs  . do you use some other tools for it.

**Comment by Yuki2718** [comment]
> So you mean to say that you go to every site one by one and then note down the rules,which are not used and then posted them here?

Yes, and the oldest rules can be found in Github history.
 
>  do you use some other tools for it?

At most publicwww and Google search (often with `site:example.com`) to reduce chance of missing minor subpages. In other cleanups such as Base/Spyware I use redundant checker and PyFunceble, but not in case of JP filter cleanups.

**Pull request merged**
