### PR TITLE
fix #76946 hentaihere.com

### LINKED ISSUE #76946: hentaihere.com
### Issue URL (Ads)
 [https://hentaihere.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fhentaihere.com%2F)
### Comment
Username: @wernser412
> popup

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.31
Browser: | Chrome
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Russian, <br/>AdGuard Spanish/Portuguese

### PR DESCRIPTION
**Pull request by wout-codes**
#76946

### CODE REVIEW

**Comment by Yuki2718** [comment]
Of note `||duamilsyr.com^` is in Chinese filter (yet should be added to Base too, the site is not Chinese) and I don't think this domain will be accessed as first-party.

**Comment by wout-codes** [comment]
I will remove it @Yuki2718

**Comment by Yuki2718** [comment]
No need, the duplicate will anyway be discarded so no harm.

**Comment by wout-codes** [comment]
> No need, the duplicate will anyway be discarded so no harm.

Okay, closed

**Pull request merged**
