### PR TITLE
Fix #177317 gamefa.com

### LINKED ISSUE #177317: en.gamefa.com
### Issue URL (Ads)
 [https://en.gamefa.com/2175/agents-tactics-and-tips-for-developing-rank-in-valorant/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fen.gamefa.com%2F2175%2Fagents-tactics-and-tips-for-developing-rank-in-valorant%2F)
Username: `@rakleed`

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | Value
--- | ---
AdGuard product: | AdGuard for Mac v2.13.0.1558 release
Browser: | Chrome
Stealth mode options: | Strip URLs from tracking parameters, <br>Hide your search queries, <br>Hide your Referrer from third-parties, <br>Hide your User-Agent, <br>Remove X-Client-Data header from HTTP requests, <br>Protect against DPI, <br>Disable cache for third-party requests, <br>Block trackers
DNS filtering: | server: `https://dns.cloudflare.com/dns-query`<br>
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Cookie Notices, <br/>AdGuard Popups, <br/>AdGuard Mobile App Banners, <br/>AdGuard Other Annoyances, <br/>AdGuard Widgets<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>Persian Blocker
Userscripts: | IMDb Tomatoes (url: https://update.greasyfork.org/scripts/15222/IMDb%20Tomatoes.user.js)<br>AdGuard Extra (url: https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js)<br>Nova YouTube (url: https://update.greasyfork.org/scripts/433360/Nova%20YouTube.user.js)
Referrer: | [https://en.gamefa.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fen.gamefa.com%2F)

### PR DESCRIPTION
**Pull request by artemiv4nov**
Fix for #177317

Updated PR of https://github.com/AdguardTeam/AdguardFilters/pull/177776

### CODE REVIEW

**Review by piquark6046 — CHANGES_REQUESTED** [review]
please resolve the conflict.

**Review by piquark6046 — DISMISSED** [review]

**Review by AdamWr — APPROVED** [review]

**Review by piquark6046 — COMMENTED** [review]
@Alex-302 
I think that the website ( `en.gamefa.com` ) does not have the enough traffic.
However, its main domain ( `gamefa.com` ) has the enough traffic.
Brought from SimilarWeb Pro.

<details><summary>Screenshots</summary>
<p>

Screenshot from 2024-04-24 21-03-51
image


</p>
</details>

**Comment by Alex-302** [comment]
@piquark6046 
> I think that the website ( en.gamefa.com ) does not have the enough traffic.
However, its main domain ( gamefa.com ) has the enough traffic.

We usually check traffic of the main domain. So it must be fixed. But in `foreign.txt` => Persian

**Comment by piquark6046** [comment]
CC: @MasterKia

**Comment by Alex-302** [comment]
@MasterKia there are more ads on the main domain gamefa.com Please handle them

<details>
<summary>Details</summary>

image


</details>

**Pull request closed without merging**
