### PR TITLE
fix #76615 pacesuite.com

### LINKED ISSUE #76615: pacesuite.com
### Issue URL (Annoyance)
 [https://pacesuite.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fpacesuite.com%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.31
Browser: | Chrome
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Turkish, <br/>AdGuard French, <br/>AdGuard Russian, <br/>AdGuard Chinese, <br/>AdGuard German, <br/>AdGuard Japanese, <br/>AdGuard Dutch, <br/>AdGuard Spanish/Portuguese

### PR DESCRIPTION
**Pull request by wout-codes**
#76615

### CODE REVIEW

**Review by zloyden — CHANGES_REQUESTED** [review]
Also add `pacesuite.com#%#//scriptlet('remove-class', 'cookies-requested', 'body')`

**Comment by wout-codes** [comment]
> Also add `pacesuite.com#%#//scriptlet('remove-class', 'cookies-requested', 'body')`

Where and why?

**Comment by zloyden** [comment]
> Where and why?

`cookies_specific.txt` - JS rules.
There is a leftover  that is not removed by your rule.

**Comment by wout-codes** [comment]
> > Where and why?
> 
> `cookies_specific.txt` - JS rules.
> There is a leftover that is not removed by your rule.

Ah yes. I didn't see that. Thanks.

**Review by zloyden — APPROVED** [review]

**Pull request merged**
