### PR TITLE
fix #79402 cryptodirectories.com

### LINKED ISSUE #79402: cryptodirectories.com
### Issue URL (Ads)
 [https://cryptodirectories.com/faucet/DASH?r=XjGaa6yfwzfxobJ9mTooKyrTKf3TFbN8U8](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fcryptodirectories.com%2Ffaucet%2FDASH%3Fr%3DXjGaa6yfwzfxobJ9mTooKyrTKf3TFbN8U8)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.34
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (2880), <br>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Turkish, <br/>AdGuard Russian, <br/>AdGuard Spanish/Portuguese

### PR DESCRIPTION
**Pull request by stanislav-atr**
#79402

### CODE REVIEW

**Comment by wout-codes** [comment]
There are a lot more to fix. 
Add the domain to this existing rule `##ins[class][style^="display:inline-block;"]` and remove the current rule.
`cryptodirectories.com##br`
`cryptodirectories.com##.code-block` - There is an existing rule with `##.code-block`


- To prevent auto refresh

``` 
cryptodirectories.com#%#AG_onLoad(function(){document.querySelector('meta[http-equiv="REFRESH"]')&&setTimeout(function(){window.stop()},4E3)});
cryptodirectories.com$$meta[http-equiv="REFRESH"]
```
`cryptodirectories.com##.rc-advert` - RainCaptcha Advertisement

**Review by zloyden — CHANGES_REQUESTED** [review]
@stanislav-atr I'd use these rules
```
cryptodirectories.com##ins[class][style^="display:inline-block;"]
cryptodirectories.com##.code-block
cryptodirectories.com##iframe[data-src*="ads.com"]
cryptodirectories.com##center > a[href^="https://cryptodirectories.com/"]
cryptodirectories.com##.rc-advert
cryptodirectories.com##.entry-content br
cryptodirectories.com#%#AG_onLoad(function(){document.querySelector('meta[http-equiv="refresh"]')&&setTimeout(function(){window.stop()},4E3)});
cryptodirectories.com$$meta[http-equiv="refresh"]
```

**Comment by wout-codes** [comment]
@zloyden You have forgotten this I think `cryptodirectories.com##.code-block`. 
image

**Comment by zloyden** [comment]
Thanks, also added to the list.

**Comment by wout-codes** [comment]
There is an existing rule already for this `##.code-block`. Just add the domain there.

**Review by zloyden — APPROVED** [review]

**Review by wout-codes — APPROVED** [review]

**Pull request merged**
