### PR TITLE
Add v.qq.com specific to Chinese filter

### PR DESCRIPTION
**Pull request by Hill-98**
# Creating the pull request

> Please include a summary of the change and which issue is fixed\
> If the related issue does not exist in our repository, please create it before making pull request\
> It is highly recommended to use our [Web Reporting Tool](https://kb.adguard.com/technical-support/reporting-tool) instead of creating an issue on GitHub directly\
> Please note, that we verify every pull request manually, so it may take time to apply it

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [x] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

1.iWan Advertisement in the lower right corner of the channel page

2.Game advertisement in the lower right corner of the video playback page.

3.Home page video card advertisement

<details>

<summary>Screenshot 1:</summary>

image

</details>

<details>

<summary>Screenshot 2:</summary>

image

</details>

<details>

<summary>Screenshot 3:</summary>

image

</details>

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Comment by Alex-302** [comment]
It seems Chinese filters block them. Removed obsolete rule.

**Comment by Hill-98** [comment]
@Alex-302 I used the latest Chinese filter for testing, but only the ads in screenshot 3 were filtered, so the rules in screenshots 1 and 2 are still valid.

**Comment by Hill-98** [comment]
Screenshot 1: https://v.qq.com/channel/cartoon
Screenshot 2: https://v.qq.com/x/cover/mzc0020098j8e13/l004778itj0.html

The ad in screenshot 1 may not be displayed on non-Chinese networks.

**Comment by Alex-302** [comment]
* `v.qq.com##a.focus-item[dt-params*="business=ad"]` - already blocked

<details>
<summary>Details</summary>

image

</details>

* `.card-wrap[dt-params*="business=ad"]`, `.game-switch-ad`, `#iwan-gamependant-page` - I don't see. Need at leash screenshot of an ad + devtools

**Comment by Alex-302** [comment]
Ok, please leave 
```adblock
v.qq.com##div.game-switch-ad
v.qq.com###iwan-gamependant-page
```

**Pull request closed without merging**
