### PR TITLE
fix #79724 paidtomoney.com

### LINKED ISSUE #79724: paidtomoney.com
### Issue URL (Ads)
 [https://paidtomoney.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fpaidtomoney.com%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.34
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (2880), <br>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection, <br/>EasyPrivacy<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Turkish, <br/>AdGuard Russian, <br/>AdGuard Spanish/Portuguese

### PR DESCRIPTION
**Pull request by wout-codes**
#79724

### CODE REVIEW

**Review by stanislav-atr — APPROVED** [review]
Could go for `[style="display:inline-block;width:"]`.

**Comment by wout-codes** [comment]
Hi. It may be too wide. :) There is a common rule so I have just added it there.

**Comment by stanislav-atr** [comment]
> Hi. It may be too wide. :) There is a common rule so I have just added it there.

I meant `##ins[class][style="display:inline-block;width:"]`, but common is ok i guess.

**Comment by wout-codes** [comment]
Ok.

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
