### PR TITLE
rule-maintenance - 25

### PR DESCRIPTION
**Pull request by SKEIDs**
AnnoyancesFilter/sections/mobile-app.txt

### CODE REVIEW

**Review by Alex-302 — APPROVED** [review]

**Comment by Alex-302** [comment]
> [group website in alphabetical order](https://github.com/AdguardTeam/AdguardFilters/pull/118725/commits/7e455b1fb2d77c2f207488b09f2b3eecc378bf2e)

Please never do it. Unncessary change, and hard to check it.

**Comment by SKEIDs** [comment]
> > [group website in alphabetical order](https://github.com/AdguardTeam/AdguardFilters/pull/118725/commits/7e455b1fb2d77c2f207488b09f2b3eecc378bf2e)
> 
> 
> 
> Please never do it. Unncessary change, and hard to check it.

i see

**Comment by Alex-302** [comment]
At least - it should not be done manually. We need own sorting script.

**Comment by SKEIDs** [comment]
> At least - it should not be done manually. We need own sorting script.

If the rules can be sort in a script, that would be best.

**Pull request merged**
