### PR TITLE
Fix #54102

### LINKED ISSUE #54102: theverge.com delay
@SeriousHoax commented on [Sat Apr 18 2020](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1626)

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  3.4.19
- **Browser and version:**
  -  Chromium Edge 81
- **Operating system and version:**
  -  Windows 10
- **Filters you use in AdGuard:**
  -  Adguard Base, AdGuard Mobile Ads, Adguard Tracking Protection, Adguard Annoyances, Adguard Social Media
- **Stealth Mode settings:**
  - 
- **Other browser extensions:**
  - 

### Expected Behavior

 Website loading with unnecessary delay

### Actual Behavior

 Delay in page loading for https://www.theverge.com/ 
When the page is visited there's always a certain unnecessary delay for the page to come into view. Now if I click on an article then there's a delay again, if I go back then there's a delay as well. This is Adguard extension related because there's no such issue with uBlock Origin with same filters.

### Screenshots

 Check the gif for details on how to reproduce

<details><summary>Screenshot:</summary>

adg
</details>

### Additional Information

---

@zecanard commented on [Sat Apr 18 2020](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1626#issuecomment-615896273)

Not experiencing this with the browser extension in Safari on macOS Catalina 10.15.4 and iOS 13.4.1, if that helps narrow it down.

---

@SeriousHoax commented on [Sat Apr 18 2020](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1626#issuecomment-615897056)

> 
> 
> Not experiencing this with the browser extension in Safari on macOS Catalina and iOS 13.4.1, if that helps narrow it down.

I've asked this to some other users on Windows and they are experiencing this delay too more or less. One of them is even using Adguard desktop. He has this delay too on The Verge website. So maybe this needs to be tested on Windows. Same behavior with Firefox on Windows 10.

---

@Yuki2718 commented on [Mon Apr 20 2020](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1626#issuecomment-616291353)

> 
> One of them is even using Adguard desktop. 

In fact it's not an extension issue but a filter issue, so should be moved to AdGuardFilters.
Please add this to User Rules and test:
`||googletagmanager.com/gtm.js$script,redirect=googletagmanager-gtm,domain=theverge.com`

If the issue persists, also:
```
||googletagservices.com/tag/js/gpt.js$script,redirect=googletagservices-gpt,domain=theverge.com
theverge.com#%#//scriptlet('abort-current-inline-script', 'CONCERT_ADS_CONFIG.dfpVariables')
```

---

@Alex-302 commented on [Mon Apr 20 2020](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1626#issuecomment-616431694)

Hmm. I cannot reproduce this issue - page content loaded fast.

---

@SeriousHoax commented on [Mon Apr 20 2020](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1626#issuecomment-616451760)

> 
> 
> > One of them is even using Adguard desktop.
> 
> In fact it's not an extension issue but a filter issue, so should be moved to AdGuardFilters.
> Please add this to User Rules and test:
> `||googletagmanager.com/gtm.js$script,redirect=googletagmanager-gtm,domain=theverge.com`
> 

Hi, the first rule fixed the issue. The second one was not required. Now the page is loading fast as it should. So should this be forwarded to Adguard filters? 

---

@Yuki2718 commented on [Mon Apr 20 2020](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1626#issuecomment-616512943)

> 
> 
> Hmm. I cannot reproduce this issue - page content loaded fast.

It may not be obvious delay, but when visited the top page I got page-blink or a temporal black screen, and after clicking any article again blink or a temporal white screen - how long it take depends, sometimes 0.5 sec or so other times more.  Reproduced on: Firefox 75.0 + AG 3.4.19 (Base + Tracking)

### PR DESCRIPTION
**Pull request by Yuki2718**
https://github.com/AdguardTeam/AdguardFilters/issues/54102

### CODE REVIEW

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/4356df9bf74d856fb1284f733507bbb92c4e174f

**Comment by Yuki2718** [comment]
> 
> 
>     * rule for platforms without `$redirect` rules
>       [4356df9](https://github.com/AdguardTeam/AdguardFilters/commit/4356df9bf74d856fb1284f733507bbb92c4e174f)

Sorry about that. According to @zecanard , iOS doesn't suffer from this issue, so better to use NOT_PLATFORM?

**Comment by zecanard** [comment]
> Sorry about that. According to @zecanard , iOS doesn't suffer from this issue, so better to use NOT_PLATFORM?
> 
> EDIT: Confirmed, no problem on iOS so no need to whitelist.

Also tested in Firefox with lots more filters than my Safari installation (244k rules vs. 134k), updated 8 days ago (I only rarely open Firefox). Fast loading, still on macOS Catalina 10.15.4.

**Comment by Yuki2718** [comment]
Further finding on Android, the exception actually doesn't solve the issue.

**Comment by Yuki2718** [comment]
Alternative solution:
`theverge.com#%#//scriptlet('abort-current-inline-script', 'document.documentElement', 'GTM-')`
But a question is whether Android (Samsung) CB supports scriptlet injection.

**Comment by Alex-302** [comment]
> But a question is whether Android (Samsung) CB supports scriptlet injection.

no support

**Comment by Yuki2718** [comment]
> 
> 
> no support

Okay then leave Android CB, it's anyway not an AG issue.

**Pull request closed without merging**
