### PR TITLE
seolaboratory.jp 

### PR DESCRIPTION
**Pull request by SKEIDs**
#103134

### CODE REVIEW

**Review by Sergey-Lyapin — CHANGES_REQUESTED** [review]
@SKEIDs
These banners do not lead to third-party resources so please move these rules to self-promo.txt.
And add `||adgocoo.com^$third-party` to the spyware filter > tracking servers

**Comment by Yuki2718** [comment]
Probably `||seolaboratory.jp/banner/` is better.

**Comment by SKEIDs** [comment]
> Probably `||seolaboratory.jp/banner/` is better.

ok. I add this rule to spyware filter > tracking servers

**Comment by Yuki2718** [comment]
> 
> ok. I add this rule to spyware filter > tracking servers

No, this should be in Annoyance > self-promo.txt and replaces the current rules.

**Comment by SKEIDs** [comment]
> No, this should be in Annoyance > self-promo.txt and replaces the current rules.

replace `seolaboratory.jp##.under_ad_wrap` with `||seolaboratory.jp/banner/` ?

**Comment by Yuki2718** [comment]
> replace `seolaboratory.jp##.under_ad_wrap` with `||seolaboratory.jp/banner/` ?

If I didn't miss something, both
```
seolaboratory.jp##.side_ad_box
seolaboratory.jp##.under_ad_wrap
```

**Comment by SKEIDs** [comment]
> > replace `seolaboratory.jp##.under_ad_wrap` with `||seolaboratory.jp/banner/` ?
> 
> If I didn't miss something, both
> 
> ```
> seolaboratory.jp##.side_ad_box
> seolaboratory.jp##.under_ad_wrap
> ```

ok.fixed.

**Comment by Yuki2718** [comment]
> ok.fixed.

Not JPF but Annoyances > self-promo as suggested by @Sergey-Lyapin

**Comment by SKEIDs** [comment]
> Not JPF but Annoyances > self-promo as suggested by @Sergey-Lyapin

sorry. Are these correct?
https://github.com/AdguardTeam/AdguardFilters/pull/103287/commits/25f4525ca4902e108d82344bacb42142e23aad41
https://github.com/AdguardTeam/AdguardFilters/pull/103287/commits/2a5756aca09329d38003ffadf4c5e47d39c1c3bd

**Review by Yuki2718 — APPROVED** [review]

**Pull request merged**
