### PR TITLE
add new parameters for TikTok

### PR DESCRIPTION
**Pull request by fenopa**
refs:
https://github.com/Smile4ever/Neat-URL/issues/235
https://github.com/ThatRedKite/thatkitebot/blob/master/data/detrackparams.toml
https://github.com/mtxadmin/ublock/blob/master/filters/_removeparams
https://github.com/DrKain/tidy-url/blob/main/data/rules.js
https://github.com/DandelionSprout/adfilt/blob/master/LegitimateURLShortener.txt

### CODE REVIEW

**Comment by Alex-302** [comment]
Need example values and links with these params.

**Comment by fenopa** [comment]
there are some examples in ref links

**Comment by fenopa** [comment]
@BlazDT @jellizaveta can someone take a look? I spent time to compile these and it's getting closed without any respect.

**Comment by BlazDT** [comment]
Alex meant link to every tracking parameter with vues and how to reproduce them.
Some may sound like a tracker, but provide some function on the page.

**Comment by fenopa** [comment]
> Some may sound like a tracker, but provide some function on the page.

@BlazDT No they do not, all of these ref links for "tracking parameters", why would they include parameter that provide function to remove as tracking. The currently existing were added with a DandelionSprout/adfilt discussion link, this only updates them with that and some other links.

**Comment by Alex-302** [comment]
I don't see params in urls. Need real actual examples, and description where we can get them.

**Pull request closed without merging**
