### PR TITLE
fix #80963, #81160, #81157, #80957, #80953, #80955

### LINKED ISSUE #80963: russiacoin.xyz
### Issue URL (Anti Adblock Script)
 [http://russiacoin.xyz/?r=DSmfGGmpPZretmuz8msYRdYq6KLQAPCRD5](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Frussiacoin.xyz%2F%3Fr%3DDSmfGGmpPZretmuz8msYRdYq6KLQAPCRD5)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.34
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (2880), <br>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection, <br/>EasyPrivacy<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Turkish, <br/>AdGuard Russian, <br/>AdGuard Spanish/Portuguese, <br/>EasyList Italy

### PR DESCRIPTION
**Pull request by wout-codes**
#80963, #81160, #81157, #80957, #80953, #80955

### CODE REVIEW

**Comment by Yuki2718** [comment]
Add timer boost.

**Comment by wout-codes** [comment]
@Yuki2718 Does this work for every domain in the rule? `claimbits.io,i-bits.io,diamondfaucet.space,gobits.io,russiacoin.xyz,starsfaucet.com,lionltcfaucet.xyz,projecto2.xyz,faucet.shorterall.com,yellowfaucet.ovh#%#//scriptlet("adjust-setInterval", "seconds", "", "0.02")`

**Comment by Yuki2718** [comment]
@wout-codes Didn't check all but at least should work on `lionltcfaucet.xyz` and you can reference uAssets for the rest.

**Comment by wout-codes** [comment]
It works, fortunately.

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
