### PR TITLE
fix #80037 psdly.com

### LINKED ISSUE #80037: www.psdly.com
### Issue URL (Anti Adblock Script)
 [https://www.psdly.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.psdly.com%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.3
Browser: | Firefox
AdGuard driver: | TDI
Stealth mode options: | 
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Language-specific:</b><br/> EasyList Lithuania, <br/>AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Dutch
Userscripts: | https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js

### PR DESCRIPTION
**Pull request by wout-codes**
#80037

### CODE REVIEW

**Review by Alex-302 — COMMENTED** [review]
cannot reproduce antoadblock

**Comment by wout-codes** [comment]
I still can reproduce it.

**Comment by Alex-302** [comment]
no script in html on JS files

**Comment by wout-codes** [comment]
Yeah, I can't reproduce anti-adblock anymore, but I still can reproduce the others.

**Comment by Alex-302** [comment]
Yes, the question was about anti-adblock only.

**Pull request merged**
