### PR TITLE
fix #75491 parasportontario.ca

### LINKED ISSUE #75491: parasportontario.ca
### Issue URL (Anti Adblock Script)
 [https://parasportontario.ca/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fparasportontario.ca%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.6 nightly 19
Browser: | Opera
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (180), <br>Block Push API, <br>Block Location API
DNS filtering: | server: `https://dns-unfiltered.adguard.com/dns-query`<br>filters: `User rules`
Filters: | <b>Ad Blocking:</b><br/> EasyList, <br/>Peter Lowe's Blocklist, <br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> EasyPrivacy, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> Adblock Warning Removal List, <br/>I don't care about cookies, <br/>EasyList Cookie List, <br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/> Online Malicious URL Blocklist, <br/>Spam404, <br/>NoCoin Filter List<br/><br/><b>Language-specific:</b><br/> AdGuard Spanish/Portuguese
Custom filter subscriptions: | https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

### PR DESCRIPTION
**Pull request by wout-codes**
#75491
Is that the correct place to add these rules?
```
parasportontario.ca#@#.adg_row
parasportontario.ca#@#.adg_cell
```

### CODE REVIEW

**Review by AdamWr — APPROVED** [review]

**Comment by wout-codes** [comment]
@AdamWr Set-constant also works in this case.

**Comment by wout-codes** [comment]
@AdamWr By the way, should I use hints for this?
example.com#%#//scriptlet("set-constant", "isAdBlockActive", "false")
@@||example.com/js/prebid-ads.js

**Comment by AdamWr** [comment]
I know, but it just "breaks" their anti-adblock script, the same like `abort-on-property-read` in this case, so I prefered to use it.

**Comment by wout-codes** [comment]
Ok.

**Pull request merged**
