### PR TITLE
Domain: mega.io ( mega.nz )

### PR DESCRIPTION
**Pull request by ghost**
They changed their domain from `mega.nz` to `mega.io`
https://mega.nz https://mega.io

### CODE REVIEW

**Comment by Yuki2718** [comment]
`mega.nz` is still working, so keep `.nz` for all the rules than just two.

**Comment by piquark6046** [comment]
> 
> 
> `mega.nz` is still working, so keep `.nz` for all the rules than just two.

But, I think they will change their main domain to `.io`..

https://twitter.com/MEGAprivacy/status/1351700047566520321
https://www.facebook.com/MEGAprivacy

**Comment by Yuki2718** [comment]
> 
> But, I think they will change their main domain to `.io`..
> 

Yeah, but it's not too late to remove the old domain only after it actually became obsolete. Currently nz is used and removing this will, for example, bring cookie notice back at https://github.com/AdguardTeam/AdguardFilters/issues/72583

**Comment by piquark6046** [comment]
fd9cfec396317848db647638baac4b0aa969f851; Is it Okay?
@Yuki2718

**Comment by Yuki2718** [comment]
>  Is it Okay?

I think so, but of course I'm not in the position to say okay or not, you know.

**Comment by piquark6046** [comment]
> 
> 
> > Is it Okay?
> 
> I think so, but of course I'm not in the position to say okay or not, you know.

Okay. Thank for reviewing my pull request.

**Comment by Alex-302** [comment]
It works as redirect to NZ.
Not working if you try to download
image

**Comment by piquark6046** [comment]
> 
> 
> It works as redirect to NZ.
> Not working if you try to download
> image

`mega.io` which is the homepage of MEGA works.
However, do you want to close this pull request?

**Comment by Alex-302** [comment]
Better wait some time. It can be reopened if necessary.

**Comment by piquark6046** [comment]
> 
> 
> Better wait some time. It can be reopened if necessary.

OK.

**Comment by piquark6046** [comment]
Screenshot

**Comment by piquark6046** [comment]
@Alex-302 Cloud you please check it out?

**Comment by Alex-302** [comment]
ok

**Comment by Yuki2718** [comment]
@Alex-302 Adjusted, see https://github.com/AdguardTeam/AdguardFilters/pull/72586

**Pull request closed without merging**
