### PR TITLE
fix #68042 jshow.tv

### LINKED ISSUE #68042: jshow.tv
### Issue URL (Ads)
 [https://jshow.tv/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fjshow.tv%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.2
Browser: | Edge 86.0.622.69 (Chromium-based)
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Remove X-Client-Data header from HTTP requests, <br/>Strip URLs from tracking parameters, <br/>Block third-party Authorization header, <br/>Self-destructing third-party cookies (1), <br/>Disable cache for third-party requests, <br/>Block Push API, <br/>Block Location API, <br/>Block Flash, <br/>Hide your Referrer from third-parties (jshow.tv), <br/>Hide your User-Agent ()
Filters: | <b>Ad Blocking:</b><br/> EasyList, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> EasyPrivacy, <br/>AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances

### PR DESCRIPTION
**Pull request by Yuki2718**
https://github.com/AdguardTeam/AdguardFilters/issues/68042

Not reproduced on my end, but since the site has been changing ad-servers constantly added generic fixes.

### CODE REVIEW

**Comment by Alex-302** [comment]
I don't see unblocked third-party requests. Do you still see ads?

**Comment by Yuki2718** [comment]
@Alex-302 Neither do I, but having observed the site, they constantly changes ad-servers. I already added a similar denyallow filter to uAssets and so far no problem: https://github.com/uBlockOrigin/uAssets/pull/7994

**Comment by Alex-302** [comment]
Added as https://github.com/AdguardTeam/AdguardFilters/commit/e3aea59010ebb67a4ef9f7281fee8bcd2b4b4c86#diff-b0bf1333dcfa2e503b6b6318a289d7553d3d6d091dfe5a17cc3a2664dd859cafR6-R8

**Comment by Yuki2718** [comment]
Okay, thx for understanding needs.

**Pull request closed without merging**
