### PR TITLE
fix #79335 mcrypto.club

### LINKED ISSUE #79335: mcrypto.club
### Issue URL (Ads)
 [https://mcrypto.club/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fmcrypto.club%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.34
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (2880), <br>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Turkish, <br/>AdGuard Russian, <br/>AdGuard Spanish/Portuguese

### PR DESCRIPTION
**Pull request by wout-codes**
#79335

### CODE REVIEW

**Comment by wout-codes** [comment]
Which level is this complicated "whatever you call it" in? `span:contains(/^(Our )?Sponsor$/):upward(3)`

**Comment by AdamWr** [comment]
Something strange happened when I resolved a conflict, I will add it directly.
Thank you.

>Which level is this complicated "whatever you call it" in? span:contains(/^(Our )?Sponsor$/):upward(3)

I think that I don't understand a question, could you please explain what exactly do you mean?

**Comment by wout-codes** [comment]
Ok. In simpler words, what does this even do? `span:contains(/^(Our )?Sponsor$/):upward(3)`? Isn't the one I made, simpler?

**Comment by AdamWr** [comment]
Yes it's simpler, it could be even simpler, for example - `:contains(Sponsor)` and it will work the same. It would match `Sponsor`, `Our Sponsor`, `whateverSponsor`.
This - `:contains(/^(Our )?Sponsor$/)` matches only exactly `Our Sponsor` and `Sponsor`.

**Comment by wout-codes** [comment]
Btw, how do you even write this regex?

**Comment by AdamWr** [comment]
To check a regex, you can for example use this website - https://regex101.com/

**Pull request closed without merging**
