### PR TITLE
Too broad filter, blocking legitimate scripts

### PR DESCRIPTION
**Pull request by indeed-a-genius**

### CODE REVIEW

**Comment by Alex-302** [comment]
Hi. We need few examples to check the rule.

**Comment by indeed-a-genius** [comment]
Don't have any examples. Stumbled upon this issue when developing my own website. The rule is too broad regardless.

**Comment by Alex-302** [comment]
I need at least one example)

**Comment by indeed-a-genius** [comment]
on https://m.lh1backup.pw/city/Dubai
these scripts are blocked:
https://m.lh1backup.pw/client/dist/front/js/main.js?ex=15197
https://m.lh1backup.pw/client/dist/m/js/vendor.js?ex=e03d0
https://m.lh1backup.pw/client/dist/m/js/app.js?ex=e03d0

**Comment by Alex-302** [comment]
I mean real example.

**Comment by indeed-a-genius** [comment]
Please check your e-mail notification for the original urls, I edited them
after for privacy reasons.

**Comment by krystian3w** [comment]
obraz

with this planed removed filter.

**Comment by Alex-302** [comment]
@indeed-a-genius that rule breaks only your sites. As I see, you don't want to see exclusions in the filter, but I can't remove this rule because it blocks ads. Changed it, will be applied to third-party requests only.

**Pull request closed without merging**
