### PR TITLE
fix #74082 desktophut.com

### LINKED ISSUE #74082: desktophut.com
### Issue URL (Anti Adblock Script)
 [https://www.desktophut.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.desktophut.com%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.6 nightly 15
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (180), <br>Block Push API, <br>Block Location API
DNS filtering: | server: `https://dns-unfiltered.adguard.com/dns-query`<br>filters: `User rules`
Filters: | <b>Ad Blocking:</b><br/> EasyList, <br/>Peter Lowe's Blocklist, <br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> EasyPrivacy, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> Adblock Warning Removal List, <br/>I don't care about cookies, <br/>EasyList Cookie List, <br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/> Online Malicious URL Blocklist, <br/>Spam404, <br/>NoCoin Filter List
Custom filter subscriptions: | https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_15_DnsFilter/filter.txt

### PR DESCRIPTION
**Pull request by wout-codes**
#74082
Fixes anti-adblock and leftover/placeholder.

### CODE REVIEW

**Comment by Yuki2718** [comment]
`desktophut.com#%#//scriptlet("prevent-setTimeout", "$", "200")` in EnglishFilter is not needed.

**Comment by wout-codes** [comment]
> `desktophut.com#%#//scriptlet("prevent-setTimeout", "$", "200")` in EnglishFilter is not needed.

Why though?

**Comment by Yuki2718** [comment]
> 
> Why though?

Isn't `desktophut.com##.ads` alone enough?

**Comment by wout-codes** [comment]
> > Why though?
> 
> Isn't `desktophut.com##.ads` alone enough?

Oh Yes.

**Review by Alex-302 — APPROVED** [review]

**Review by Yuki2718 — APPROVED** [review]

**Pull request merged**
