### PR TITLE
fix #77237 kissanime.si

### LINKED ISSUE #77237: kissanime.si
### Issue URL (Incorrect Blocking)
 [https://kissanime.si/Anime/Hortensia-Saga/Episode-010?id=169107](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fkissanime.si%2FAnime%2FHortensia-Saga%2FEpisode-010%3Fid%3D169107)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>
<details>
  <summary>Screenshot 2</summary>

  Screenshot 2
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.31
Browser: | Chrome
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion
Other extensions used: | bitdefender

### PR DESCRIPTION
**Pull request by wout-codes**
#77237
`kissanime.si` has a few mirrors like `kissanime.help`. The scriptlet is to prevent further popups.

### CODE REVIEW

**Comment by wout-codes** [comment]
@Alex-302 @AdamWr @zloyden I want your reviews.

**Comment by AdamWr** [comment]
`#%#//scriptlet("json-prune", "*", "pop_type")` fixes popups (opened in a new tab), what about adding also this rule:
`kissanime.*#%#//scriptlet("json-prune", "*", "rot_url")`
It should prevent these floatings ads even if they change ad server.

I also see one different ad server:
`||searsbushelbus.com^$third-party`
Please add it too.

**Comment by wout-codes** [comment]
> `#%#//scriptlet("json-prune", "*", "pop_type")` fixes popups (opened in a new tab), what about adding also this rule:
> `kissanime.*#%#//scriptlet("json-prune", "*", "rot_url")`
> It should prevents these floatings ads even if they change ad server.
> 
> I also see one different ad server:
> `||searsbushelbus.com^$third-party`
> Please add it too.

@AdamWr I know that ad-server. Once in one of my PR's, I added it in Base filter, @Sergey-Lyapin told me to move it to Japanese filter. So I am bewildered now.

**Review by zloyden — APPROVED** [review]

**Comment by AdamWr** [comment]
It seems that it's used not only on Japanese websites, so I guess it should be moved to Base filter.

**Comment by wout-codes** [comment]
> It seems that it's used not only on Japanese websites, so I guess it should be moved to Base filter.

Wait up. I will remove it from there and add it in base.

**Comment by zloyden** [comment]
> It seems that it's used not only on Japanese websites, so I guess it should be moved to Base filter.

I agree, @wout-codes you can moved it.

**Comment by wout-codes** [comment]
Done.

**Review by zloyden — APPROVED** [review]

**Comment by Sergey-Lyapin** [comment]
> @Sergey-Lyapin told me to move it to Japanese filter. So I am bewildered now.

Yes, because it was a Japanese site

**Review by AdamWr — APPROVED** [review]

**Comment by wout-codes** [comment]
> > @Sergey-Lyapin told me to move it to Japanese filter. So I am bewildered now.
> 
> Yes, because it was a Japanese site
> #76541

Yeah.

**Comment by Sergey-Lyapin** [comment]
@wout-codes 
And now, when we see that this server is used not only on Japanese sites, we move it to the base filter - nothing bewilderedable

**Comment by wout-codes** [comment]
> @wout-codes
> And now, when we see that this server is used not only on japanese sites, we move it to the base adserver - nothing bewilderedable

Thanks.

**Pull request merged**
