### PR TITLE
Fix #186058 chrome-stats.com

### LINKED ISSUE #186058: chrome-stats.com
### Issue URL (Ads)
 [https://chrome-stats.com/top](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fchrome-stats.com%2Ftop)

### Screenshots
<details>
  <summary>Screenshot 1 </summary>

  Screenshot 1
</details>

### System configuration

Information | Value
--- | ---
AdGuard product: | AdGuard Browser Extension v4.3.53
System version: | Windows 10
Browser: | Chrome
Stealth mode: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances
Browsing Security: | disabled
Browsing Security statistics: | disabled

### PR DESCRIPTION
**Pull request by gork7777**
### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [x] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

### Enter the issue address

https://github.com/AdguardTeam/AdguardFilters/issues/186058

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Review by jellizaveta — APPROVED** [review]

**Comment by jellizaveta** [comment]
@gork7777 Hello. Could you please resolve conflicts?

**Comment by Alex-302** [comment]
Or open new PR.

**Comment by gork7777** [comment]
@jellizaveta How can I do this?

**Comment by Alex-302** [comment]
@gork7777 
image

**Comment by jellizaveta** [comment]
@gork7777 If you want, you can open a new pr. Also you can place the rule 3-4 positions down from the comment:
```
! NOTE: Specific rules
!
```
to avoid conflicts during merge

**Comment by jellizaveta** [comment]
I've added, thanks for the suggested rule!

**Pull request closed without merging**
