### PR TITLE
jp.co.sej.app - unable to connect to PayPay

### PR DESCRIPTION
**Pull request by ghost**
There are no issues on this repository but I saw many complaints on [Twitter](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Ftwitter.com%2Fsearch%3Fq%3DAdGuard%2BPayPay%26f%3Dlive).
I don't have the premium license and haven't tested this PR with Content Blocking but it will probably fix the issue.

### CODE REVIEW

**Comment by Yuki2718** [comment]
@hirorpt 
I'll look into later, but do you have a particular reason to suspect that google-analytics is the culprit?

**Comment by hirorpt** [comment]
|Settings (Unmentioned filters are disabled.)|Result|
|------|------|
| `\|\|www.google-analytics.com^` in DNS User filter | Error|
|AdGuard DNS filter | Error|
|AdGuard DNS filter + `@@\|\|www.google-analytics.com^`  in DNS User filter | Works correctly|
|AdGuard DNS filter + Disable AdGuard protection of `jp.co.seji.app` | Works correctly|
|AdGuard DNS filter + Disable AdGuard protection of `jp.ne.paypay.android` | Error|

**Comment by Yuki2718** [comment]
@hirorpt Confirmed your fix works, but can you please move the filter to whitelist.txt? Also I think in this case `www.` can safely be trimmed down.

**Review by Alex-302 — APPROVED** [review]

**Review by Alex-302 — CHANGES_REQUESTED** [review]
Hi. Please move to Spyware whitelist.txt
Mobile Ads filter is for ads related issues:)

**Comment by Alex-302** [comment]
> I don't have the premium license

Please write to filters@adguard.com and post here part of email(to avoid spam bots on github) :)

**Comment by Yuki2718** [comment]
> Hi. Please move to Spyware whitelist.txt
> Mobile Ads filter is for ads related issues:)

Ah, my bad.

**Review by zloyden — APPROVED** [review]

**Review by Yuki2718 — APPROVED** [review]

**Comment by hirorpt** [comment]
> made the necessary changes

Thanks

@Alex-302 
> >  I don't have the premium license

> Please write to filters@adguard.com and post here part of email(to avoid spam bots on github) :)

I sent an email to `filters@adguard.com`. My email address: `[MyGithubUsername]@protonmail.com`

**Comment by Yuki2718** [comment]
(Removed potentially personal info to avoid spam)

**Comment by Alex-302** [comment]
@Yuki2718 I did not read remeved message.

**Comment by Alex-302** [comment]
@hirorpt done

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
