### PR TITLE
TrackPrara Logger: nicovideo.jp

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by piquark6046** [comment]
## TrackPara
### Examples
https://www.nicovideo.jp/watch/sm32723613?ref=search_key_video&playlist=eyJ0eXBlIjoic2VhcmNoIiwiY29udGV4dCI6eyJrZXl3b3JkIjoiXHUzMGIzXHUzMGVkXHUzMGMzXHUzMGIxIiwic29ydEtleSI6ImhvdCIsInNvcnRPcmRlciI6Im5vbmUiLCJwYWdlIjoxLCJwYWdlU2l6ZSI6MzJ9fQ&ss_pos=2&ss_id=f35ce31e-c40a-4e13-a677-9d1fa4b25577
https://www.nicovideo.jp/watch/sm38992573?ref=search_key_video&playlist=eyJ0eXBlIjoic2VhcmNoIiwiY29udGV4dCI6eyJrZXl3b3JkIjoiXHUzMGNiXHUzMGIzXHUzMGNiXHUzMGIzIiwic29ydEtleSI6ImhvdCIsInNvcnRPcmRlciI6Im5vbmUiLCJwYWdlIjoxLCJwYWdlU2l6ZSI6MzJ9fQ&ss_pos=2&ss_id=9a9c297b-9ee4-4564-99d3-3b8fb0258535

### How to reproduce
* **Using `コロッケ` query**
    1. Visit [search page](https://www.nicovideo.jp/search/%E3%82%B3%E3%83%AD%E3%83%83%E3%82%B1).
    2. Click one of these items.
    scre
* **Using `ニコニコ` query**
    1. Visit [search page](https://www.nicovideo.jp/search/%E3%83%8B%E3%82%B3%E3%83%8B%E3%82%B3?f_range=0&l_range=0&opt_md=&start=&end=)
    2. Click one of these items
    scre

**Comment by piquark6046** [comment]
## Logger
### URLs
https://www.nicovideo.jp/watch/sm38992573
https://www.nicovideo.jp/watch/sm32723613

### Logs
log
scre2

**Comment by Yuki2718** [comment]
Not much sure about `playlist` and `ss_id`.

**Comment by Yuki2718** [comment]
To clarify, I literally meant "not sure" - I didn't get any particular problem by removing them but also don't have an evidence they're strictly tracking parameter.

**Comment by Alex-302** [comment]
Seems to be ok

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
