### PR TITLE
canli2.bahislet.com #24140

### PR DESCRIPTION
**Pull request by slavaleleka**
.

### CODE REVIEW

**Review by BlazDT — CHANGES_REQUESTED** [review]
hdstreams.club###html1

To hide box in iframe.

**Comment by slavaleleka** [comment]
Cannot see any box in frame there

**Comment by Alex-302** [comment]
I don't see too.

**Review by Alex-302 — APPROVED** [review]

**Review by AdamWr — APPROVED** [review]

**Comment by Alex-302** [comment]
@BlazDT plz show that element in dev tools

**Comment by BlazDT** [comment]
A stream from them was embedded - you can see the code here:

https://hdstreams.club/live/ch6.php

For adservers:
||turngrind.com^$third-party

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
