### PR TITLE
telecinco.es

### PR DESCRIPTION
**Pull request by jellizaveta**
https://github.com/AdguardTeam/AdguardFilters/issues/138452

### CODE REVIEW

**Comment by Alex-302** [comment]
Cannot check - player is not working without AdGuard and with Spansh VPNs.

**Comment by Alex-302** [comment]
@AdguardTeam/filters-maintainers

**Review by zloyden — COMMENTED** [review]
https://github.com/AdguardTeam/AdguardFilters/pull/138491#issuecomment-1365935581 I have the same.

**Comment by BlazDT** [comment]
Same :(

**Pull request closed without merging**
