### PR TITLE
rule-maintenance - 38 

### PR DESCRIPTION
**Pull request by SKEIDs**
MobileFilter/sections/specific_web.txt
Delete duplicate rules

### CODE REVIEW

**Review by Alex-302 — APPROVED** [review]

**Comment by Alex-302** [comment]
As I said previously - this work is for sorting script.

**Comment by SKEIDs** [comment]
@Alex-302 

> As I said previously - this work is for sorting script.

I am doing this to kill time. It is annoying?

**Comment by SKEIDs** [comment]
> It takes a long time to check. I know about redundancy checker)

OK. I stop to send these PR.

**Comment by Alex-302** [comment]
Ok) The requirements for the script have already been partially completed, we are waiting for the next steps.

**Comment by SKEIDs** [comment]
> Ok) The requirements for the script have already been partially completed, we are waiting for the next steps.

I wish that script the best of luck.

**Comment by Alex-302** [comment]
I hope it will be implemented:)

**Pull request merged**
