### PR TITLE
Update adservers.txt

### PR DESCRIPTION
**Pull request by ghost**
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: code: | | https://companion.ua/wp-content/uploads/2020/11/300.gif$domain=companion.ua
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

image
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

image
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | ?
Browser:                               | ?
AdGuard version:                       | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

### CODE REVIEW

**Comment by Yuki2718** [comment]
That's syntactically wrong, `||` is for domain. Also better to use wildcard for the year/date part. So in this case
`||companion.ua/wp-content/uploads/*/300.gif`.
But AG team may want to add cosmetic filter.

**Comment by Yuki2718** [comment]
Tips for future, if you **really** need to use URL than domain, prefix with single `|` like
`|https://companion.ua`

**Comment by Talented-X-Coder-X** [comment]
Oh sorry! But companion.ua is a legit domain. Inside it has this url: https://companion.ua/wp-content/uploads/2020/11/300.gif$domain=companion.ua

**Comment by Yuki2718** [comment]
Uh, example is example, solely for illustration purpose.

**Comment by Talented-X-Coder-X** [comment]
Deleted. I opened another pull request

**Comment by Yuki2718** [comment]
FYI: you can just correct something and/or add more commits in the same branch and push again.

**Pull request closed without merging**
