### PR TITLE
Update #148552 converter.app

### PR DESCRIPTION
**Pull request by SKEIDs**
### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [x] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

### Enter the issue address

https://github.com/AdguardTeam/AdguardFilters/pull/148552
https://converter.app/png-to-jpg/result.php

### Add your comment and screenshots

 <details><summary>screenshot</summary>

</details><br/>

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Review by piquark6046 — COMMENTED** [review]
What about a regexp rule?

**Comment by SKEIDs** [comment]
> What about a regexp rule?

Sorry, I do not have knowledge to make regexp rule.
But I think `##.prime` or `##.prime > img[src^="https://ik.imagekit.io/"]` may be enough.

**Review by piquark6046 — APPROVED** [review]

**Comment by SKEIDs** [comment]
Excuse me, I think that rule is not perfect.
For example, this image on converter.app can not block.
`https://ik.imagekit.io/k1j6q2xzdte/kucoin2_ZKhmqoNYD.png?updatedAt=1681833216811`    

<details><summary>screenshot</summary>


</details><br/>

And I tried to update rule. If you can time, please check.

**Comment by piquark6046** [comment]
Please open new PR.

**Comment by SKEIDs** [comment]
OK, I will open a new one

**Pull request merged**
