### PR TITLE
TrackPara Tracking: naver.com and subdomain

### PR DESCRIPTION
**Pull request by ghost**
### Summary
There is a traceable HTTP request contains a visitor's specific activities.

### How to reproduce
- **blog.naver.com**
https://blog.naver.com/noh0058/222170342176
Click one of these items.
scre1

- **m.comic.naver.com**
https://m.comic.naver.com/webtoon/detail?titleId=734574&no=1&week=mon&listSortOrder=DESC&listPage=1#nafullscreen
When you scroll this cartoon via the progressbar, you can see these network log like the following screenshot.
scre3
log2

- **cafe.naver.com**
https://cafe.naver.com/ps3friend
scre2
1. Click the item in the blue box.
2. Click the item in the green box.
3. Then, you can see these network log like the following screenshot.
scre1

### Related PR
https://github.com/AdguardTeam/AdguardFilters/pull/69724

### CODE REVIEW

**Comment by Apious** [comment]
cc.naver.com domain be opened. you may not shown some information.
i tried before

**Comment by piquark6046** [comment]
> cc.naver.com domain be opened. you may not shown some information.
> i tried before

for example?

**Comment by Apious** [comment]
> [#89838 (comment)](https://github.com/AdguardTeam/AdguardFilters/pull/89838#issuecomment-906193570)
> 
> Did you apply `||cc.naver.com/cc$~subdocument,~document`?
> If you talk about `||cc.naver.com^` or `||cc.naver.com/cc`, It had been already fetched, and I know that they should not be used. #69724

i knew it also samsung smartphone apps same 
maybe almost korean big company as well

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/89838#issuecomment-908130981

I cannot understand your meaning.
I am talking about a tracker used `cc.naver.com` on Naver Crop.'s services.
Please give me a reproducible URL address that It is broken when my rule is applied and its details.

**Comment by Apious** [comment]
> [#89838 (comment)](https://github.com/AdguardTeam/AdguardFilters/pull/89838#issuecomment-908130981)
> 
> I cannot understand your meaning.
> I am talking about a tracker used `cc.naver.com` on Naver Crop.'s services.
> Please give me a reproducible URL address that It is broken when my rule is applied and its details.

i tried again also same
- blocked blog or cafe contents "comments". / can't see any of comment (= 댓글 )
- each unblock of each category "*.naver.com" if you're blocked for the "comment"

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/89838/commits/b25bbedb534fc33ab34f466201ee537bc8280f64 : 
https://m.blog.naver.com/PostView.naver?blogId=tjddms1646&logNo=222490708719&proxyReferer=
sdf3

**Comment by piquark6046** [comment]
Ping.

**Comment by piquark6046** [comment]
Ping,

**Review by zloyden — APPROVED** [review]

**Pull request merged**
