### PR TITLE
apprev.smt.docomo.ne.jp

### PR DESCRIPTION
**Pull request by jellizaveta**
https://github.com/AdguardTeam/AdguardFilters/issues/101737

<details><summary>Screenshot:</summary>

https://apprev.smt.docomo.ne.jp/sit_nml01/

Снимок экрана 2021-12-10 в 17 27 25

https://apprev.smt.docomo.ne.jp/quiz/

Снимок экрана 2021-12-10 в 17 27 56

Снимок экрана 2021-12-10 в 17 30 47

</details><br/>

### CODE REVIEW

**Comment by Yuki2718** [comment]
Where you found `d2-c.appli-info.com`? `apprev.smt.docomo.ne.jp##.site-promo` probably hides too much. OTOH `||apprev.smt.docomo.ne.jp/sp320_$subdocument` can be blocked.

**Comment by Yuki2718** [comment]
IMO only `.site-promo` that can safely blocked by JPF is `##.site-promo > div.site-promo`. The rest would be at best Annoyances (self-promo) although I'm not sure whether should be blocked or not.

**Comment by jellizaveta** [comment]
Hi! This rules is for elements inside iframe with source `d2-c.appli-info.com`
```
d2-c.appli-info.com###scroll_suggest
d2-c.appli-info.com##.topIconArea
d2-c.appli-info.com##.imc-ad-pr
```
Снимок экрана 2021-12-13 в 17 18 26

**Comment by Yuki2718** [comment]
> Hi! This rules is for elements inside iframe with source `d2-c.appli-info.com`

As I commented in the issue, are they worth being addressed?

**Comment by jellizaveta** [comment]
> As I commented in the issue, are they worth being addressed?

I think yes, because this blocks has "PR" label

**Comment by Yuki2718** [comment]
@Alex-302 @zloyden I'm not sure, the whole page looks ad.

**Comment by zloyden** [comment]
I'm not sure that those elements are ads. They don't lead to another site.
In fact, they are easy to navigate - you just click on one of them and you're ready to read the info about the app.

**Comment by Yuki2718** [comment]
I was not cleaer, I mean the whole page is PR contents and partial block doesn't make sense.

**Comment by zloyden** [comment]
I meant `PR` block + elements under him are the part of the article.
Ofc. If I got correctly the context of the translation of this.
```
今回は今話題＆注目の無料アプリをご紹介！ちょっと時間が空いた時にも、楽しいアプリを見つけたい時にも！全て無料なので気になるアプリをチェックして、スマホライフをレベルアップしよう！
```

**Comment by Yuki2718** [comment]
I think adding `||apprev.smt.docomo.ne.jp/sp320_$subdocument` and `apprev.smt.docomo.ne.jp##.site-promo > div.site-promo` to JPF is enough.

**Comment by zloyden** [comment]
Yep, I agree with that.

**Comment by Yuki2718** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/8590df5e2a4e0c046b31bfd4c8df26e5ad271923

**Pull request closed without merging**
