### PR TITLE
fix #42325 holcare.com

### LINKED ISSUE #42325: holcare.com
### Issue URL (Anti Adblock Script)
[https://holcare.com/x2ljX](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fholcare.com%2Fx2ljX)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.2.2946.0
Browser: | Chrome
AdGuard driver: | TDI
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Self-destructing third-party cookies (1), Block WebRTC, Block Push API, Block Location API, Block Flash, Block Java
Filters: | AdGuard Turkish,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

### PR DESCRIPTION
**Pull request by zloyden**
https://github.com/AdguardTeam/AdguardFilters/issues/42325

### CODE REVIEW

**Review by BlazDT — APPROVED** [review]

**Comment by Alex-302** [comment]
image
is it working?

**Comment by zloyden** [comment]
Yes, it worked before, but now I get the same error 404.

**Comment by Alex-302** [comment]
Ok. Close it after 1-2 days, if it does not work.

**Comment by zloyden** [comment]
The site still doesn't work - error 404.

**Pull request closed without merging**
