### PR TITLE
fix 57490 ponta.abstractpainting.work ;update3

### PR DESCRIPTION
**Pull request by Yuki2718**
https://github.com/AdguardTeam/AdguardFilters/issues/57490

### CODE REVIEW

**Comment by Alex-302** [comment]
Merge conflicts)

**Comment by Yuki2718** [comment]
Okay, add
`ponta.abstractpainting.work#%#//scriptlet('adjust-setTimeout', 'visibility', '4000')`
and remove all the others; i.e.
`ponta.abstractpainting.work#%#//scriptlet('adjust-setTimeout', '#game-screen', '4000')`
`ponta.abstractpainting.work#$#a.link-button { visibility: visible !important; }`

**Comment by Alex-302** [comment]
Thanks, done.

**Comment by Yuki2718** [comment]
@Alex-302 Sorry, missed to mention
`ponta.abstractpainting.work#$##game-start-btn > img { visibility: visible !important; opacity: 1 !important; }`
which should also be removed : (

**Comment by Alex-302** [comment]
Done. Do they bapass previous rules?

**Comment by Yuki2718** [comment]
The last scriptlet takes care of all the cases so no need for the previous rules. As far as I could find in their scripts it should not cause any false positive, but IF there was @sa-ki13 will probably make another report ;)

**Pull request closed without merging**
