### PR TITLE
fix #76337 fshost.me

### LINKED ISSUE #76337: fshost.me
### Issue URL (Anti Adblock Script)
 [https://fshost.me/free/cs16](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Ffshost.me%2Ffree%2Fcs16)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.3
Browser: | Chrome
AdGuard driver: | WFP
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> Bulgarian list, <br/>Icelandic ABP List, <br/>Dandelion Sprout's Nordic Filters, <br/>AdGuard Turkish, <br/>AdGuard French, <br/>AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Dutch

### PR DESCRIPTION
**Pull request by wout-codes**
#76337

### CODE REVIEW

**Comment by wout-codes** [comment]
@Alex-302 @AdamWr @zloyden I have no idea on what to add for content blockers and IOS. Also this issue requires an account.

**Comment by AdamWr** [comment]
I can't reproduce it.
This issue is already fixed by this rule:
`fshost.me#%#//scriptlet("set-constant", "adsbygoogle.loaded", "true")`
on my end.

**Comment by wout-codes** [comment]
> I can't reproduce it.
> This issue is already fixed by this rule:
> `fshost.me#%#//scriptlet("set-constant", "adsbygoogle.loaded", "true")`
> on my end.

I could. You gotta trust me then.

**Comment by wout-codes** [comment]
@AdamWr 
<details>

image
</details>

**Comment by AdamWr** [comment]
Does it happen if you disable EasyPrivacy?

**Comment by wout-codes** [comment]
@AdamWr  First of all, AdGuard Tracking Protection Filter isn't that rough/strong as EasyPrivacy because the trackers and analytics are remained unblocked without EasyPrivacy. 
<details>

image
</details>

**Comment by AdamWr** [comment]
I can reproduce it only if EasyPrivacy is enabled and this bait request is blocked:
`https://fshost.me/analytics.js?callback=jsonCallback`

I think that this rule is not needed:
```
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect=googlesyndication-adsbygoogle,important,domain=fshost.me
```

**Comment by wout-codes** [comment]
> `https://fshost.me/analytics.js?callback=jsonCallback`

I will remove it. It is still there vice versa. Btw, you can address the trackers and analytics, if this pull request is merged as it will dismiss the anti-adblock whether trackers blocked or unblocked.

**Comment by AdamWr** [comment]
I will add `||analytics.fsho.st/tracker.js`

**Review by AdamWr — APPROVED** [review]

**Comment by AdamWr** [comment]
Thank you.

**Comment by AdamWr** [comment]
>`/tracker.js`

I'm not sure if it's safe to add, some websites might be broken, so I prefer to add more specific rules.

**Pull request merged**
