### PR TITLE
bs.benefit-one.co.jp

### LINKED ISSUE #116632: bs.benefit-one.co.jp
### Issue URL (Annoyance)
 [https://bs.benefit-one.co.jp/bs/pages/bs/top/top.faces](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fbs.benefit-one.co.jp%2Fbs%2Fpages%2Fbs%2Ftop%2Ftop.faces)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v4.0.141
Browser: | Chrome
Stealth mode: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>AdGuard Chinese, <br/>AdGuard Japanese

### PR DESCRIPTION
**Pull request by SKEIDs**
Fix #116632 
URL: https://bs.benefit-one.co.jp/bs/pages/bs/top/top.faces
account required to reproduce this popup.

<details><summary>screenshot</summary>

</details><br/>

### CODE REVIEW

**Review by zloyden — COMMENTED** [review]
> account required to reproduce this popup

Could you also provide it?

**Comment by SKEIDs** [comment]
I cannot provide my account. sorry.

**Comment by zloyden** [comment]
At least you can send it to filters@adguard.com.
Tell me if there is a problem with scrolling the page when the popup is blocked?

**Comment by SKEIDs** [comment]
> At least you can send it to [filters@adguard.com](mailto:filters@adguard.com).

It is my account ID and password that I provide to you? Or is it the HTML source?

> Tell me if there is a problem with scrolling the page when the popup is blocked?

There is no problem with the website.

**Review by zloyden — APPROVED** [review]

**Comment by zloyden** [comment]
> There is no problem with the website.

Well, it's good. Account is not needed for now.
> It is my account ID and password that I provide to you? Or is it the HTML source?

It depends on you, but It's better to provide login and password for the next time.
Just send it to the email above safely if the issue needs it.

**Comment by SKEIDs** [comment]
> > There is no problem with the website.
> 
> Well, it's good. Account is not needed for now.
> 
> > It is my account ID and password that I provide to you? Or is it the HTML source?
> 
> It depends on you, but It's better to provide login and password for the next time. Just send it to the email above safely if the issue needs it.

Okay,I see.

**Pull request merged**
