### PR TITLE
fix #71514 dztechphone.com

### LINKED ISSUE #71514: dztechphone.com
### Issue URL (Incorrect Blocking)
 [https://dztechphone.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdztechphone.com%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>
<details>
  <summary>Screenshot 2</summary>

  Screenshot 2
</details>
<details>
  <summary>Screenshot 3</summary>

  Screenshot 3
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.31
Browser: | Edge
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Strip URLs from tracking parameters, <br/>Self-destructing third-party cookies (2880), <br/>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Adblock Warning Removal List, <br/>I don't care about cookies, <br/>EasyList Cookie List<br/><br/><b>Security:</b><br/> Online Malicious URL Blocklist
Other extensions used: | I only have adguard

### PR DESCRIPTION
**Pull request by Yuki2718**
https://github.com/AdguardTeam/AdguardFilters/issues/71514

### CODE REVIEW

**Comment by Talented-X-Coder-X** [comment]
Hi,
Can I have your Email? I wanna learn something from you. Thanks

**Comment by BlazDT** [comment]
Did not see your PR, added rules already.

**Comment by Yuki2718** [comment]
> Did not see your PR, added rules already.

Okay, um, I should have added to foreign.txt as it's Arabic and the rule is not a common one. HNY!

**Comment by BlazDT** [comment]
Yep, correct.

**Pull request closed without merging**
