### PR TITLE
Bilibili (bilibili.com) URL tracking parameter

### PR DESCRIPTION
**Pull request by dingwen07**
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[Bilibili](https://www.bilibili.com/) (a Chinese Niconico-like video website) have multiple tracking parameters:
 - `from` tracking
 - `seid` possibly come with searching
 - `share_source` when sharing from PC website
 - `spm_id_from` added by JavaScript of the website
 - `from_source` when searching
 - `share_medium` (and follows) when sharing from Bilibili mobile application
 - `share_plat`
 - `share_session_id`
 - `share_source`
 - `share_tag`
 - `timestamp`
 - `unique_k`

<details><summary>Screenshot:</summary>

img1
img2

</details><br/>

* **Expected behaviour**: 

Tracking parameters are removed

### CODE REVIEW

**Comment by yingziwu** [comment]
image

The trace parameter also has `from_spm_id`.

```
||*.bilibili.com^$removeparam=from_spm_id
```

**Comment by dingwen07** [comment]
> image
> 
> The trace parameter also has `from_spm_id`.
> 
> ```
> ||*.bilibili.com^$removeparam=from_spm_id
> ```

Updated.

**Review by Yuki2718 — CHANGES_REQUESTED** [review]
`||*.bilibili.com^` is wrong syntax making domain anchor `||` useless. Change to `||bilibili.com^` covering all its subdomain.

**Comment by dingwen07** [comment]
> `||*.bilibili.com^` is wrong syntax making domain anchor `||` useless. Change to `||bilibili.com^` covering all its subdomain.

I have corrected these rules.

**Review by Yuki2718 — APPROVED** [review]

**Comment by Yuki2718** [comment]
Thank you for your contribution, please wait for review of the official team.

**Review by zloyden — APPROVED** [review]

**Pull request merged**
