### PR TITLE
oload.party whitelist specific 2 filter

### PR DESCRIPTION
**Pull request by Niush**
oload.party whitelist specific 2 filter for Base Filter to work properly

[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

image
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

image

</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | ?
Browser:                               | Chrome 78.0.3904.108
AdGuard version:                       | 3.3.4
Filters enabled:                       | AdGuard Base Filter
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

### CODE REVIEW

**Comment by Alex-302** [comment]
Hi. Please provide sample  link.
Also, instead of exclusion better remove domain from original blocking rule.

**Comment by Niush** [comment]
Removed filters instead of exclusion

Sample link [https://pixat.ml/](https://pixat.ml/) after playing a video, if Base Filter is active overlay is present which goes away if filter is removed. Allowing Play button to be clickable.

**Comment by AdamWr** [comment]
I think that direct link will be better:
https://oload.party/loadsource.php?server=12&id=3593673&token=xHQlhemxrX8AZY2QFgdw9i7O7zauDYT3OO8Gery/tXeDIL5B2ROsMvNowNYz11mwsEixmT74vZIAc5wAyASxtettWt1Vh6r7VpMIar/nwBs0cgOxKFdKvO5YokdBbN2KRTejnTIQoMFaIU3TTVpmrrZ/nN+svNJJWuQM6di+rllyccJyz/6+nQXJg9g75zAou0HUcgue7iROUls7q92S1w==

I get a popup/popunder (on first visit) if these rules are disabled.

What about just hidding this overlay?
For example:
```
oload.party##body > div[style^="z-index: 999"][style*="position: absolute;"]
mixdrop.co##div[style^="position:absolute;"][style*="z-index:"][onclick]
```

**Comment by Alex-302** [comment]
> What about just hidding this overlay?

as I remember(few years ago:) ), it can break player on iOS.

**Comment by AdamWr** [comment]
As I recall it was on websites which was using `propellerads` script (`zfgloaded`), this script is different.
Anyway, if it's a problem on iOS, we can add hints, I think.
```
!+ NOT_PLATFORM(ios, ext_android_cb)
oload.party##body > div[style^="z-index: 999"][style*="position: absolute;"]
mixdrop.co##div[style^="position:absolute;"][style*="z-index:"][onclick]
```
or add:
`oload.party#%#//scriptlet("abort-current-inline-script", "decodeURI", "4zz.")`
seems to works fine too.

**Comment by Alex-302** [comment]
Better check on iOS)

**Comment by AdamWr** [comment]
It seems that at the moment this video doesn't work on iOS.
After adding these rules video works.
There are also popups with and without these rules, but I guess it can't be fixed on iOS.

**Comment by Niush** [comment]
I don't really know much about advanced filters. I would appreciate any working solutions, if you can.

**Comment by AdamWr** [comment]
@Niush  Could you please check if it work on your side if you add these rules to user filter?
```
oload.party##body > div[style^="z-index: 999"][style*="position: absolute;"]
mixdrop.co##div[style^="position:absolute;"][style*="z-index:"][onclick]
```
or instead of first rule, this:
`oload.party#%#//scriptlet("abort-current-inline-script", "decodeURI", "4zz.")`

**Comment by Niush** [comment]
@AdamWr 

oload.party##body > div[style^="z-index: 999"][style*="position: absolute;"]
mixdrop.co##div[style^="position:absolute;"][style*="z-index:"][onclick]

this seems to be working...

Can you also explain what does the scriptlet thing does?

_Sent from my Desire 830 dual sim using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AdamWr** [comment]
This scriptlet should abort one of the inline script, which seems to be related to popups.
<details><summary>Screenshot</summary>

image

</details>

There is more about scriptlets - https://github.com/AdguardTeam/Scriptlets
https://github.com/AdguardTeam/Scriptlets#abort-current-inline-script

**Comment by AdamWr** [comment]
OK, I removed this rule:
```
oload.party#%#(function(){var c=document.addEventListener;document.addEventListener=function(a,b,d,e){"mousedown"!=a&&-1==b.toString().indexOf('Z4P')&&c(a,b,d,e)}.bind(document); var b=window.setTimeout;window.setTimeout=function(a,c){if(!/\..4P\(|=setTimeout\(/.test(a.toString()))return b(a,c)};})(); 
```
and added these:
```
oload.party#%#//scriptlet("abort-current-inline-script", "decodeURI", "4zz.")
oload.party##body > div[style^="z-index: 999"][style*="position: absolute;"]
mixdrop.co##div[style^="position:absolute;"][style*="z-index:"][onclick]
```
it should be okay.
Update should be available in 1-2 hours.

Thank you for your reply.

**Pull request closed without merging**
