### PR TITLE
fix #72436 rtl.de

### LINKED ISSUE #72436: rtl.de
### Issue URL (Annoyance)
 [https://www.rtl.de/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.rtl.de%2F)
### Comment
Username: @Morku
> Cookie Pop-up
> --
> Die folgenden Informationen werden automatisch generiert. Bitte löschen Sie sie nicht.
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.3
Browser: | Firefox
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Remove X-Client-Data header from HTTP requests, <br/>Strip URLs from tracking parameters
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Russian, <br/>AdGuard German

### PR DESCRIPTION
**Pull request by stanislav-atr**
#72436

### CODE REVIEW

**Comment by BlazDT** [comment]
Did you check for articles with embedded social streams or embedded videos?

**Comment by stanislav-atr** [comment]
> Did you check for articles with embedded social streams or embedded videos?

@BlazDT, yeah, articles are clean on my side, only video teasers related to articles are present.

**Comment by Alex-302** [comment]
@stanislav-atr Is everything ok with German IP?

**Comment by stanislav-atr** [comment]
> @stanislav-atr Is everything ok with German IP?

@Alex-302, i only see cookie notice with any IP.

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
