### PR TITLE
fix inoreader block, and consolidate rules

### PR DESCRIPTION
**Pull request by kaznovac**
added:
inoreader.com###reader_pane:style(padding-right: 0px !important;)
inoreader.com###sinner_container

removed:
inoreader.com###splitter > div#sinner_container [superseded]

### CODE REVIEW

**Comment by Alex-302** [comment]
Hi. 
Consolidation is not required.
Why do we need `inoreader.com###reader_pane:style(padding-right: 0px !important;)`?

**Comment by kaznovac** [comment]
@Alex-302 to expand the reading area, otherwise the ad section is hidden but the whitespace remains

**Comment by Alex-302** [comment]
I need the sample url or saved page.

**Comment by kaznovac** [comment]
url: https://www.inoreader.com

you'll have to create free account, login and subscribe to few rss sources

**Comment by Alex-302** [comment]
image

**Comment by ameshkov** [comment]
@Alex-302 might be ublock-specific issue?

**Pull request closed without merging**
