### PR TITLE
Fix #188920 footybite.to

### LINKED ISSUE #188920: www.footybite.to
### Issue URL (Ads)
 [https://www.footybite.to/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.footybite.to%2F)

### Screenshots
<details>
  <summary>Screenshot 1 </summary>

  Screenshot 1
</details>

### System configuration

Information | Value
--- | ---
AdGuard product: | AdGuard Browser Extension v4.4.22
System version: | Windows 10
Browser: | Chrome
Tracking protection: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances
Browsing Security: | disabled
Browsing Security statistics: | disabled

### PR DESCRIPTION
**Pull request by Alex-302**
Sample link of this ad system
https://regex101.com/r/WLk5IZ/1

### CODE REVIEW

**Review by zloyden — APPROVED** [review]

**Review by AdamWr — APPROVED** [review]

**Comment by Yuki2718** [comment]
Wait, we should have an rule for them? Looks needs improvement though.

**Comment by Alex-302** [comment]
@Yuki2718 Yes, also works - changed `\d{4,5}` to `[0-9A-Za-z]{4,5}`
`^https?:\/\/(?:[a-z]{2}\.)?[0-9a-z]{5,16}\.[a-z]{3,7}\/[a-z](?=[a-z]{0,25}[0-9A-Z])[0-9a-zA-Z]{3,26}\/[0-9A-Za-z]{4,5}(?:\?[_v]=\d+)?$`
Ok?

**Comment by Yuki2718** [comment]
> Ok?

I meant having two rules may be waste, though the original one also has `$subdocument` etc.

**Comment by Alex-302** [comment]
I meant I modified existing rule, mentioned in https://github.com/AdguardTeam/AdguardFilters/pull/188977#issuecomment-2355625983

>  the first character after .com/ is always r

No, please check URLs in https://regex101.com/r/WLk5IZ/1

**Comment by Yuki2718** [comment]
> No, please check URLs in

I said
> ending with alphabets

Those ending with digits may use `p` or `t`.

**Comment by Yuki2718** [comment]
> I meant I modified existing rule, mentioned in [#188977 (comment)](https://github.com/AdguardTeam/AdguardFilters/pull/188977#issuecomment-2355625983)

Hmm..? Can't find the change.

**Comment by Yuki2718** [comment]
Anyway, these ending with digits are already covered, no additional rule is required: https://regex101.com/r/OTdzAy/1 So either modify this rule, or if you're to add a new one, it should focus only on the pattern ending with alphabets.

**Comment by Alex-302** [comment]
Ok, removed matching the digits at the end. And moved near the similar rules.

**Review by Yuki2718 — APPROVED** [review]

**Review by zloyden — APPROVED** [review]

**Pull request merged**
