### PR TITLE
www.buzzfeednews.com

### PR DESCRIPTION
**Pull request by gork7777**
issue: #110942

### CODE REVIEW

**Review by Yuki2718 — CHANGES_REQUESTED** [review]
Hmm, I don't see the popup. Can you add `||buzzfeednews.com^$removeparam=ref` to Trackparam?

**Comment by gork7777** [comment]
Which popup you didn't see?

**Comment by Yuki2718** [comment]
> Which popup you didn't see?

"News moves fast" staff, so is this not popup?

**Comment by gork7777** [comment]
@Yuki2718 It's not a popup, its subscription and I can reproduce, `##.newsblock-newsletter-signup`

**Review by Yuki2718 — APPROVED** [review]

**Review by zloyden — APPROVED** [review]

**Pull request merged**
