### PR TITLE
hf.saokouryaku.com

### PR DESCRIPTION
**Pull request by SKEIDs**
https://github.com/AdguardTeam/AdguardFilters/issues/103027

### CODE REVIEW

**Review by gork7777 — CHANGES_REQUESTED** [review]
`hf.saokouryaku.com##[class*="ads"]` is shorter and better I guess.
Last rule is fine.

**Comment by SKEIDs** [comment]
> `hf.saokouryaku.com##[class*="ads"]` is shorter and better I guess. Last rule is fine.

That rule is smart. Thank you.

**Comment by Yuki2718** [comment]
A matter of preferece but I don't like `##[class*="ads"]`, not very safe in my experience tho may be safe on this site. At least specify tag so that `##div[class*="ads"]` unless you see different tags.

**Review by Yuki2718 — CHANGES_REQUESTED** [review]
Please change hange `##div[style="text-align:center; font-size:11px;"]` to `##div[style="text-align:center; font-size:11px;"] > span` to minimize likelihood of false positive. Also add tag to the first rule.

**Comment by SKEIDs** [comment]
> Please change hange `##div[style="text-align:center; font-size:11px;"]` to `##div[style="text-align:center; font-size:11px;"] > span` to minimize likelihood of false positive. Also add tag to the first rule.

Ok,I changed it.

**Comment by Yuki2718** [comment]
I mean `hf.saokouryaku.com##div[class*="ads"]`. BTW additional `h` is somehow inserted at the top of the domain.

**Comment by SKEIDs** [comment]
> 

done

**Review by Yuki2718 — APPROVED** [review]

**Comment by urvbcn88** [comment]
> `hf.saokouryaku.com##[class*="ads"]` is shorter and better I guess. Last rule is fine.

O really?
So, you decide how to fix reports anymore? If you're not a developer, don't interfere with user reports. This platform is for developers/programmer, is no child's play.
Leave that to professionals.

**Review by zloyden — APPROVED** [review]

**Pull request merged**
