### PR TITLE
store.united-arrows.co.jp

### LINKED ISSUE #108526: store.united-arrows.co.jp
### Issue URL (Incorrect Blocking)
 [https://store.united-arrows.co.jp/sp/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fstore.united-arrows.co.jp%2Fsp%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>
<details>
  <summary>Screenshot 2</summary>

  Screenshot 2
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.3.2
Browser: | Safari
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Other:</b><br/>AdGuard Experimental<br/><br/><b>Language-specific:</b><br/>AdGuard Japanese, <br/>AdGuard Chinese

### PR DESCRIPTION
**Pull request by SKEIDs**
Fix #108526

### CODE REVIEW

**Comment by Yuki2718** [comment]
I don't see unblocked share buttons on Android, may be iOS-specific. @Sergey-Lyapin Plz take a look. (The 1st screenshot seems to be just lazy load and thus no issue.)

**Comment by SKEIDs** [comment]
> I don't see unblocked share buttons on Android, may be iOS-specific. @Sergey-Lyapin Plz take a look. (The 1st screenshot seems to be just lazy load and thus no issue.)

That element is here. I am sorry I forgot to tell.
URL: https://store.united-arrows.co.jp/shop/glr/styling/20220222_402392.html
<details><summary>screenshot</summary>


</details><br/>

**Comment by Yuki2718** [comment]
I still don't see, tested on real device too. Wait for @Sergey-Lyapin 's review.

**Comment by Sergey-Lyapin** [comment]
I was not able to reproduce this share element on 2 different iPhones

**Comment by Sergey-Lyapin** [comment]
Ok, I've reproduced it on a desktop.

**Comment by Yuki2718** [comment]
Oh, somehow I assumed it's on mobile, sorry.

**Comment by Sergey-Lyapin** [comment]
Me too at first, the reports were from iOS)

**Pull request merged**
