### PR TITLE
update #76928 ustream.to

### PR DESCRIPTION
**Pull request by wout-codes**
#76928

### CODE REVIEW

**Review by zloyden — APPROVED** [review]

**Comment by wout-codes** [comment]
@zloyden Can you please check? I am busy with something else. Seems like the domain has changed it's scripts. Anti-AdBlock is back. Isn't it possible to use `$$` rule to kill it?

**Comment by wout-codes** [comment]
@AdamWr Can you please check too? Possible fix: `ustream.to$$script[tag-content="adblock"][min-length="500"][max-length="2500"]`

**Comment by AdamWr** [comment]
It seems that at the moment website is broken and show this message even if ad blocker is disabled.

<details><summary>Screenshot</summary>

image

</details>

>`ustream.to$$script[tag-content="adblock"][min-length="500"][max-length="2500"]`

On my end it causes that stream doesn't load at all (on `ustream.to`).

**Comment by wout-codes** [comment]
> It seems that at the moment website is broken and show this message even if ad blocker is disabled.
> 
> Screenshot
> > `ustream.to$$script[tag-content="adblock"][min-length="500"][max-length="2500"]`
> 
> On my end it causes that stream doesn't load at all (on `ustream.to`).

Broken detection. Same the stream doesn't load, but it will load

**Comment by AdamWr** [comment]
This rule works on my end:
`beef1999.blogspot.com#%#//scriptlet("set-constant", "use_adebloker", "0")`

**Comment by wout-codes** [comment]
@AdamWr Doesn't this work for you? Works on my end. `beef1999.blogspot.com#%#//scriptlet("prevent-eval-if", "use_adebloker")`

**Comment by AdamWr** [comment]
It works too.

**Comment by wout-codes** [comment]
Yay. You decide on whether which one to add or add both.

**Comment by AdamWr** [comment]
Done - https://github.com/AdguardTeam/AdguardFilters/commit/0db78b355f00484f7fab2ff373eaf5d6c79709f1

**Comment by wout-codes** [comment]
@AdamWr Hi. Can you add this rule directly? They changed their script, so AdGuard gets detected again. 
This works on my end:
`||revenuenetworkcpm.com$redirect=noopjs,important,domain=beef1999.blogspot.com|ustream.to`

**Comment by AdamWr** [comment]
Hi,
Okay, added - https://github.com/AdguardTeam/AdguardFilters/commit/0748684cc473894c0a3fb3f23e8f93dc3d8437a4

**Pull request merged**
