### PR TITLE
Update #53079 coron.tech

### PR DESCRIPTION
**Pull request by Yuki2718**
The current solution works but no need to allow ad scripts on platforms supporting scriptlet. Plus some cosmetic staff. Of note, somehow now I don't see antiadb on `https://coron.tech/` even without solution but anti-adb scripts is still there so added scriptlet worked months ago (and should still work) just in case. `http://connect.coron.tech/` has a working anti-adb tho.

### CODE REVIEW

**Review by AdamWr — APPROVED** [review]

**Comment by Sergey-Lyapin** [comment]
@AdamWr 
Hi) Do you see antiadblock on this site? I can't reproduce

**Comment by AdamWr** [comment]
Hi:)
Yes, I do. On `http://connect.coron.tech/`

**Comment by Yuki2718** [comment]
@Sergey-Lyapin As noted, no anti-adb on `https://coron.tech/` but I got few months ago and the script is still sitting there.

**Review by Sergey-Lyapin — APPROVED** [review]

**Comment by Yuki2718** [comment]
Thx!

**Pull request merged**
