### PR TITLE
fix #56261 chip.com.tr

### LINKED ISSUE #56261: chip.com.tr
### Issue URL (Incorrect Blocking)
 [https://www.chip.com.tr/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.chip.com.tr%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>
<details>
  <summary>Screenshot 2</summary>

  Screenshot 2
</details>

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 3.4.31
Browser: | Chrome
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (1440), Block WebRTC, Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Security:</b><br/> NoCoin Filter List<br/><br/><b>Language-specific:</b><br/> AdGuard Turkish

### PR DESCRIPTION
**Pull request by Sergey-Lyapin**
#56261

### CODE REVIEW

**Comment by AdamWr** [comment]
I thought that this element is already blocked by this rule - `||amazonaws.com/Gravity/doganfooter.js` from Turkish filter. Isn't it?

**Comment by Sergey-Lyapin** [comment]
> I thought that this element is already blocked by this rule - `||amazonaws.com/Gravity/doganfooter.js` from Turkish filter. Isn't it?

It is visible in Safari with extension and iOS, this script loads even if I add the rule in user filter, strange.
P.S. this rule exists in optimized filters.

**Comment by AdamWr** [comment]
What about something like:
`||storagemw.s*.amazonaws.com/Gravity/doganfooter.js`

**Comment by Sergey-Lyapin** [comment]
> What about something like:
> `||storagemw.s*.amazonaws.com/Gravity/doganfooter.js`

This rule works, thank you, I'll change the original rule. So what is the difference? For iOS&Safari we should add basic rules with subdomains?

**Review by AdamWr — APPROVED** [review]

**Comment by AdamWr** [comment]
From what I found:
>`||` on Safari matches only one level of subdomains
`||example.org` matches `test.example.org`, but it does not match `another.test.example.org`

So in case like that, we should add rules with subdomains for iOS and Safari.

**Comment by Sergey-Lyapin** [comment]
Thanks

**Pull request merged**
