### PR TITLE
Update foreign.txt

### PR DESCRIPTION
**Pull request by diomed**

### CODE REVIEW

**Comment by Alex-302** [comment]
I need explanations for the rules/

**Comment by diomed** [comment]
What explanation do you need?
These are all ad service domains, and last one is a government site 
that asks of people to open modal for login, so it has to be allowed.

**Comment by Alex-302** [comment]
contacts-store.com is not working.
Please add `^$third-party` to domain blocking rules and comment to the last rule, why it must be completely excluded.

**Review by Alex-302 — CHANGES_REQUESTED** [review]
contacts-store.com is not working.
Please add ^$third-party to domain blocking rules and comment to the last rule, why it must be completely excluded.

**Comment by diomed** [comment]
I don't understand last part of your sentence. What comment should I add, and how is it completely excluded? I basically want that modal to open up. Can you please edit file instead of me?

**Comment by Alex-302** [comment]
> What comment should I add,

we always add comments for exclusion rules with the reason of excluding.
As I see, nothing is broken on this site.

**Review by Alex-302 — APPROVED** [review]

**Comment by Alex-302** [comment]
thanks, merged

**Pull request merged**
