### PR TITLE
Move to correct place with improvement

### PR DESCRIPTION
**Pull request by Yuki2718**
This filter catches a specific cluster of revolving adservers and complements `/ntfc.php?$script` in Base, I don't know why it's in Annoyance. There are some variants in `tag.min.js?z=` so I removed the part and instead limited scope to 3p script.

An example: `https://publicwww.com/websites/%22propu.sh%22/`

### CODE REVIEW

**Comment by Alex-302** [comment]
But `/pfe/current/` used by push notifications, also `||propu.sh^` exists in Easylist.

**Comment by Yuki2718** [comment]
If fact 99% of `/pfe/current/` servers are included in EasyList, but the sense of revolving servers is that they change every day and EL can miss some.

**Comment by Alex-302** [comment]
> /pfe/current/

all these are related to propu.sh? If "yes" - better add with a short comment

**Comment by Yuki2718** [comment]
> 
> all these are related to propu.sh? If "yes" - better add with a short comment

Rather hundreds of such domain but yes, okay.

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
