### PR TITLE
Made the ad report template less incomprehensible for newcomers to fill out

### PR DESCRIPTION
**Pull request by DandelionSprout**
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

I've noticed over the past 3 years that people who are new to AdGuard's GitHub repos, are usually rather confused about which lines in this very template to replace, or where (despite the `[//]` tags). So I decided to add better title headers and at least somewhat more clear guidelines.

It would've probably been even better to just as well convert the whole template to the new `.yml` form format, but I wasn't sure how to convert the system config information table in a way that wouldn't make it ≥1500px tall.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

image
</details><br/>

* **Expected behaviour**: 

Laymen end-users, and even industry experts, are able to correctly use this repo's GitHub report system. Though to be frank, I presume roughly 75% of them will completely ignore the template anyway, sadly.

<details><summary>Screenshot:</summary>

image
</details><br/>

***Steps to reproduce the problem***:

N/A

***System configuration***

**Filters:**

N/A

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | 21H1 x64
Browser:                               | Chrome 92.0.4515.107 x64
AdGuard version:                       | N/A
Filters enabled:                       | N/A
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

### CODE REVIEW

**Comment by peace2000** [comment]
I felt that report template was bit confusing too...

**Comment by Alex-302** [comment]
Current template is ok.

> Though to be frank, I presume roughly 75% of them will completely ignore the template anyway, sadly.

The most reports made using reporting tool, and most of them are correct.

**Comment by peace2000** [comment]
I made a report yesterday by using reporting tool because I felt it was a bit less complicated option than issue report.

**Comment by Alex-302** [comment]
AdGuard sends all necessary info to reporting tool automatically. In general user must select problem type, copypaste URL and screenshot only.

**Pull request closed without merging**
