### PR TITLE
heise.de

### PR DESCRIPTION
**Pull request by Volker-Weissmann**
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
Removes a cookie consent banner on heise.de

* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

image

</details><br/>

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

image
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

Go to heise.de

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

adguard-annoyance, user-filters, ublock-filters: 30741-27,  ublock-badware, ublock-privacy, ublock-abuse, ublock-unbreak, easylist, easyprivacy, urlhaus-1,  plowe-0

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      |  Arch Linux
Operating system version (Android/iOS) | 10.02.21
Browser:                               |  Firefox 97.0
AdGuard version:                       | UBlock Origin 1.41.2 
Filters enabled:                       | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

### CODE REVIEW

**Comment by Alex-302** [comment]
Cannot reproduce. @BlazDT Please take a look.

**Comment by BlazDT** [comment]
Not reproduced. Blocking url hides it, but then social embeds/videos are not working.

**Comment by Volker-Weissmann** [comment]
> Not reproduced. Blocking url hides it, but then social embeds/videos are not working.

Are you aware of any blocklist that prioritizes blocking gdpr-banners over working social embeds/videos?

**Comment by BlazDT** [comment]
Nope.

**Pull request closed without merging**
