### PR TITLE
Preparing to add Ukrainian filter

### PR DESCRIPTION
**Pull request by Alex-302**
https://github.com/AdguardTeam/FiltersRegistry/issues/735

### CODE REVIEW

**Review by zloyden — APPROVED** [review]

**Review by AdamWr — APPROVED** [review]

**Review by BlazDT — APPROVED** [review]

**Review by jellizaveta — APPROVED** [review]

**Review by Sergey-Lyapin — APPROVED** [review]

**Review by piquark6046 — APPROVED** [review]

**Review by ameshkov — COMMENTED** [review]
Generally, all good, but since this is a Cyrillic filters category, we should add Belorussian, Kazakh and Bulgarian sections here as well.

**Comment by Sergey-Lyapin** [comment]
Also Kyrgyz, Tajik, Uzbek, Mongolian, Macedonian, Serbian

**Comment by Alex-302** [comment]
@Sergey-Lyapin 

> Also Kyrgyz, Tajik, Uzbek, Mongolian, Macedonian, Serbia

maybe next time)

**Review by ameshkov — APPROVED** [review]

**Comment by ameshkov** [comment]
> Also Kyrgyz, Tajik, Uzbek, Mongolian, Macedonian, Serbian 🙂

There's already a Serbian filter, also they seem to have switched to latin alphabet:)
Regarding the Stans, if there are many rules for their websites, we should definitely consider that.

**Review by ameshkov — APPROVED** [review]

**Comment by ameshkov** [comment]
Hmm, we may need to add Tajik language tag to PersianBlocker then?

**Comment by DeepSpaceHarbor** [comment]
👋 My project looks inactive because I haven't noticed broken filters in my daily web browsing. I'm using the list myself and I'm more than happy to assist others with fixing/adding other filters to it.

**Comment by ameshkov** [comment]
@Alex-302 @zloyden 

https://github.com/AdguardTeam/AdguardFilters/pull/144318#issuecomment-1451721914
Seem to be a great pick for both FiltersRegistry and https://github.com/AdguardTeam/HostlistsRegistry

**Comment by DandelionSprout** [comment]
*Macedonian Pi-hole Blocklist* has already [been in AdGuard Home for some years now](https://github.com/AdguardTeam/HostlistsRegistry/tree/main/filters/regional/filter_20_MKD_MacedonianPiHoleBlocklist).

I approve of the prospect of adding *Macedonian Adblock Filters* to FiltersRegistry, as it is currently isn't in either repo.

**Comment by DandelionSprout** [comment]
>Seem to be a great pick for both FiltersRegistry (…)

Turns out that https://raw.githubusercontent.com/DeepSpaceHarbor/Macedonian-adBlock-Filters/master/Filters has indeed been proposed for inclusion in AdGuard for several years, but was rejected in https://github.com/AdguardTeam/FiltersRegistry/issues/354 for supposedly not being updated often enough. I wouldn't mind having that list be looked into for inclusion again.

**Comment by DandelionSprout** [comment]
When/if the Ukrainian and/or Cyrillic filters go live on Adtidy, feel free to give me a headsup about it, and I can wait with (or come up with) any of my remaining ideas until then.

**Comment by DandelionSprout** [comment]
Since https://github.com/AdguardTeam/AdguardFilters/tree/master/CyrillicFilters/Kazakh/sections had an existing designated folder, I took a look into which `.kz` domains in https://github.com/AdguardTeam/AdguardFilters/blob/master/CyrillicFilters/RussianFilter/sections/specific.txt that were Kazakh-language only.

The answer seemingly turned out to be 0, potentially causing obstacles for that folder.

**Comment by krystian3w** [comment]
I heard that Moldovan uses Cyrillic (Romanian is written in a different alphabet).


Maybe there are websites with 100k visitors who use this alphabet.

**Comment by braverug** [comment]
Moldova's official language has been Romanian (which uses the Latin alphabet) since 1989. The only region that currently uses Moldovan + Cyrillic is Transnistria, so there are not many websites that specifically use Moldovan Cyrillic. Moldovan websites (.md) primarily use Romanian and Russian.

Side note: Why wasn't the "foreign-cyrillic.txt" file merged into main?

**Pull request merged**
