### PR TITLE
fix #76203 vexfile.com

### LINKED ISSUE #76203: vexfile.com
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: green fake buttons and crap requests from different domains
`https://vexfile.com/download/e9uz7cJXWt/7848f`

* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

109434116-f4811680-7a13-11eb-936f-a7d10784bc5a

</details><br/>

[//]: # (Substitute this line with a description of the problem)

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.31
Filters enabled:                       | Default + Adguard tracking protection + Adguard annoyances + Adguard germany + phishing and malware protection enabled
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

### PR DESCRIPTION
**Pull request by wout-codes**
#76203

### CODE REVIEW

**Comment by Alex-302** [comment]
Please don't create new PRs untill current are not closed.

**Comment by wout-codes** [comment]
> Please don't create new PRs untill current are not processed.

Ok.

**Review by Alex-302 — APPROVED** [review]

**Comment by Alex-302** [comment]
Also we block push notifications(except some sites, where they are useful. For example messengers and email services) https://github.com/AdguardTeam/AdguardFilters/commit/6a2d2fa08fac210ae7d30655a80a09aac646b311

**Comment by wout-codes** [comment]
Okay. Next time I will fix that too.

**Pull request merged**
