### PR TITLE
bursahakimiyet.com.tr-problematic rule deleted

### LINKED ISSUE #118180: www.bursahakimiyet.com.tr
### Issue URL (Ads)
 [https://www.bursahakimiyet.com.tr/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.bursahakimiyet.com.tr%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v4.0.163
Browser: | Chrome
Stealth mode options: | Send Do-Not-Track header, <br>Strip URLs from tracking parameters
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Turkish

### PR DESCRIPTION
**Pull request by ghost**
### Please include a summary of the change and which issue is fixed.

Problematic rule deleted

Closes #118180 

---

##### To avoid invalid pull requests, please check and confirm following checkboxes:

        
  - [ ] This is not an ad/bug report;
  - [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
  - [x] I have performed a self-review of my own changes;
  - [x] My changes do not break web sites, apps and files structure.

##### If the problem does not fall under any category that is listed here, please contact our tech support: `support@adguard.com`

  - [ ] Missed ads or ad leftovers;
  - [x] Website or app doesn't work properly;
  - [ ] AdGuard gets detected on a website;
  - [ ] Missed analytics or tracker;
  - [ ] Social media buttons — share, like, tweet, etc;
  - [ ] Annoyances — pop-ups, cookie warnings, etc.
  
##### Enter the issue address:

Closes https://github.com/AdguardTeam/AdguardFilters/issues/118180

##### If possible, a screenshot of a page or application should not be cropped too much. Otherwise, it is not always clear where the element is located.

**0.** **DO NOT** upload screenshots with sexually explicit material on GitHub directly. Instead, upload it to a third-party image hosting and post the link to it without preview (!) here. Also, mention if the link leads to NSFW content;

**1.** Add screenshots of the problem. You can drag and drop images or paste them from clipboard;

Use `<details> </details>` tag to hide screenshots under the spoiler; 

**2.** Describe the issue in detail until it is absolutely clear from the screenshot what the problem is;

You can also indicate any other information that you think the developers should know.

**Warning:** Please remove personal information before uploading screenshots!

**1.** `Write a comment here`

**2.** Screenshots

<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Terms

  - [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met.

### CODE REVIEW

**Comment by dcxstq2** [comment]
@AdamWr 
Please check this patch.

**Comment by AdamWr** [comment]
If this script is not blocked then ads are loaded.
What about adding:
```
||bursahakimiyet.com.tr/get-ad
```
it should block ads and website shouldn't be broken.

This rule:
```
bursahakimiyet.com.tr#%#//scriptlet("set-constant", "getAd", "noopFunc")
```
also should fix broken website, but I think it's not necessary if blocking `bursahakimiyet.com.tr/get-ad` works fine.

**Review by zloyden — COMMENTED** [review]
@AdamWr it seems your rule `||bursahakimiyet.com.tr/get-ad` is ok.

**Comment by dcxstq2** [comment]
@AdamWr 
When I remove the `/ad_getter.js` rule, I can't see ads on the desktop version, but I didn't check other platforms.
`||bursahakimiyet.com.tr/get-ad `rule seems to work.

**Review by AdamWr — APPROVED** [review]

**Pull request merged**
