### PR TITLE
fix #80056 chip.de

### LINKED ISSUE #80056: www.chip.de
### Issue URL (Annoyance)
 [https://www.chip.de/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.chip.de%2F)
### Comment
Username: @Morku
> Cookie Pop-up

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.3
Browser: | Firefox
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters
DNS filtering: | server: `Cloudflare DNS-over-HTTPS`<br>filters: `"AdGuard DNS filter" with AdGuard Home`
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Russian, <br/>AdGuard German
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js

### PR DESCRIPTION
**Pull request by wout-codes**
#80056

### CODE REVIEW

**Review by BlazDT — APPROVED** [review]
Thanks for noticing the missing line break :)

**Comment by wout-codes** [comment]
Btw, I could use the euconsent rule, which works much faster. This rule is quite complicated in my perspective.

**Comment by BlazDT** [comment]
With euconsent cookie check on very first visit it works. Then you visit a subdomain of chip.de and is not doing anything with the cookie element as euconsent cookie exists.
Just accepting the cookie dialogue while allowing every marketing (etc.) cookie is imho not a way a customer is accepting as without AdGuard the privacy-concerned user is also disabling every non-necessary cookie.

**Comment by wout-codes** [comment]
Yeah, you're right.

**Pull request merged**
