### PR TITLE
Inspired by #107129

### PR DESCRIPTION
**Pull request by DandelionSprout**
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

As a result of #107129, I figured it'd be a good idea to pre-emptively fix social media buttons before people report them. So I took some generic hiding rules from https://raw.githubusercontent.com/DandelionSprout/adfilt/master/SocialShareList.txt with minor adjustments, and am submitting them here.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

image
</details><br/>

* **Expected behaviour**: 

End-users don't see as much need to report social media buttons, because they're hopefully fixed already.

<details><summary>Screenshot:</summary>

N/A
</details><br/>

***Steps to reproduce the problem***:

1) Open https://github.com/AdguardTeam/AdguardFilters/issues?q=is%3Aissue+is%3Aopen+label%3A%22T%3A+Social+Widget%22

***System configuration***

**Filters:**

N/A, as the issue report is exclusively for AdGuard Social Media Filter.

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 11 x64
Operating system version (Android/iOS) | N/A
Browser:                               | Chrome 97.0.4692.71 x64
AdGuard version:                       | uBO 1.40.9b1 + IDCAC 3.3.5
Filters enabled:                       | N/A
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

### CODE REVIEW

**Comment by ameshkov** [comment]
Thank you, the idea is not bad.

Could you please also check if there're any duplicates there?
Some of these rules intersect with existing domain-specific rules.

Here's one example: `joemonster.org###fb-share` is now covered by `#fb-share`.

Also, quick question to @AdguardTeam/filters-maintainers. Why do we keep adding per-domain rules for some elements like `#social-share`?

Talking about this: `
lewdgamer.com,zet.com,clubhunters.ru,multiplayer.it,www-m.cnn.com,edition-m.cnn.com,ampproject.org,drom.ru,haberler.com,daenischesbettenlager.at,daenischesbettenlager.de,jysk.al,jysk.am,jysk.ba,jysk.be,jysk.bg,jysk.by,jysk.ca,jysk.co.id,jysk.co.uk,jysk.com,jysk.com.cy,jysk.com.kw,jysk.com.mt,jysk.ch,jysk.cz,jysk.dk,jysk.ee,jysk.es,jysk.fi,jysk.fr,jysk.ge,jysk.gr,jysk.hr,jysk.hu,jysk.ie,jysk.it,jysk.kz,jysk.lt,jysk.lv,jysk.nl,jysk.md,jysk.me,jysk.mk,jysk.no,jysk.pl,jysk.pt,jysk.ro,jysk.rs,jysk.se,jysk.si,jysk.sk,jysk.ua,jysk.vn,jysk-ks.com,jyskthailand.com,pisiffik.gl,rumfatalagerinn.is,skemman.fo###social-share`

**Comment by DandelionSprout** [comment]
I've at least tried to remove duplicates from `specific.txt` now. The catch is that the tool I use for such (https://abpvn.com/ruleChecker/redundantRuleChecker.html), does not take `$generichide` entries from other lists into the equation.

**Comment by BlazDT** [comment]
When converting big rules to generic rules we have to check if there is an existing generichide rule exception too.

**Comment by DandelionSprout** [comment]
I think I've accomplished that too now, by comparing the specific-entries I had removed, with `$generichide` entries in AdGuard Base and EasyList. Thankfully, only 4 sites were affected by this.

**Comment by AdamWr** [comment]
I'm not sure if all these rules should be removed and it looks like that some of generic rules may cause incorrect blocking (I didn't check all rules).

For example, there is `generichide` rule for `onet.pl`, so specific rule shouldn't be removed. As I recall, the same for `fakt.pl` (`generichide` is in one of the Polish filter lists).

If I'm not wrong, this rule is still needed:
```
einfachbacken.de##.social-share-links > a:not(.social-share-links__link--pdf)
```

Another case:
```
thegamer.com,cbr.com,gamerant.com,screenrant.com##.sharing > .sharing-btn:not(.js-show-coments)
```
As far as I understand, it will be covered by `##.sharing` rule, but it causes that a comment button is hidden here:
```
https://www.cbr.com/the-suicide-squad-peacemaker-james-gunn-defends-rick-flag-death/
```

<hr>

>Why do we keep adding per-domain rules for some elements like `#social-share`?

As far as I know, we are adding generic rule only if rule is used on many websites. I guess, because generic rules may cause incorrect blocking.

**Comment by DandelionSprout** [comment]
Regarding `onet.pl`, I've now finished re-instating entries for sites that had `$generichide` in AdGuard filters *other* than AdGuard Base. That task was not easy to do, enough so that I should take the rest of the night off with food and streaming-cartoons.

Regarding `einfachbacken.de` and `thegamer.com,cbr.com,gamerant.com,screenrant.com##.sharing > .sharing-btn:not(.js-show-coments)` (without having tested the example link just yet), I have in recent months become a passionate proponent of adding `:not(html, body)` or `:not(html, body, article)` to generic `##.` rules in pretty much all major lists; but I wasn't sure if AdGuard was sold on that idea just yet.

Regarding `fakt.pl`, I haven't got that far as to re-instate third-party filters' `$generichide` entries' sites. I've turned on the "Allow edits by maintainers" button just in case.

**Comment by Alex-302** [comment]
Checking in user filter on many sites, and did not find new the necessary rules, which not covered by our. It seeems the most elements exist on few sites only.
But found incorrect blockings. For example, on some sites `##.btn-twitter` blocks links to twitter blogs, similar problem with `##.social-icon` - blocks too much.
Also the most of the rules do not have `"` in selectors, and I don't like a large number of generic rules with `*=`  they lead to  drop in performance on some sites(like with enabled AdBlockID) and may block too much.
Removing of `PLATFORM` hints and making some rules as generic - 100% bad idea.

**Comment by DandelionSprout** [comment]
Well, if you guys want to cut down on the amount of open issues for annoyances and social widgets, you guys simply don't have much other choice than to use generic entries big time.

**Comment by Alex-302** [comment]
We need generic rules, but not hundreds at a time)
Even that recently reported Japanese sites may be broken(blocked too much) by similar rules, created for them. And the most of them are not popular, only one user reports them.

**Comment by Yuki2718** [comment]
TBH I have already made them generic if a rule shall be safe by doing so.

**Comment by Yuki2718** [comment]
> Well, if you guys want to cut down on the amount of open and future issues for annoyances and social widgets, you guys simply don't have much other choice than to use generic entries big time.

We can simply ignore them.

**Comment by chirag127** [comment]
> Well, if you guys want to cut down on the amount of open and future issues for annoyances and social widgets, you guys simply don't have much other choice than to use generic entries big time.

I'm using your list from some time but most of the times it also block button like sign in with facebook and sign in with xyz and sometimes even sign up with email button. but I don't remember the example but saying to avoid this kind of blocking for other adguard used and henceforth creating much more reports.

**Pull request closed without merging**
