### PR TITLE
fix #74166 balticlivecam.com

### LINKED ISSUE #74166: balticlivecam.com
### Issue URL (Anti Adblock Script)
 [https://balticlivecam.com/ru/cameras/taiwan/taipei/taipei-down-town/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fbalticlivecam.com%2Fru%2Fcameras%2Ftaiwan%2Ftaipei%2Ftaipei-down-town%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.31
Browser: | Firefox
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard Russian

### PR DESCRIPTION
**Pull request by wout-codes**
#74166

### CODE REVIEW

**Comment by wout-codes** [comment]
@Yuki2718 Can you help me? What should I add for `content_blocker.txt`?

**Comment by Yuki2718** [comment]
`balticlivecam.com#@#.ad-placement` but not to `content_blocker.txt` but to the same anti-adblock.txt with `if` directive:
```
!#if (adguard_ext_safari || adguard_app_ios || adguard_ext_android_cb)
balticlivecam.com#@#.ad-placement
!#endif
```
Also `balticlivecam.com##.ad-block-inside` to AnnoyancesFilter > antiadblock.txt

**Comment by wout-codes** [comment]
> `balticlivecam.com#@#.ad-placement` but not to `content_blocker.txt` but to the same anti-adblock.txt with `if` directive:
> 
> ```
> !#if (adguard_ext_safari || adguard_app_ios || adguard_ext_android_cb)
> balticlivecam.com#@#.ad-placement
> !#endif
> ```
> 
> Also `balticlivecam.com##.ad-block-inside` to AnnoyancesFilter > antiadblock.txt

Thanks!

**Comment by Yuki2718** [comment]
Maybe `balticlivecam.com##.ad-block-inside` -> `balticlivecam.com###ad_block_off` (not much difference).

**Comment by wout-codes** [comment]
> Maybe `balticlivecam.com##.ad-block-inside` -> `balticlivecam.com###ad_block_off` (not much difference).

Yeah Now?

**Comment by Yuki2718** [comment]
> 
> Yeah Now?

If you can.

**Comment by wout-codes** [comment]
So I change the rule right?

**Comment by Yuki2718** [comment]
Merged as everything looks fine, thank you!

**Pull request merged**
