### PR TITLE
swatchseries.to #24376

### PR DESCRIPTION
**Pull request by slavaleleka**
.

### CODE REVIEW

**Review by BlazDT — CHANGES_REQUESTED** [review]
Change adblock rule to 
swatchseries.to##.centeres > #rotating-item-wrapper > .notify

Rule "swatchseries.to##.fullwrap > * > div[style="margin:0 0 0px 0;"] > * > * > * > * > div[style="padding: 10px; width: 25%;"]
" is not matching on main site or episode site.

To block generation of the ads:
swatchseries.to#%#AG_abortInlineScript(/driver\,bannerId/, 'addEventListener');

**Comment by ameshkov** [comment]
I suggest using this:

```
! unblocking this request as otherwise the circumvention script is triggered
@@||native.propellerclick.com/1?z=^$domain=swatchseries.to
```

It'd be better to avoid JS rules when it is possible (there's a serious scriptlets rework under development).

**Comment by slavaleleka** [comment]
> Rule "swatchseries.to##.fullwrap > * > div[style="margin:0 0 0px 0;"] > * > * > * > * > 
> div[style="padding: 10px; width: 25%;"]" is not matching on main site or episode site.

it will match on the next page after you choose "Watch this link!"

**Comment by Alex-302** [comment]
@BlazDT

**Comment by BlazDT** [comment]
OK @ameshkov.

@slavaleleka please put mentioned rule into anti-adblock and remove javascript rule.

**Pull request closed without merging**
