### PR TITLE
Fix tiktok.com

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/AdguardTeam/AdguardFilters/issues/95986

### CODE REVIEW

**Comment by Yuki2718** [comment]
Hmm, on my end it's `##.backdrop-1`. Also scroll is locked, needing `tiktok.com#$#body[style="overflow: hidden;"] { overflow: auto!important; }`. This also means all the filters have to be convereted to css filter like `tiktok.com#$#div[class^="jsx-"][style="bottom:49px"].footer-guide { display: none!important; }` to prevent 'half-fix' on Contents Blocker.

**Comment by piquark6046** [comment]
Committed. https://github.com/AdguardTeam/AdguardFilters/pull/96238/commits/58dd65910d3222251d772be036ec9f7a3f3d5073

**Comment by Yuki2718** [comment]
Please change `#$#.backdrop-2 { display: none!important; }` to `#$#div[class^="backdrop-"] { display: none!important; }`

**Comment by piquark6046** [comment]
Done. Thank you. https://github.com/AdguardTeam/AdguardFilters/pull/96238/commits/561f39f55e78b1a4646c64a7be0b9eecaa7b8bb2

**Review by Yuki2718 — APPROVED** [review]

**Review by Yuki2718 — CHANGES_REQUESTED** [review]
~~Oh, btw this is wrong file - correct one is popups.txt so move the rules there.~~ Never mind, mobile-app.txt is fine here. My bad.

**Review by Yuki2718 — APPROVED** [review]

**Review by zloyden — APPROVED** [review]

**Pull request merged**
