### PR TITLE
fix #38741 cyberspace.world

### LINKED ISSUE #38741: cyberspace.world
### Issue URL (Anti Adblock Script)
[https://www.cyberspace.world/search/label/Adobe](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.cyberspace.world%2Fsearch%2Flabel%2FAdobe)
### Comment
Username: @AnonymousGitHubUser2020
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 3.2.1
Browser: | Chrome
Filters: | Filter unblocking search ads and self-promotion,<br>AdGuard Base

### PR DESCRIPTION
**Pull request by zloyden**
https://github.com/AdguardTeam/AdguardFilters/issues/38741

### CODE REVIEW

**Comment by BlazDT** [comment]
And for non-JS and non-$$ products?

**Review by Alex-302 — CHANGES_REQUESTED** [review]
make rules for all platfoms

**Comment by zloyden** [comment]
In this case I unblocked too much requests, but even with exception `generichide` I noticed adblock window.

**Comment by Alex-302** [comment]
look for the BlockAdBlock rules in content_blocker.txt

**Review by Alex-302 — APPROVED** [review]

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
