### PR TITLE
Went through most of the English entries in "Annoyances - Remains"

### PR DESCRIPTION
**Pull request by DandelionSprout**
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

After I went through the German entries in "AdGuard Annoyances - Remains" last time, this time I went through the English entries in it. Took me 3 hours.

My findings for the entries were as following:
```
! Sites that no longer exist:
bitmakler.com
btconity.com
filescloud.co
m.flyordie.com
sansursuzhaber.com
streamcherry.com
streamsfinder.com
thedaretelly.com
x.epidemz.co
x.epidemz.com
animev.net
porno720p.org
winphonehub.org
zonasports.be
zonasports.ch
efirde.az

! Reproduced:
diffnow.com###root > div[style="margin: 20px 72px;"] > div[style^="position: relative; display: flex; margin-top: 20px; margin-bottom: 20px; justify-content: center; align-items: center; border:"][style$="height: 100px; overflow: hidden;"]
distrowatch.com##td[style="width: 19%; vertical-align: top; border: none"] > table[class="News"]+br+table[width="100%"]
filehorse.com##.dx-sb-1
gottabemobile.com##div[class^="code-block code-block-"][style]:not([class$="code-block code-block-16 ai-desktop-tablet"])
heroesfire.com,owfire.com,pgfire.net,vaingloryfire.com##.sidebar-feature.add.box
hidden247.com##.oglSve
m.empflix.com##.bannerBlock
movies.ndtv.com##.ndmv-ad-wrapper
movies.ndtv.com#$##footer-ads { height: 0!important; }
ndtv.com###ad100
slipstick.com##.entry-content > div[style^="width:100%;padding: 10px 10%;height:100px;"]
smitefire.com##.self-clear div.caroufredsel_wrapper
vivud.com##.closeContainer
lyngsat.com##a[href="http://www.lyngsat.com/advert.html"]
ashemaletube.com#$##site-wrapper {padding-top: 0!important; }
ashemaletube.com#$##site {min-width: calc(100%)!important; max-width: calc(100%)!important;}
ashemaletube.com#$##site-wrapper {min-height: calc(100%)!important;}
babesource.com##.corner-ad
babesource.com##.addthis
babesource.com##.gallery-content > .sidebar
bigtitsxxxsex.com##.bnrba
enjoyfuck.com,fuckgonzo.com##.advmnt
foxgay.com##body > .pb_footer
gayporno.fm,gaymaletube.name,gayporn.fm,gaysuperman.com##.b-uvb-spot
gaytiger.com##.content-inner-col > .aside-itempage-col
m.smutty.com##.ui-content .center[style*="margin-"]:not([id])
me-gay.com,gaysuperman.com##.b-mobile-random-links
me-gay.com,gaysuperman.com##.mobile-random
modelsxxxtube.com##div[class^="adx-"]
wildgay.com###main > table td[width="520"] + td[bgcolor="#191919"]
youjizz.com###desktopFooterPr
youjizz.com###onPausePrOverlay
youjizz.com##.top_pr
off-soft.net##.right_sidebar > .adsbygoogle
zoomgirls.net##.side-header2

! Reproduced (Indonesian):
semprot.com##.semprotnenenmontok_adalah_pujaan_hatiku > div[style]:not([id]):not([class])

! Reproduced (Azerbaijani):
kayzen.az##.CustomBlock.Blocksmaster
feat.az##.counts

! Can't reproduce:
bonusbitcoin.co##[style*="width:468px"][style*="height"][style*="0px"]:not([id]):not([class])
bonusbitcoin.co##div[style*="width:500px;height:402px;"]
cafefernando.com###l_sidebarwidgeted > #text-20
distrowatch.com##td[style^="width: 20%; vertical-align: top; border: none;"] > table[class="News"]+br+table[class="Info"]
download3k.com###dl_main_container_content > div[class="space"][style]
frkn64modding.com##.flexia-sidebar-inner > #ai_widget-3
frkn64modding.com##.flexia-sidebar-inner > #ai_widget-4
getandroidstuff.com##.td-header-rec-wrap
gottabemobile.com##section[class$="cb-entry-content clearfix"] > center
gottabemobile.com##tr > td[colspan$="2"] > center
hidden247.com##.igraR
hidden247.com#$#.igraL { visibility: hidden!important; }
ign.com##.video_supplement > div#queen
investingnote.com##.dianomi-ads
investingnote.com##iframe[src^="//www.dianomi.com"]
latimes.com##ark-ad-right
latimes.com##ark-top-ad
lolalytics.com##.right_1_3 > div:not([class]):not([id]):not([style])
lolalytics.com##body > div[class] > div[style^="width:728px; font-size:0px; height:90px;"]:not([id]):not([class])
m.boyfriendtv.com##.adblock-big
m.comic.naver.com##body > div.viewer.cuttoon > div[class^=ly_dim].on
m.comic.naver.com##div[class="ly_wrap viewer_da_ly"]
majorgeeks.com###ypaAdWrapper-mjgeeksUnitTop
menshealth.com##.iab-adcontent
menshealth.com,runnersworld.com##.zeus_inhouse_ad_container
movies.ndtv.com##.cnAdzerkDiv
movies.ndtv.com##.ndmv-inner-ad-wrapper
ndtv.com#$#.ad300 { position: absolute!important; top: -2000px!important; }
ndtv.com#$#.ad_300.section { position: absolute!important; top: -2000px!important; }
nzz.ch##aside[class$="resor resor--billboard"]
omgchrome.com###banner
opensnow.com##.recommend-blocks > .col-md-4[style="text-align:center"]
radarbox24.com##.remove-pub
remote.12dt.com##.left_rail > div.pad
sadeempc.com###secondary > aside#text-15
semprot.com###semprotnenenmontok_f
slipstick.com##.entry-footer > .lastone
softpedia.com###swipebox-top
softpedia.com##div[style^="font-size:13px; margin: 0 0 5px 0; color: #002873;"]
softpedia.com#$##swipebox-right:before { content: none!important; }
thefreedictionary.com##div[style="border:1px solid #e8e8e9;font-weight:600"]
thefreedictionary.com##span[class] > div[style="float:right;display:inline-block;margin-left:20px"]
top100arena.com###container3 > div[style="padding:20px; position:relative"] > div[style="overflow:auto"] > div[style="float:right; text-align:center"]
tureng.com##.tureng-ad-horizontal-responsive
tureng.com##.tureng-index.hidden-print > div[style$="min-height: 130px;"]
unlockapk.com##.StlyeSocial
||softportal.com/img/adg_rnb.png
mobafire.com###sidebar-free-champs + div.box-shadow.mb10
briian.com###content > div[style="width:100%;margin:0 10px 5px; padding:3px 12px; background:#FFFFFF;"]
briian.com##.entry-data-wrapper-single-mobile > div[style^="float: right; margin:"][style*="height: 325px; width: 170px; background: #FFFFFF;"]
m.pornxs.com###im_scroll_close_button
porndoe.com##div[data-subscript="Advertising"]
porndoe.com##div[data-supscript="Advertising"]
sexhoundlinks.com##.banner
spankwire.com##.align-center
wildgay.com##div[class^="line"][class*="ad"]
xgaytube.com##.PlayPageBanners
xgaytube.com##.videoPlayer > .uwrap
xhamster.com###swectrqw
xvideos.com##p.mobile-only-hide
xxxfatclips.com##.SAbnsBotBl
xxxfatclips.com##.SHBotBl > div[style*="height:150px;width:300px;"]:not([class]):not([id])
xxxfatclips.com##.SHVidBlock > .SHVidBlockR
zgaytube.com##.gal_body > .right > h3
marktplaats.nl###bottom-listings-divider
audiotube.org##div[style="color:black;background-color:white;line-height: 11px;"] + hr
loading.az##.banlog
loading.az##.counts
olke.az##div[class="mom_visibility_desktop center"][style="padding-left: 4px"]

! Made superfluous by EasyList
ndtv.com##div[id^="div-gpt-ad-"]

! Made superfluous by AdGuard Base
off-soft.net##.contents-usual > div[style] > .adsbygoogle

! Incorrectly blocks a mailing list widget
filehorse.com##.big-sidebar

! Incorrectly blocks what seems to be legitimate elements
l2topzone.com##.col-md-6 > .panel

! Add new entries
! https://bonusbitcoin.co/
bonusbitcoin.co##div[style^="text-align:center;margin"]:has(iframe[src*="ads."])
! https://www.hidden247.com/
hidden247.com##.oglSvePoc
! https://lolalytics.com/
lolalytics.com###leaderboard
! https://www.lyngsat.com/
lyngsat.com##tr[valign="baseline"]
! https://kayzen.az/
||code.ainsyndication.com^
kayzen.az##.Blocksmaster

! Reproduced (for AdGuard German):
handelsblatt.com##.hcf-sponsoring

! Reproduced (for AdGuard Turkish):
teknolojioku.com##.row > div.justify-content-center.d-flex.align-items-center[style*="px"]:not([id])
webaslan.com##div[style="float:right; margin-right:4px; width:300px;"] div[style="min-height: 255px;"]
bursa.com##.bg--gri[style="padding: 10px 0;"]

! Reproduced (for AdGuard Japanese):
kiwi-english.net###footer > div.footer-inner.shad
```

I've attempted to make sure that only Russian and Turkish sites would remain in Annoyances Remains. Mostly because you guys are better at such sites than what I am, but also since a list that only had RU/TR sites remaining in it would no longer be something I'd feel an odd need to use in my various adblocker setups on an everyday basis, thus I can slim down the huge list-setup screenshots like the below one a slight bit.

* **Expected behaviour**: 

N/A

***Steps to reproduce the problem***:

N/A

***System configuration***

**Filters:**

image

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | May 2020 Update
Browser:                               | Chrome x64
AdGuard version:                       | Nano Adblocker 1.0.0.152 + Nano Defender 15.0.0.201
Filters enabled:                       | See screenshot above.
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | N/A
Helpdesk ID (if exists):               | N/A

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

### CODE REVIEW

**Review by Alex-302 — COMMENTED** [review]
that rules are in Annoyances, because they are not safe or ambiguous.
Sure, they need be reviewed and resorted.

Progress is here:
<details>

+++ ! Sites that no longer exist:


+++ ! Reproduced:

! Reproduced (Indonesian):
semprot.com##.semprotnenenmontok_adalah_pujaan_hatiku > div[style]:not([id]):not([class])

--- ! Reproduced (Azerbaijani):

+++ ! Can't reproduce:

+++ ! Made superfluous by EasyList

+++ ! Made superfluous by AdGuard Base

+++ ! Incorrectly blocks a mailing list widget

+++! Incorrectly blocks what seems to be legitimate elements

! Add new entries
! https://bonusbitcoin.co/
bonusbitcoin.co##div[style^="text-align:center;margin"]:has(iframe[src*="ads."])
! https://www.hidden247.com/
hidden247.com##.oglSvePoc
! https://lolalytics.com/
lolalytics.com###leaderboard
! https://www.lyngsat.com/
lyngsat.com##tr[valign="baseline"]
! https://kayzen.az/
||code.ainsyndication.com^
kayzen.az##.Blocksmaster

! Reproduced (for AdGuard German):
handelsblatt.com##.hcf-sponsoring

! Reproduced (for AdGuard Turkish):
teknolojioku.com##.row > div.justify-content-center.d-flex.align-items-center[style*="px"]:not([id])
webaslan.com##div[style="float:right; margin-right:4px; width:300px;"] div[style="min-height: 255px;"]
bursa.com##.bg--gri[style="padding: 10px 0;"]

! Reproduced (for AdGuard Japanese):
kiwi-english.net###footer > div.footer-inner.shad
</details>

**Comment by DandelionSprout** [comment]
I've heard multiple stories from AdGuard team members about how placeholders are treated. But once I realised that placeholders are accepted in the main AdGuard lists as well, and on equal conditions as actual ads, I began thinking *"Wait, why does AdGuard Annoyances have a placeholder section then?"*, and probably drew several conclusions based on that.

**Comment by Alex-302** [comment]
Look at the date when that rules was added.

**Comment by Alex-302** [comment]
> ! Sites that no longer exist:

removed.  flyordie.com / m.flyordie.com is working.

**Comment by DandelionSprout** [comment]
For me, `m.flyordie.com` redirected to `www.flyordie.com` regardless of which user-agent I was using. I'm glad you guys could confirm it worked, however.

**Comment by DandelionSprout** [comment]
I did have the "Allow edits by maintainers" button turned on, in case only minor modifications would've been needed before merging in one go. I do however accept the decision that bigger modifications are needed,

**Comment by Alex-302** [comment]
> bigger modifications are needed

yes. Also dozens of conflicts will appear in a few hours.

**Comment by Alex-302** [comment]
Done

**Pull request closed without merging**
