### PR TITLE
fix #64959 javhay.net

### LINKED ISSUE #64959: javhay.net
### Issue URL (Incorrect Blocking)
[NSFW] [https://javhay.net/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fjavhay.net%2F)

### [NSFW] Screenshots
<details>
  <summary>Screenshot 1</summary>

  [Screenshot 1](https://reports-img.adguard.com/h8InRcg.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  [Screenshot 2](https://reports-img.adguard.com/iceDGtU.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.12
Browser: | Chrome
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Adblock Warning Removal List<br/><br/><b>Language-specific:</b><br/> AdGuard Chinese
Other extensions used: | AdGuard

### PR DESCRIPTION
**Pull request by Yuki2718**
https://github.com/AdguardTeam/AdguardFilters/issues/64959

### CODE REVIEW

**Comment by Sergey-Lyapin** [comment]
I think it's better to add this rule `||javnung.net/adbock.js` and remove existing `$generichide` rule and` javhay.net` from `#%#//scriptlet('abort-current-inline-script', 'document.addEventListener', '/google_ad_client/')` because it doesn't work at this moment.

**Comment by Yuki2718** [comment]
@Sergey-Lyapin You're right, will revert the change, add the rule, and remove the obsolete one.

**Comment by Yuki2718** [comment]
If there's any problem please fix on your end.

**Comment by Sergey-Lyapin** [comment]
I've fixed the issue by myself https://github.com/AdguardTeam/AdguardFilters/commit/ca278d0b9ae10c71386a34da54a78eb7a8982165, thanks for your time. I've added the network rule to other particular antiadblock rules.

**Pull request closed without merging**
