### PR TITLE
Fix #144576 www.clubjt.jp

### LINKED ISSUE #144576: www.clubjt.jp
### Issue URL (Annoyance)
 [https://www.clubjt.jp/home](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.clubjt.jp%2Fhome)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.4.5
Browser: | Safari
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Japanese

### PR DESCRIPTION
**Pull request by SKEIDs**
### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [x] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

### Enter the issue address

 Fix #144576 

### Add your comment and screenshots

Account required
I could reproduced by moving on from other webpage.

`##app-favorite-popup-chrome` also need?

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Review by zloyden — COMMENTED** [review]
It requires an account, but I can't register it.
@Yuki2718 could you review it?

**Comment by SKEIDs** [comment]
I will share webpage HTML file.
Please refer to it if you like.

**Comment by SKEIDs** [comment]
> Do you see that if you use Chrome? 

I can reproduce it when I changed UA to Android.
This is then HTML.
https://send.cm/d/LcCo

**Comment by Yuki2718** [comment]
Okay, then add the rule.

**Comment by Yuki2718** [comment]
I meant Tracking Protection filter = spyware.

**Comment by SKEIDs** [comment]
I see, Sorry.

**Review by Yuki2718 — APPROVED** [review]

**Review by zloyden — APPROVED** [review]

**Pull request merged**
