### PR TITLE
cospa.co.jp

### PR DESCRIPTION
**Pull request by gork7777**
issue: #99271

### CODE REVIEW

**Comment by Yuki2718** [comment]
@Alex-302 @gork7777 's fix is perfectly fine but at the same time I wonder about a generic filter `##a[href^="javascript:void window.open('http://line.naver.jp/R/msg/text/"]`

**Review by Alex-302 — APPROVED** [review]

**Comment by Alex-302** [comment]
@Yuki2718 How frequently this part is used?

**Comment by Yuki2718** [comment]
@Alex-302 publicwww says 325 sites: `https://publicwww.com/websites/%22javascript%3Avoid+window.open%28%27http%3A%2F%2Fline.naver.jp%2FR%2Fmsg%2Ftext%2F%22/`

**Comment by Alex-302** [comment]
@Yuki2718 Please open few sites - this selector cannot be applied(code on the sites is a bit different)

**Comment by Yuki2718** [comment]
@Alex-302 Yeah, so probably the generic filter is not worth adding, at least for now.

**Pull request merged**
