### PR TITLE
Fix #133898 a2zapk.com

### LINKED ISSUE #133898: a2zapk.com
### Issue URL (Incorrect Blocking)
 [https://a2zapk.com/History/com.medhaapps.wififtpserver.pro/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fa2zapk.com%2FHistory%2Fcom.medhaapps.wififtpserver.pro%2F)
### Comment
Username: @wernser412
> Las imágenes no aparecen.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>
<details>
  <summary>Screenshot 2</summary>

  Screenshot 2
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v4.1.39
Browser: | Chrome
Stealth mode: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>AdGuard Spanish/Portuguese

### PR DESCRIPTION
**Pull request by piquark6046**
### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [X] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [X] I have performed a self-review of my own changes;
- [X] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [X] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

### Enter the issue address

 - https://github.com/AdguardTeam/AdguardFilters/issues/133898

### Add your comment and screenshots

None.

### Terms

- [X] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Comment by Alex-302** [comment]
I still see detection when I try to download

<details>
<summary>Details</summary>

image


</details>

**Comment by piquark6046** [comment]
Can you the following instruction?
1. Close all related tabs
2. Clear all caches and cookies
3. Open the URL provided at https://github.com/AdguardTeam/AdguardFilters/issues/133898#issuecomment-1305143035

It works on my end.

**Comment by piquark6046** [comment]
@Alex-302

**Comment by Alex-302** [comment]
Hm. It works now(in a regular or a private tab).

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
