### PR TITLE
The 1st large cleanup of Base

### PR DESCRIPTION
**Pull request by Yuki2718**
I checked dead domains in this way:
1: Screened with PyFunceble for potential dead domains
2: picked some domains and checked each with publicwww (depth: all) for actual URL, if found I checked the URL, if not found (0 hit) I googled the domain (`"example.com"` and `site:example.com`) which usually returns some example URLs.
```

! ---------- Dead domains
||n2hbmu7he2faa.online^
||mama.foor-zik.com^$third-party
||foastail.net^
||js.gouhei.top^$third-party
||wilwasharrabred.pro^
||asg.xz2aab.xyz^$third-party
||qr-maker.me^
||reberr.pro^$third-party
||deryjobmeetin.info^
||furtherescottom.info^
||udriveme2.com^$third-party
||rotibald.com^
||anothinga.com^$third-party
||xikrik.com^$third-party
||brassyobedientcotangent.com^$third-party
||eerdckbwujcx.com^
||growth-flexvprosystem.com^$third-party
||poprush.net^$script,third-party
||qwtm.purecertainengine.com^$popup
||u034024.778669.com^$third-party
||xxyafiswqcqz.com^
||yuiop.trade^$third-party
||yxbtyzqcczra.com^$third-party
||zaperplop.info^$third-party
||zptncsir.com^


! ---------- Now in EL (can be slightly different form)
||d227cncaprzd7y.cloudfront.net^$third-party

vivud.com##.in_stream_banner
||ouo.press/js/pop.
vshare.io###sendif
||giveawayoftheday.com/web/bannerinf.js
||gotporn.com/bck_loader_
||cpmgohigh.com^$third-party
anysex.com##.native_middle
txxx.com##.underplayer_banner
howtogeek.com###div-thetop1
||videoszoofiliahd.com/wp-content/themes/vz/js/p.js
||maxconsole.com/styles/mc/ad/
||eroprofile.com/js/nvbl.js
flashscore.co.uk##.boxOverContent__banner
fliphtml5.com##.fh5---banner---container

||uptopopunder.com^$popup

##.post-ads


! ---------- Redundant
xz2.xyz#%#//scriptlet("prevent-window-open")
! Base has ||zbporn.*/xdman/
||zbporn.com/xdman/
||zbporn.com/xdman/license.*.js
! Base has ||util.simply-hentai.com/prod/
||util.simply-hentai.com/prod/$script,image,domain=simply-hentai.com
! EL has ||coinadster.com^
||coinadster.com^$domain=dogemanager.com
! EL has /popad|$popup
||linclik.com/links/popad|$popup
! EL has /ad_onclick.
||hitsmedia.us/ad_onclick.php
! EL has ||gamecopyworld.*/p2.js
||gamecopyworld.eu/games/js/p2.js
! EL has ||clipwatching.com/pu/
||clipwatching.com/pu/*.js
! EL has ||aparat.cam/pu/
||aparat.cam/pu/*.js

! EL has /adBlockDetector/*
/AdblockDetector/handler.min.js$script

! covered by @@||hdliveextra-a.akamaihd.net/HD/scripts/*/config/ads.js
@@||hdliveextra-a.akamaihd.net/*/config/ads.js$domain=vplayer.nbcsports.com

! ---------- Obsolete filters: no such properties
!+ NOT_PLATFORM(windows, mac, android)
vjav.com#%#//scriptlet("abort-on-property-read", "vertis.popunder.neverblock")
!+ NOT_PLATFORM(windows, mac, android)
vjav.com#%#//scriptlet("set-constant", "JsvISiNc.neverblock.loaderUrl", "undefined")
!+ PLATFORM(windows, mac, android)
vjav.com#%#AG_abortOnPropertyRead('vertis.popunder.neverblock');
!+ PLATFORM(windows, mac, android)
vjav.com#%#AG_setConstant('JsvISiNc.neverblock.loaderUrl', 'undefined');


! ---------- Obsolete filters in Annoyances
independent.co.uk#%#//scriptlet("prevent-fab-3.2.0")
```

### CODE REVIEW

**Comment by Alex-302** [comment]
The problem with dead domains - sometimes top domain cannot be resolved, only subdomains, but a rule contains top domain only.

**Comment by Yuki2718** [comment]
> The problem with dead domains - sometimes top domain cannot be resolved, only subdomains, but a rule contains top domain only.

I explained how I addressed that. Talked about the same with @ameshkov in Slack (PM).

**Review by zloyden — APPROVED** [review]

**Comment by Yuki2718** [comment]
Thx!

**Comment by zloyden** [comment]
You are welcome.

**Pull request merged**
