### PR TITLE
fix dazn.com ads

### PR DESCRIPTION
**Pull request by Yuki2718**
### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [x] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

### Enter the issue address

NA

### Add your comment and screenshots

1. Your comment

https://www.dazn.com
Removes preroll (and hopefully midroll, but so far not tested) ads. Requires paid account to check. All rules tested, but tell me if you need details.

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Review by Alex-302 — COMMENTED** [review]
Isn't the scriptlet enough? I can't register.

Also we add these types to `specific.txt`

**Comment by Yuki2718** [comment]
> Isn't the scriptlet enough? I can't register.
> 

You know scriptlet is not 100% bullet-proof especially on the launch.

**Comment by Alex-302** [comment]
> You know scriptlet is not 100% bullet-proof especially on the launch.

programs inject their script as early as possible

**Comment by Yuki2718** [comment]
But we have `$jsonprune` for yt and tend to use both HTML filter/replace and scriptlet too. In general `$jsonprune` is better except for compatibility.

**Comment by Alex-302** [comment]
@Yuki2718 
> But we have $jsonprune for yt

YT is problematic...

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
