### PR TITLE
Fix #174674 www.khou.com

### LINKED ISSUE #174674: www.khou.com
### Issue URL (Annoyance)
 [https://www.khou.com/article/news/crime/houston-texas-crime-child-killed-suspect-arrested/285-422c3761-be38-441c-995a-8e8a6ab5a010](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.khou.com%2Farticle%2Fnews%2Fcrime%2Fhouston-texas-crime-child-killed-suspect-arrested%2F285-422c3761-be38-441c-995a-8e8a6ab5a010)
Username: `@xglossyntx`

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | Value
--- | ---
AdGuard product: | AdGuard Browser Extension v4.3.13
System version: | Windows 10
Browser: | Firefox
Stealth mode options: | Block WebRTC, <br>Strip URLs from tracking parameters, <br>Hide your search queries, <br>Send Do-Not-Track header, <br>Self-destructing third-party cookies (2880)
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>AdGuard Cookie Notices, <br/>AdGuard Popups, <br/>AdGuard Mobile App Banners, <br/>AdGuard Other Annoyances, <br/>AdGuard Widgets, <br/>Adblock Warning Removal List<br/><br/><b>Security:</b><br/>NoCoin Filter List<br/><br/><details><summary><b>Language-specific:</b></summary>AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Japanese, <br/>AdGuard Dutch, <br/>AdGuard Spanish/Portuguese, <br/>AdGuard French, <br/>EasyList Czech and Slovak, <br/>EasyList Italy, <br/>AdBlockID, <br/>List-KR, <br/>Dandelion Sprout's Nordic Filters, <br/>IndianList</details>

### LINKED ISSUE #174677: www.wusa9.com
### Issue URL (Annoyance)
 [https://www.wusa9.com/article/news/local/virginia/marijuana-marketplace-advocates-in-virginia-frustrated-over-unlikely-future/65-411e1591-1369-40a1-a9af-aea2a41d78d3](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.wusa9.com%2Farticle%2Fnews%2Flocal%2Fvirginia%2Fmarijuana-marketplace-advocates-in-virginia-frustrated-over-unlikely-future%2F65-411e1591-1369-40a1-a9af-aea2a41d78d3)
Username: `@xglossyntx`

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | Value
--- | ---
AdGuard product: | AdGuard Browser Extension v4.3.13
System version: | Windows 10
Browser: | Firefox
Stealth mode options: | Block WebRTC, <br>Strip URLs from tracking parameters, <br>Hide your search queries, <br>Send Do-Not-Track header, <br>Self-destructing third-party cookies (2880)
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>AdGuard Cookie Notices, <br/>AdGuard Popups, <br/>AdGuard Mobile App Banners, <br/>AdGuard Other Annoyances, <br/>AdGuard Widgets, <br/>Adblock Warning Removal List<br/><br/><b>Security:</b><br/>NoCoin Filter List<br/><br/><details><summary><b>Language-specific:</b></summary>AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Japanese, <br/>AdGuard Dutch, <br/>AdGuard Spanish/Portuguese, <br/>AdGuard French, <br/>EasyList Czech and Slovak, <br/>EasyList Italy, <br/>AdBlockID, <br/>List-KR, <br/>Dandelion Sprout's Nordic Filters, <br/>IndianList</details>

### PR DESCRIPTION
**Pull request by xglossyntx**
# Creating the pull request

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [x] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

### Enter the issue address

fix #174674
fix #174677

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Review by zloyden — CHANGES_REQUESTED** [review]
Please also add the domains to other rules like you did in [previous PR](https://github.com/AdguardTeam/AdguardFilters/pull/174671/files).

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/174675#issuecomment-1991068548 yes, you can add it. As I see, the site has the same structure. The goal is that the rules must have the same order domains for easier navigation and adding rules.

**Review by zloyden — CHANGES_REQUESTED** [review]
Also update domains in this rule.
```adblock
abc10.com,wwltv.com,11alive.com,wfmynews2.com,thv11.com,9news.com,wkyc.com,wzzm13.com,kare11.com,13newsnow.com,12news.com##div[data-module="grid"] > div.grid__section:has(> div.grid__content > div.grid__main > div.grid__cell > div > div[data-module-sizer="ad"])
```

**Comment by xglossyntx** [comment]
> Also update domain in this rule.
> 
> ```
> abc10.com,wwltv.com,11alive.com,wfmynews2.com,thv11.com,9news.com,wkyc.com,wzzm13.com,kare11.com,13newsnow.com,12news.com##div[data-module="grid"] > div.grid__section:has(> div.grid__content > div.grid__main > div.grid__cell > div > div[data-module-sizer="ad"])
> ```

I planned on adding it, but I did not know what order it would go in.

**Comment by zloyden** [comment]
Like you have done
```
firstcoastnews.com,wnep.com,wtsp.com,wfaa.com,kgw.com,king5.com,wcnc.com,kens5.com,ksdk.com,khou.com,wusa9.com,abc10.com,wwltv.com,11alive.com,wfmynews2.com,thv11.com,9news.com,wkyc.com,wzzm13.com,kare11.com,13newsnow.com,12news.com
```

**Comment by xglossyntx** [comment]
> Also update domains in this rule.
> 
> ```
> abc10.com,wwltv.com,11alive.com,wfmynews2.com,thv11.com,9news.com,wkyc.com,wzzm13.com,kare11.com,13newsnow.com,12news.com##div[data-module="grid"] > div.grid__section:has(> div.grid__content > div.grid__main > div.grid__cell > div > div[data-module-sizer="ad"])
> ```

I am already in the process of working on that one.

**Review by zloyden — APPROVED** [review]

**Comment by zloyden** [comment]
Btw, do you know the name of the company behind those sites?

**Comment by xglossyntx** [comment]
> Btw, do you know the name of the company behind those sites?

Tegna Inc.

**Comment by zloyden** [comment]
I've updated it, so if you find a new related domain, use this `! Tegna Inc.` to find the rules. Thank you.

**Pull request merged**
