### PR TITLE
disable AG assistant for twitch embeds too

### PR DESCRIPTION
**Pull request by Bluscream**
Second chance for a contributor badge :D https://github.com/AdguardTeam/AdguardFilters/pull/3699#issuecomment-266031077

### CODE REVIEW

**Comment by Alex-302** [comment]
please, use new issue instead of pull requests

**Comment by Bluscream** [comment]
Why is it open source if you don't accept any PR's?

**Comment by Alex-302** [comment]
because we should to resolve conflicts while merging)
And sometimes I don't like suggested comments and rules.

**Comment by Bluscream** [comment]
That is why the "Allow edits from maintainers" checkbox exists.

**Pull request closed without merging**
