### PR TITLE
rule-maintenance - 17

### PR DESCRIPTION
**Pull request by SKEIDs**
EnglishFilter/sections/specific.txt

### CODE REVIEW

**Review by Alex-302 — APPROVED** [review]

**Comment by Alex-302** [comment]
Please do not make too big PRs.

**Comment by SKEIDs** [comment]
@Alex-302

excuse me, what size would be best?

**Comment by Alex-302** [comment]
5-7 rules(which you sort, not lines:) ), for PR like this.

**Comment by SKEIDs** [comment]
I see. thank you.

**Pull request merged**
