### PR TITLE
fix #77492 enrt.eu

### LINKED ISSUE #77492: enrt.eu
### Issue URL (Ads)
 [https://enrt.eu/hztYWVd](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fenrt.eu%2FhztYWVd)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.6 nightly 22
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (180), <br>Block Push API, <br>Block Location API
DNS filtering: | server: `https://dns-unfiltered.adguard.com/dns-query`<br>filters: `User rules`
Filters: | <b>Ad Blocking:</b><br/> EasyList, <br/>Peter Lowe's Blocklist, <br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> EasyPrivacy, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> Adblock Warning Removal List, <br/>I don't care about cookies, <br/>EasyList Cookie List, <br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/> Online Malicious URL Blocklist, <br/>Spam404, <br/>NoCoin Filter List
Custom filter subscriptions: | https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt,<br>https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt

### PR DESCRIPTION
**Pull request by wout-codes**
#77492
Site auto-redirects to it's ads page. So `enrt.eu$$meta` will solve it.

### CODE REVIEW

**Comment by wout-codes** [comment]
@Yuki2718 Should I add the ad-server to the base? `||ads.enrt.eu^`

**Comment by Yuki2718** [comment]
> Should I add the ad-server to the AdGuard Base first party? `||ads.enrt.eu^`

Sure, why not.

**Comment by wout-codes** [comment]
> > Should I add the ad-server to the AdGuard Base first party? `||ads.enrt.eu^`
> 
> Sure, why not. [EDIT] AH, you mean because this is Spanish site?

Yeah, I am not sure, that's why I asked. Also, for this one `enrt.eu$$meta[http-equiv="refresh"]`, should it be in base or spanish filter?

**Comment by Yuki2718** [comment]
I'm not sure either, the service description page is surely Spanish tho. I haven't addressed meta redirect but your rule is fine.

**Comment by wout-codes** [comment]
> I'm not sure either, the service description page is surely Spanish tho. I haven't addressed meta redirect but your rule is fine.

Should not the `$$` rule be under the HTML rules area? I don't see it in Spanish general extensions. I will leave the ad-server as it is for now.

**Comment by zloyden** [comment]
> @Yuki2718 Should I add the ad-server to the AdGuard Base first party? `||ads.enrt.eu^`

Let's keep it in `AdGuard Spanish` for now.

> I am not sure, that's why I asked. Also, for this one `enrt.eu$$meta[http-equiv="refresh"]`, should it be in base or spanish filter?

Spanish filter.



> > I'm not sure either, the service description page is surely Spanish tho. I haven't addressed meta redirect but your rule is fine.
> 
> Should not the `$$` rule be under the HTML rules area? I don't see it in Spanish general extensions. I will leave the ad-server as it is for now.

Leave it as it is.
Also @Yuki2718 @wout-codes please check `enrt.eu#%#AG_onLoad(function() {if ("/" !== location.pathname) {var a = new MutationObserver(function() {document.querySelector('meta[http-equiv="refresh"]') && (a.disconnect(), setTimeout(function() {window.stop()}, 20E3))});a.observe(document, {childList: !0,subtree: !0,attributeFilter: ['http-equiv']});setTimeout(function() {a.disconnect()}, 20E3)}});`, It should prevent the redirect.

**Comment by wout-codes** [comment]
Magic? It's working. Should I add it in Spanish filter?

**Comment by zloyden** [comment]
> Magic? It's working. Should I add it in Spanish filter?

Nice. Add it to your HTML rule, but don't remove `enrt.eu$$meta[http-equiv="refresh"]`.

**Comment by Yuki2718** [comment]
Maybe this can be addressed by custom script too? https://github.com/AdguardTeam/AdguardFilters/issues/76477

**Comment by wout-codes** [comment]
I will be on it. @zloyden Give me a chance

**Review by zloyden — APPROVED** [review]

**Comment by zloyden** [comment]
> Maybe this can be addressed by custom script too? #76477

I guess similar rule might work.

**Pull request merged**
