### PR TITLE
Trackers: dispatch.co.kr & laurenhi.com

### PR DESCRIPTION
**Pull request by ghost**
### URL: `https://www.dispatch.co.kr/2122214`
Screenshot:
Screenshot

### Network Logs
network1

If you try visiting `https://piclick.kr`, you will be redirected to `https://www.piclick.me`.

### CODE REVIEW

**Comment by Yuki2718** [comment]
@piquark6046 Not related to this, but I see some unblocked analytics at `https://laurenhi.com/product/detail.html?product_no=22790&psr=reco_ai`. Can you investigate and make PR?

**Comment by piquark6046** [comment]
> 
> 
> @piquark6046 Not related to this, but I see some unblocked analytics at `https://laurenhi.com/product/detail.html?product_no=22790&psr=reco_ai`. Can you investigate and make PR?

Please review 0ad773c525a95d17656e71fb4d8b38a3ad928043.

**Comment by Yuki2718** [comment]
@piquark6046 Currently I'm busy for some other staff (so I asked you), but I see `https://log22.makeshop.co.kr/ms.log?` and `https://laurenhi.com/exec/front/eclog/main/?` too. Can't take time to investigate if they should and can safely be blocked.

**Comment by piquark6046** [comment]
> 
> 
> @piquark6046 Currently I'm busy for some other staff (so I asked you), but I see `https://log22.makeshop.co.kr/ms.log?` and `https://laurenhi.com/exec/front/eclog/main/?` too. Can't take time to investigate if they should and can safely be blocked.

Done.

**Comment by Yuki2718** [comment]
Thanks!

**Pull request closed without merging**
