### PR TITLE
Logger: youtube.com

### PR DESCRIPTION
**Pull request by ghost**
### URLs
https://www.youtube.com/watch?v=gZBh00N5Qp0
https://www.youtube.com/watch?v=pMorI1_U5Zk

### Screenshots
Screenshot
Screenshotappera

### CODE REVIEW

**Comment by piquark6046** [comment]
#82607

**Comment by piquark6046** [comment]
This is how I reproduce:
1. Watch a video fully.
2. Click one of videoes recommended by YouTube.
Screenshot

3. Watch the video fully.
4. Click Back button on your browser.

**Comment by Alex-302** [comment]
This is not ayanytics. When it is blocked, current position is not saved.

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/83258#issuecomment-841662134

Ok.

**Pull request closed without merging**
