### PR TITLE
fix #76281 nxload.com

### LINKED ISSUE #76281: nxload.com
### Issue URL (Anti Adblock Script)
 [https://nxload.com/v/AIk1GNLrrT2c](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fnxload.com%2Fv%2FAIk1GNLrrT2c)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.6 nightly 19
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (180), <br>Block Push API, <br>Block Location API
DNS filtering: | server: `https://dns-unfiltered.adguard.com/dns-query`<br>filters: `User rules`
Filters: | <b>Ad Blocking:</b><br/> EasyList, <br/>Peter Lowe's Blocklist, <br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> EasyPrivacy, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> Adblock Warning Removal List, <br/>I don't care about cookies, <br/>EasyList Cookie List, <br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/> Online Malicious URL Blocklist, <br/>Spam404, <br/>NoCoin Filter List
Custom filter subscriptions: | https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt,<br>https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt

### PR DESCRIPTION
**Pull request by wout-codes**
#76281
The video doesn't even work for me without AdGuard.

### CODE REVIEW

**Comment by zloyden** [comment]
It seems that they have a broken adb detection, even without AdGuard I can see it.
Try this `nxload.com#%#//scriptlet("prevent-eval-if", "adbd")` on your end.

**Comment by wout-codes** [comment]
> It seems that they have a broken adb detection, even without AdGuard I can see it.
> Try this `nxload.com#%#//scriptlet("prevent-eval-if", "adbd")` on your end.

Yeah you got it. Let me check. Btw, how to use Eval if?

**Comment by zloyden** [comment]
[There](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#scriptlets) is a useful information about scriptlets.

**Comment by wout-codes** [comment]
Nice magic @zloyden. Video works fine and no AdBlocker detection.

**Comment by zloyden** [comment]
Ok, then exchange your rule to this one. 
But their webmasters should fix the detection - it's broken.

**Comment by wout-codes** [comment]
Btw, how to use it? I don't understand by eval matching payload in the information given by you.

**Comment by zloyden** [comment]
Just follow this [information](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#prevent-eval-if).
But if you have more questions about this scriptlet, @slavaleleka can help you.

**Review by zloyden — APPROVED** [review]

**Comment by wout-codes** [comment]
@zloyden Will it work if craft the rule like this? `nxload.com#%#//scriptlet("prevent-eval-if", "p,a,c,k,e,d")`

**Comment by zloyden** [comment]
If the script have `p,a,c,k,e,d` in `eval`, it should work.

**Comment by wout-codes** [comment]
@zloyden While testing my rules, with AdGuard for Windows, after a few refresh, this came in screenshot.

<details>

image
</details>

**Comment by zloyden** [comment]
Hm, strange. I'd offer you to contact with @slavaleleka about the scriptlet.

**Comment by wout-codes** [comment]
> about the scriptlet.

Why though? I learned it myself already, and practiced it with a more websites.

**Pull request merged**
