### PR TITLE
Update specific.txt

### PR DESCRIPTION
**Pull request by wout-codes**
They changed their code for some websites not all. So we do not what are the websites changed. Adding a similar rule would fix the problems for sites that were changed in code. @zloyden Please take a look.

### CODE REVIEW

**Comment by zloyden** [comment]
@wout-codes what about this rule `##div[class^="justify-bro"]`?

**Comment by wout-codes** [comment]
> @wout-codes what about this rule `##div[class^="justify-bro"]`?

@zloyden Hi!
Both works.

**Comment by zloyden** [comment]
> > @wout-codes what about this rule `##div[class^="justify-bro"]`?
> 
> @zloyden Hi!
> Both works.

Oh, hi! Well, please exchange original and your rules with `##div[class^="justify-bro"]`

**Comment by wout-codes** [comment]
> > > @wout-codes what about this rule `##div[class^="justify-bro"]`?
> > 
> > 
> > @zloyden Hi!
> > Both works.
> 
> Oh, hi! Well, please exchange original and your rules with `##div[class^="justify-bro"]`

Is it okay now?

**Comment by zloyden** [comment]
One more thing. Remove this too `! ##.justify-brow` with the whole rule.

**Comment by wout-codes** [comment]
> One more thing. Remove this too `! ##.justify-brow` with the whole rule.

Done please check @zloyden.

**Comment by zloyden** [comment]
Ok, well done. @wout-codes thanks!

**Review by zloyden — APPROVED** [review]

**Pull request merged**
