### PR TITLE
pandora.tv

### PR DESCRIPTION
**Pull request by piquark6046**
### To avoid invalid pull requests, please check and confirm following terms

- [X] This is not an ad/bug report;
- [X] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [X] I have performed a self-review of my own changes;
- [X] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [X] Filters maintenance.

### Enter the issue address

 - https://github.com/List-KR/List-KR/issues/572

### Add your comment and screenshots

The pandora.tv service will be ended in February 1st, 2023 (KST).
http://www.pandora.tv/company/notice/view/1/1178

### Terms

- [X] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Review by Sergey-Lyapin — COMMENTED** [review]
Let's keep these rules until February 1.

**Comment by Alex-302** [comment]
@Sergey-Lyapin 
> Let's keep these rules until February 1.

Why?

**Comment by Sergey-Lyapin** [comment]
> @Sergey-Lyapin
> 
> > Let's keep these rules until February 1.
> 
> Why?

Because this site still works. Or these rules are outdated?

**Comment by Alex-302** [comment]
Ok, I see
image

**Review by Alex-302 — APPROVED** [review]

**Review by zloyden — APPROVED** [review]

**Review by Sergey-Lyapin — APPROVED** [review]

**Pull request merged**
