### PR TITLE
fix #78507 20minutos.es

### LINKED ISSUE #78507: www.20minutos.es
### Issue URL (Anti Adblock Script)
 [https://www.20minutos.es/noticia/4633670/0/trenes-repletos-aeropuertos-llenos-ninos-darias-no-responde-congreso-exodo-previo-semana-santa/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.20minutos.es%2Fnoticia%2F4633670%2F0%2Ftrenes-repletos-aeropuertos-llenos-ninos-darias-no-responde-congreso-exodo-previo-semana-santa%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.34
Browser: | Firefox
Stealth mode: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Adblock Warning Removal List, <br/>I don't care about cookies<br/><br/><b>Language-specific:</b><br/> AdGuard Spanish/Portuguese

### PR DESCRIPTION
**Pull request by wout-codes**
#78507
Anti-Adblock fixed in a generic rule.

### CODE REVIEW

**Review by BlazDT — CHANGES_REQUESTED** [review]
Layout is broken on mobile view (in desktop view with open dev tools too).
Adblock caused by third-party filter.

**Comment by wout-codes** [comment]
@BlazDT I can't reproduce. 

<details>

image
image

**Comment by wout-codes** [comment]
@BlazDT In mobile view without rule:
<details>

image
</details>

<details>

image
</details>

**Comment by AdamWr** [comment]
I can reproduce it. 
On the main page part of the website is hidden.
<details><summary>Screenshot</summary>

image

</details>

**Comment by AdamWr** [comment]
It seems that these rules should work fine:
```
20minutos.es##.axds > .henneoHB
20minutos.es#$#div#axds-Top { min-height: 0 !important; }
```

**Comment by wout-codes** [comment]
I am not sure why. I can't reproduce it still, but I will add the rules.

**Comment by wout-codes** [comment]
@AdamWr This works too: `20minutos.es###axds-Top`. Which one should I add:

```
20minutos.es##.axds > .henneoHB
20minutos.es#$#div#axds-Top { min-height: 0 !important; }
20minutos.es###axds-Top
```

**Comment by AdamWr** [comment]
`20minutos.es###axds-Top` causes that part of the website is hidden (on the main page `https://www.20minutos.es/` in mobile view), at least on my side.
Please add these two rules:
```
20minutos.es##.axds > .henneoHB
20minutos.es#$#div#axds-Top { min-height: 0 !important; }
```

**Comment by AdamWr** [comment]
Please move `20minutos.es#$#div#axds-Top { min-height: 0 !important; }` to `general_extensions.txt`:
https://github.com/AdguardTeam/AdguardFilters/blob/42bdf9a564fa366c3e993f938b675472b193c93e/SpanishFilter/sections/general_extensions.txt#L213-L218
And add link to issue in comment:
```
! https://github.com/AdguardTeam/AdguardFilters/issues/78507
20minutos.es#$#div#axds-Top { min-height: 0 !important; }
```

**Pull request closed without merging**
