### PR TITLE
fix #75372 lacalleochotv.org

### LINKED ISSUE #75372: lacalleochotv.org
### Issue URL (Anti Adblock Script)
 [http://lacalleochotv.org/canal-4-online-en-directo-gratis/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Flacalleochotv.org%2Fcanal-4-online-en-directo-gratis%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.6 nightly 18
Browser: | Opera
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (180), <br>Block Push API, <br>Block Location API
DNS filtering: | server: `https://dns-unfiltered.adguard.com/dns-query`<br>filters: `User rules`
Filters: | <b>Ad Blocking:</b><br/> EasyList, <br/>Peter Lowe's Blocklist, <br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> EasyPrivacy, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> Adblock Warning Removal List, <br/>I don't care about cookies, <br/>EasyList Cookie List, <br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/> Online Malicious URL Blocklist, <br/>Spam404, <br/>NoCoin Filter List<br/><br/><b>Language-specific:</b><br/> AdGuard Spanish/Portuguese
Custom filter subscriptions: | https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

### PR DESCRIPTION
**Pull request by wout-codes**
#75372

### CODE REVIEW

**Review by AdamWr — APPROVED** [review]

**Comment by AdamWr** [comment]
If blocked request is just a bait and it's used on other websites as well, then I think it can be added for all platforms.

**Comment by wout-codes** [comment]
@AdamWr Can you tell me how to use this `!+ PLATFORM(ios, ext_android_cb, ext_safari)`? and when can I use. If I don't use it what should the order be? Scriptlet first or whitelisting files to kill anti-adblock?

**Comment by AdamWr** [comment]
This hint "`!+ PLATFORM(ios, ext_android_cb, ext_safari)`" means that rule will be only available in filter list for AdGuard for iOS, AdGuard Content Blocker for Android and AdGuard Extensions for Safari.

>when can I use it?

For example, in case if you need to unblock ad request to fix anti-adblock script, for platforms which do not support scriptlets and redirect rules.
If you unblock only a bait then in my opinion it can be added for all platforms.

>If I don't use it what should the order be? Scriptlet first or whitelisting files to kill anti-adblock?

It depends on the case, on `lacalleochotv.org` both rules will be applied.

**Comment by wout-codes** [comment]
> It depends on the case, on lacalleochotv.org both rules will be applied.
@AdamWr Will the whitelisted rule get injected first in platforms with Scriptlet support or the scriptlet will get injected first in platforms with Scriptlet support?

**Comment by AdamWr** [comment]
In this case anti-adblock will be fixed by the scriptlet, but the request will be unblocked by the whitelisted rule anyway.

**Comment by wout-codes** [comment]
@AdamWr 
Then how about for this?
`example.com#@#.ad-top`
`example.com#%#//scriptlet("set-constant", "adblock", "false")`
Same case?

**Comment by AdamWr** [comment]
`example.com#@#.ad-top` doesn't unblock any request, it unhides hidden element.
Better use a real case, because it may depends on how anti-adblock script looks like.

**Comment by wout-codes** [comment]
> `example.com#@#.ad-top` doesn't unblock any request, it unhides hidden element.
> Better use a real case, because it may depends on how anti-adblock script looks like.

@AdamWr 
It's from my PR (https://github.com/AdguardTeam/AdguardFilters/pull/75420), also, to reproduce it requires an account. 
Here is the fix I could write: 
```
friendproject.net#@#.ad-top
friendproject.net#%#//scriptlet("set-constant", "adblock", "false")
```

**Comment by AdamWr** [comment]
So I would have to check it to answer, but if it doesn't unblock ads, then I think it's fine to add it for all platforms without hints.

**Pull request merged**
