### PR TITLE
Dead domains (1)

### PR DESCRIPTION
**Pull request by mrrtarlan**
bifilmizlesene.net
limitsizfilmizle.net
rexfilmizle.com
favorifilm.com
hdfilmizle3.com
filmihdizlet.com
fullizlefilmizle.com
hdcehennem.com
cilekfilm.com
wfilmizle.net
filmkusu.org (redirects to filmizlemetv.com which has active rules in filter; so rules related to this domain are useless)
kalitelifilmizle.net (site content are different, maybe site view changed)
ifilmizle.org
dafflix.com
hdfilmcehenemi.net
filmoyunindir.com
erotikfilms.net (this domain redirects to erotikfilmizle1.com, so rules related to this domain are useless)
erotiksexfilmizle.com
filmsokagi.org
full1080pfilmizle.com

### CODE REVIEW

**Comment by gork7777** [comment]
Some domains may be located in files other than the language specific file. That's why you shouldn't just look at the language specific file.

**Comment by mrrtarlan** [comment]
> Some domains may be located in files other than the language specific file. That's why you shouldn't just look at the language specific file.

is there any way to edit rules from one place? as you said, currently i can only edit just one section and that's why there should be rules in other filters

**Comment by gork7777** [comment]
@mrrtarlan It's better do not make PR's about dead domains, you can just report issues about dead domains and devs will check and remove them.

**Review by krystian3w — APPROVED** [review]

**Review by zloyden — APPROVED** [review]
For such cases, better do it with different commits next time.
For instance
```
example.com - dead
example1.com - dead
```

**Pull request merged**
