### PR TITLE
kurelife.jp

### PR DESCRIPTION
**Pull request by spiri-leo**
Issue: #108817

### CODE REVIEW

**Review by Yuki2718 — CHANGES_REQUESTED** [review]
Please add the domain to `amp-welt-de.cdn.ampproject.org##.c-social` as well.

**Comment by spiri-leo** [comment]
> Please add the domain to `amp-welt-de.cdn.ampproject.org##.c-social` as well.

Fixed.

**Review by Yuki2718 — CHANGES_REQUESTED** [review]
Why did you remove `kurelife.jp##.p-recipedt1__social`? They're both needed.

**Comment by spiri-leo** [comment]
> Why did you remove `kurelife.jp##.p-recipedt1__social`? They're both needed.

Fixed.

**Review by Yuki2718 — APPROVED** [review]

**Review by zloyden — APPROVED** [review]

**Pull request merged**
