### PR TITLE
fix #77780 articlix.com

### LINKED ISSUE #77780: articlix.com
### Issue URL (Anti Adblock Script)
 [https://articlix.com/new-day-is-new-life-214](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Farticlix.com%2Fnew-day-is-new-life-214)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.31
Browser: | Chrome
Stealth mode: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard Spanish/Portuguese

### PR DESCRIPTION
**Pull request by wout-codes**
#77780
Link: `https://fc.lc/7OorS86`

### CODE REVIEW

**Comment by wout-codes** [comment]
@AdamWr You can check these.

**Review by AdamWr — APPROVED** [review]

**Comment by wout-codes** [comment]
@AdamWr Is it possible to make these scriptlet better? `#%#AG_onLoad(function() { setTimeout(function() { var el = document.querySelector("#surl"); if(el) { el.classList.remove("disabled"); var text = jQuery.ajax({url:domain,method:"POST",dataType:"json",data:jQuery("#form12")["serialize"]()}); setTimeout(function() { var texturl = text.responseText.split("https")[1]; texturl = texturl.split('"')[0]; el.href="https" + texturl; el.text = "Get Link"; el.classList.add("btn-success"); el.click();}, 1000);  } }, 500); });`. It sometimes work with AdGuard for Windows and sometimes it doesn't.

**Comment by AdamWr** [comment]
It seems that sometimes it can't be skipped immediately, because server return `Bad Request`.
<details><summary>Screenshot</summary>

image

</details>

I will change this rule, so it should try to skip it again until server return destination link. From what I can see, it will be skipped after about 6 seconds.

**Comment by wout-codes** [comment]
Yeah, you're right.

**Pull request merged**
