### PR TITLE
Fix regex for uBO (addresses https://github.com/DandelionSprout/adfil…

### PR DESCRIPTION
**Pull request by Yuki2718**
…t/discussions/163#discussioncomment-4117315)

# Creating the pull request

> Please include a summary of the change and which issue is fixed\
> If the related issue does not exist in our repository, please create it before making pull request\
> It is highly recommended to use our [Web Reporting Tool](https://kb.adguard.com/en/technical-support/reporting-tool) instead of creating an issue on GitHub directly\
> Please note, that we verify every pull request manually, so it may take time to apply it

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [x] Filters maintenance.

### Enter the issue address

https://github.com/DandelionSprout/adfilt/discussions/163#discussioncomment-4117315
It turned out uBO requires `-` to be escaped if it's at the end.

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Comment by Alex-302** [comment]
Our regexes are valid. The most of filters have rules with `-]` in regexes.

**Comment by Yuki2718** [comment]
Then how about `NOT_PLATFORM(ext_ublock)`? uBF has counterparts of them anyway.

**Comment by scripthunter7** [comment]
I think that this issue can also occur in the case of many filter lists, since `-]` is a valid regex, so this PR does not solve the problem itself. Maybe a better solution would be to replace `-]` with `\-]` internally before the regexp is passed to the [analyzer](https://github.com/foo123/RegexAnalyzer/blob/master/src/js/Regex.js).

**Comment by Yuki2718** [comment]
So move to https://github.com/AdguardTeam/FiltersCompiler ?

**Comment by scripthunter7** [comment]
> So move to https://github.com/AdguardTeam/FiltersCompiler ?

I think this issue is related to the uBlock parser:
https://github.com/gorhill/uBlock/blob/master/src/js/static-filtering-parser.js#L26

I guess uBO also uses lists that don't go through the AG's Filters Compiler, and those lists can easily use `-]` in regexps.

**Comment by Yuki2718** [comment]
@gorhill

**Comment by scripthunter7** [comment]
By the way, here is the problematic part in the analyzer library:

https://github.com/foo123/RegexAnalyzer/blob/807f106914ed8b650d792d7a158f63040fd579c3/src/js/Regex.js#L1079-L1099

When line 1094 checks whether the currently iterated character is a hyphen, you need a lookahead in which you check whether the next character sequence is whitespaces + closing bracket.

But this seems like a rather outdated / low documented / low tested library, I think there are much more modern ones.

**Comment by scripthunter7** [comment]
Without any warranty, something like this: https://github.com/scripthunter7/RegexAnalyzer/blob/master/src/js/Regex.js

**Comment by gorhill** [comment]
We discussed this a long time ago, I said I would fix this eventually, we should bother AdGuard's repo just because I take long to fix stuff which is one thing among all the rest I need to work on.

**Comment by danny0838** [comment]
@gorhill About the [commit](https://github.com/gorhill/uBlock/commit/d51b7e082b73db745a1f8321e65b086902d80d80#diff-8a8c24285f93dbeb182e3383fd0907004bcd92ae6e2009fcb9c84e1dd5877b7c) (I cannot leave a comment in the commit page, seems to be an issue of GitHub?):

I wonder if modifying the regex.js library without populating to the upstream is a good idea. Also this doesn't seem to deal with the `[-abc]` case.

I would recommend preprocessing regex strings by escaping every `-` with `\-` (exclude already escaped ones like `\-`, of course) before sending to the analyzer instead.

**Comment by krystian3w** [comment]
>  (I cannot leave a comment in the commit page, seems to be an issue of GitHub?)

That is limitation to disable open issues in code of repository.

Sometimes someone can turn it off - once I managed to give a reaction to PR and after a few days someone blocked it undo/new.

**Pull request closed without merging**
