### PR TITLE
fix #78704, #78776

### LINKED ISSUE #78704: kiemlua.com
### Issue URL (Anti Adblock Script)
[NSFW] [https://kiemlua.com/movavi-picverse-photo-editor-phan-mem-chinh-sua-anh/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fkiemlua.com%2Fmovavi-picverse-photo-editor-phan-mem-chinh-sua-anh%2F)

### [NSFW] Screenshots
<details>
  <summary>Screenshot 1</summary>

  [Screenshot 1](https://reports-img.adguard.com/3fbnYgL.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.1.1
Browser: | Safari
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads, <br/>EasyList<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection, <br/>EasyPrivacy, <br/>Fanboy's Anti-Facebook List<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Adblock Warning Removal List<br/><br/><b>Language-specific:</b><br/> ABPVN List

### PR DESCRIPTION
**Pull request by wout-codes**
#78704, #78776

### CODE REVIEW

**Comment by Yuki2718** [comment]
Came across another domain `luutruhay.net` only once, but now I don't have enough time.

**Comment by Yuki2718** [comment]
There are even more variants. I suggest to add [WIP] in the title until everything gets ready.

**Comment by wout-codes** [comment]
@Yuki2718 Please bail me out. I can't reproduce anymore variants.

**Comment by Yuki2718** [comment]
@wout-codes Still under investigation, but I'll tell you what to add.

**Comment by wout-codes** [comment]
Yes, once.

**Comment by wout-codes** [comment]
@Yuki2718 Should this be added? `linkcc.pro`

**Comment by Yuki2718** [comment]
Really regretting didn't investigate at the time.
`linkcc.pro` -> standard popMagic filters, blurred (`##.banner-inner` is not needed as AG has `###fbox-background`)
`thaitrieuvi.live#%#//scriptlet('adjust-setInterval', 'count', '', '0.02')`
`thaitrieuvi.live##center + .mh-clearfix.mh-wrapper`
`linkcc.pro` -> standard bab filters
`megalink.vip#%#//scriptlet('prevent-addEventListener', 'click', 'popunder')` vip may be wildcard.
`||adcheap.network^`
Will add few more cosmtic later.

**Comment by wout-codes** [comment]
@Yuki2718 Gotta tweak this: https://linkcc.pro/PKBH

<details>

image
</details>

**Comment by wout-codes** [comment]
@Yuki2718 Does this work? `thaitrieuvi.live#%#//scriptlet("adjust-setInterval", "counter", "2000", "0.02")`

**Comment by Yuki2718** [comment]
> Does this work? `thaitrieuvi.live#%#//scriptlet("adjust-setInterval", "counter", "2000", "0.02")`

No, the it's 'count' (not 'counter') and '1000'.

**Comment by Yuki2718** [comment]
Did you see `linkcc.pro/assets/methods/hereads.png` thing? I can't find existing cosmetic filter for this. Maybe
`linkcc.pro##div[style="text-align:center"] > a > img`

**Comment by Yuki2718** [comment]
Okay, add `megalink.vip` to the `##.box-main > center > a > img` filter and you're done!

**Comment by wout-codes** [comment]
Working on this and I am not sure how. https://github.com/AdguardTeam/AdguardFilters/pull/78705#issuecomment-809355314

**Comment by Yuki2718** [comment]
If you mean boosting count on `linkcc.pro`, I think it's impossible (breaks the link).

**Comment by wout-codes** [comment]
> If you mean boosting count on `linkcc.pro`, I think it's impossible (breaks the link).

Anti-adblock. It doesn't show the button to go to the desired link unless adblocker disabled.

**Comment by Yuki2718** [comment]
Yeah, reproduced. `linkcc.pro#@#.banner-468x60`

**Comment by wout-codes** [comment]
> Yeah, reproduced. `linkcc.pro#@#.banner-468x60`

Yep, I got this, but I am tryna fix it without whitelisting it.

**Comment by Yuki2718** [comment]
If single cosmetic whitelist solves the issue, it's better than any other fixes.

**Comment by wout-codes** [comment]
@Yuki2718 As said, hard work paid off
```
linkcc.pro#@#.banner-468x60
linkcc.pro#%#//scriptlet("remove-attr", "href|target", "a[href][target='_blank']")
||linkcc.pro/assets/methods/hereads.png
```

**Comment by Yuki2718** [comment]
Hmmm, I don't see `a[target='_blank']`.

**Comment by wout-codes** [comment]
@Yuki2718 Link: `https://linkcc.pro/PKBH`. Add your whitelist rule first, then check.
Check this screenshot.

<details>

image

**Comment by Yuki2718** [comment]
@wout-codes Probably better to use simple cosmetic filter to hide that.

**Comment by wout-codes** [comment]
@Yuki2718 I have tried that, that's why it took about an hour to finalise everything. It just blocks the whole link button. Not worth it.

**Comment by Yuki2718** [comment]
@wout-codes On my end `linkcc.pro##.banner-inner > div[style="text-align:center"] > a[target="_blank"]` works without bringing back the anti-adb.

**Comment by wout-codes** [comment]
I get anti-adblock again. I am guessing that the arrow must be unblocked.

**Comment by wout-codes** [comment]
> @wout-codes On my end `linkcc.pro##.banner-inner > div[style="text-align:center"] > a[target="_blank"]` works without bringing back the anti-adb.

I will add it. Seems like it's working now.

**Comment by wout-codes** [comment]
@Alex-302 @AdamWr Could you please check? Reports coming in.

**Comment by Yuki2718** [comment]
Optional but `linkcc.pro#%#//scriptlet("abort-current-inline-script", "String.fromCharCode", "decodeURIComponent")` can be added to prevent some calls for ads.

**Comment by wout-codes** [comment]
Yeah, I will add it. Site will be much cleaner.

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
