### PR TITLE
Fix #73209, #73210 and #73211

### LINKED ISSUE #73209: thekat.cc
### Issue URL (Annoyance)
 [https://thekat.cc/full/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fthekat.cc%2Ffull%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.31
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Remove X-Client-Data header from HTTP requests, <br/>Strip URLs from tracking parameters, <br/>Self-destructing third-party cookies (2880)
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads, <br/>EasyList, <br/>Peter Lowe's Blocklist<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection, <br/>EasyPrivacy<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Adblock Warning Removal List, <br/>I don't care about cookies, <br/>EasyList Cookie List<br/><br/><b>Security:</b><br/> Online Malicious URL Blocklist, <br/>Spam404, <br/>NoCoin Filter List<br/><br/><b>Other:</b><br/> AdGuard DNS<br/><br/><b>Language-specific:</b><br/> AdGuard Spanish/Portuguese

### PR DESCRIPTION
**Pull request by wout-codes**
#73209, #73210 and #73211

### CODE REVIEW

**Review by zloyden — APPROVED** [review]

**Comment by wout-codes** [comment]
@zloyden Please take a look again. Ads and pop-ups appear now again.

**Comment by wout-codes** [comment]
@zloyden Please take a look again. Ads and pop-ups appear now again.

**Comment by zloyden** [comment]
Fixed.

**Comment by wout-codes** [comment]
> Fixed.

Thanks.

**Comment by wout-codes** [comment]
@zloyden Take a look again now. There are ads and pop-ups again.

**Comment by wout-codes** [comment]
@zloyden Take a look again now. There are ads and pop-ups again.

**Comment by wout-codes** [comment]
@zloyden Take a look again now. There are ads and pop-ups again.

**Comment by zloyden** [comment]
Ok, fixed. But I think for another case, we'll wait for a while, because they're starting to avoid us.

**Comment by wout-codes** [comment]
> Ok, fixed. But I think for another case, we'll wait for a while, because they're starting to avoid us.

I think they are spying on uAssets and AdGuard Content Blocking Filters. They change their code when it's fixed either uBO or AdGuard Filter Devs.

**Comment by wout-codes** [comment]
@zloyden Pop-ups are fixed. There are ads now.

**Comment by wout-codes** [comment]
@zloyden Pop-ups in this website `https://shortlinkpay.com/276a8FW` are blocked with AdGuard AdBlocker extension but not with AdGuard for Windows. Do you know the problem?

**Pull request merged**
