### PR TITLE
fix #71666 thetimes.co.uk

### LINKED ISSUE #71666: thetimes.co.uk
### Issue URL (Annoyance)
 [https://www.thetimes.co.uk/article/star-wars-the-force-awakens-empire-leicester-square-lfzcgvgc3mv](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.thetimes.co.uk%2Farticle%2Fstar-wars-the-force-awakens-empire-leicester-square-lfzcgvgc3mv)
### Comment
Username: @Rakleed
> Кнопка “Start your free trial” снизу экрана

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.0.4
Browser: | Safari
System wide filtering: | disabled
Simplified filters: | disabled
AdGuard DNS: | None
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Russian

### PR DESCRIPTION
**Pull request by stanislav-atr**
#71666

### CODE REVIEW

**Review by zloyden — COMMENTED** [review]
I guess those rules for cookies don't need to added. Try `||cdn.privacy-mgmt.com^$third-party,important` on your end.

**Comment by zloyden** [comment]
Hm, it's originally caused by this one. @BlazDT can you tell more about this rule? Maybe it needs a domain restriction `$domain=techbook.de`? Also I see a similar rule for `techbook.de`.
```
! techbook.de - social feeds cannot be activated
@@||cdn.privacy-mgmt.com/wrapper/*/gdpr/native-message
```

**Comment by BlazDT** [comment]
> ! techbook.de - social feeds cannot be activated
> @@||cdn.privacy-mgmt.com/wrapper/*/gdpr/native-message

For the few sites I tested that request was only made when a previous site specific url was unblocked, therefore I made that rule non-site specific.

**Comment by zloyden** [comment]
@stanislav-atr according to the @BlazDT response, please remove your cookie rules.

**Review by zloyden — APPROVED** [review]

**Pull request merged**
