### PR TITLE
hironaka-yoshio.net

### PR DESCRIPTION
**Pull request by SKEIDs**
https://github.com/AdguardTeam/AdguardFilters/issues/102125

### CODE REVIEW

**Review by zloyden — COMMENTED** [review]
I don't see any statistics for the website.

**Comment by SKEIDs** [comment]
> I don't see any statistics for the website.

excuse me.
how can I research the statistics (visitors) of the website?

**Comment by zloyden** [comment]
For most cases, using similarweb is enough.

**Comment by SKEIDs** [comment]
> 
I see.
Thank you for teach me.

**Pull request closed without merging**
