### PR TITLE
fix #78042 freshdesk.com

### LINKED ISSUE #78042: freshdesk.com
### Issue URL (Annoyance)
 [https://freshdesk.com/freshdesk-demo?utm_source=emailfooter&referrer=coldturkey.freshdesk.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Ffreshdesk.com%2Ffreshdesk-demo%3Futm_source%3Demailfooter%26referrer%3Dcoldturkey.freshdesk.com)
### Comment
Username: `@rakleed`
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.1.0
Browser: | Safari
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Russian

### PR DESCRIPTION
**Pull request by wout-codes**
#78042

### CODE REVIEW

**Comment by wout-codes** [comment]
@Sergey-Lyapin What's the point of creating Pull Requests, when you ignore it and add it directly?

**Comment by Sergey-Lyapin** [comment]
@wout-codes oops, I didn't notice the PR, sorry

**Comment by wout-codes** [comment]
@Sergey-Lyapin Then what's the point of making PR? You have missed around five of my PRs. Completely unethical. You're just wasting my time. By what logic it should not be merged?

**Comment by Sergey-Lyapin** [comment]
@wout-codes
I'm sorry about that, I'll be more careful. 
It wasn't merged because I had already fixed it by myself.

**Comment by wout-codes** [comment]
@Sergey-Lyapin I don't care on what you are saying. You merge all you have closed some time ago. Careless.

**Pull request closed without merging**
