### PR TITLE
fix #56868 dust-sounds.com

### LINKED ISSUE #56868: dust-sounds.com
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

URL: `http://dust-sounds.com/`
Issue: all sound-players are hidden.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

dust-sounds1

</details><br/>

* **Expected behaviour**: 

They should be shown.

<details><summary>Screenshot:</summary>

dust-sounds2

</details><br/>

***Steps to reproduce the problem***:

Visit the site.

***System configuration***

**Filters:**

Base, Tracking, & Japanese

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               |Brave1.9.76
AdGuard version:                       | 3.4.31
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | Disabled

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

### PR DESCRIPTION
**Pull request by Yuki2718**
https://github.com/AdguardTeam/AdguardFilters/issues/56868

### CODE REVIEW

**Review by Sergey-Lyapin — CHANGES_REQUESTED** [review]
please add this domain with tilda before `##iframe[width="100%"][height="120"]` in banner_sizes.txt

**Comment by Yuki2718** [comment]
Done.

**Review by Sergey-Lyapin — APPROVED** [review]

**Comment by Alex-302** [comment]
> ##iframe[width="100%"][height="120"]

Why?

@Yuki2718  Please better make exclusion rule.

**Comment by Sergey-Lyapin** [comment]
> > please add this domain with tilda before ##iframe[width="100%"][height="120"] in banner_sizes.txt
> 
> Why?
> 
> ~@Yuki2718 Please better make exclusion rule.~
> Added directly.

@Alex-302 
Why these domains were added there? for this reason i requested to move the rule.

screen2

**Comment by Alex-302** [comment]
That rurel are old(more than 4 years)

**Pull request closed without merging**
