### PR TITLE
fix #75236 download.ipeenk.com

### LINKED ISSUE #75236: download.ipeenk.com
### Issue URL (Ads)
 [https://download.ipeenk.com/coreldraw-graphics-suite-x7-full-version.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdownload.ipeenk.com%2Fcoreldraw-graphics-suite-x7-full-version.html)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.31
Browser: | Chrome
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion

### PR DESCRIPTION
**Pull request by stanislav-atr**
#75236

### CODE REVIEW

**Comment by AdamWr** [comment]
I'm not sure if these links should be blocked. For example, this link to video tutorial seems to be okay (it redirects through url shortener or by something like that and then to `https://uptostream.com/6942wr5mu2cj`).
What about adding something like:
```
download.ipeenk.com#%#//scriptlet("prevent-addEventListener", "DOMContentLoaded", "adlinkfly_url")
```
so there will be a "real" links without url shortener?

**Comment by stanislav-atr** [comment]
@AdamWr, these URLs lead to the different domain and are also misleading, not being related to button' text or article topic.

**Comment by AdamWr** [comment]
@stanislav-atr Are you sure?
This link to video tutorial looks okay for me, it redirects to - `https://uptostream.com/6942wr5mu2cj`
This "article" is about CorelDraw (as far as I understand it is about not legal/cracked version and it's a different topic) and this video seems to be related to that.

**Comment by stanislav-atr** [comment]
I get redirected to this page
<details><summary>Screenshot:</summary>

image
</details><br/>
through this request
https://www.wts.pw/full/?api=6d9fef021662bd1707e6aa2c845186edbb1f8361&url=aHR0cHM6Ly91cHRvc3RyZWFtLmNvbS82OTQyd3I1bXUyY2o=&type=2

**Comment by AdamWr** [comment]
What if you add this rule to the user filter:
`download.ipeenk.com#%#//scriptlet("prevent-addEventListener", "DOMContentLoaded", "adlinkfly_url")`
and then click on this link?

**Comment by AdamWr** [comment]
On my end it looks like this.
Without rule:
<details><summary>Screenshot</summary>

image

</details>

With mentioned rule:
<details><summary>Screenshot</summary>

image

</details>

**Comment by AdamWr** [comment]
I still think that we shouldn't block it on iOS/Safari/Content Blocker.
If you go here - `https://www.wts.pw/full/?api=6d9fef021662bd1707e6aa2c845186edbb1f8361&url=aHR0cHM6Ly91cHRvc3RyZWFtLmNvbS82OTQyd3I1bXUyY2o=&type=2` then fill the captcha, wait 10 seconds and click on "Get Link" button, then you will be redirected to - `https://uptostream.com/6942wr5mu2cj`.

**Comment by Alex-302** [comment]
Without new rules I can get download links, without popups or another ads.

**Comment by Alex-302** [comment]
Any news?

**Comment by stanislav-atr** [comment]
@Alex-302, I still think we should  block these for content blockers.
@AdamWr, `download.ipeenk.com#%#//scriptlet("prevent-addEventListener", "DOMContentLoaded", "adlinkfly_url")` stopped working for me, could you please check this again?

**Comment by AdamWr** [comment]
>`download.ipeenk.com#%#//scriptlet("prevent-addEventListener", "DOMContentLoaded", "adlinkfly_url")` stopped working for me, could you please check this again

It works fine on my end.

Even if it redirects through some kind of url shorteners, the destination page is related to the content of the page, so why we should block these links in content blockers?

**Comment by Sergey-Lyapin** [comment]
@stanislav-atr

**Review by AdamWr — APPROVED** [review]

**Pull request merged**
