### PR TITLE
unyoo.jp

### PR DESCRIPTION
**Pull request by SKEIDs**
https://github.com/AdguardTeam/AdguardFilters/issues/103132

### CODE REVIEW

**Review by gork7777 — CHANGES_REQUESTED** [review]
Hey, if an existing rule field already exists, add that domain there.
`archive.vanityfair.com,tubefilter.com,101.ru,glavcom.ua,javhdx.tv##.socials`
Other one is fine.

**Comment by SKEIDs** [comment]
> Hey, if an existing rule field already exists, add that domain there. `archive.vanityfair.com,tubefilter.com,101.ru,glavcom.ua,javhdx.tv##.socials` Other one is fine.

I overlooked it. thank you.

**Review by Yuki2718 — APPROVED** [review]

**Review by zloyden — APPROVED** [review]

**Comment by zloyden** [comment]
Something is wrong with the branch. I've added changes directly, thanks for the contribution.

**Comment by Yuki2718** [comment]
> Something is wrong with the branch.

Maybe had to solve conflicts before deletion of the repo?

**Pull request closed without merging**
