### PR TITLE
Social TrackPara: webtoons.com

### PR DESCRIPTION
**Pull request by ghost**
## URL
https://www.webtoons.com/en/comedy/cursed-princess-club/ep-118-piano-face-off-part-1/viewer?title_no=1537&episode_no=126

### TrackPara
1. Visit provided URL.
2. Click one of the highlighted buttons in the following screenshot.
<details>
<summary>Screenshot</summary>

ScreenshotB

</details>

3. Then, find `https://cc.loginfra.com/cc?` on network section of DevTool.

### Social
<details>
<summary>Screenshot</summary>

ScreenshotA

</details>

## Similarweb Web Traffic Report
https://www.similarweb.com/website/webtoons.com/#overview

### CODE REVIEW

**Comment by Alex-302** [comment]
Cannot reproduce params. Need sample values, similar to real.

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/100181#issuecomment-969283329 @Alex-302
Here you are.
<details>
<summary>Screenshot</summary>

Screenshot

</details>

**Comment by Alex-302** [comment]
> If you need a HAR file, please tell me that.

Yes, please send to filters@adguard.com (maybe better from two browsers, I want to compare the values)

**Comment by piquark6046** [comment]
@Alex-302 Sent. Please check it out.

**Comment by Alex-302** [comment]
@piquark6046 It seems we can just block `cc.loginfra.com`. Please test `||cc.loginfra.com^$third-party`

**Comment by piquark6046** [comment]
@Alex-302 
But, `||cc.loginfra.com^$third-party` does not block `https://cc.ioginfra.com/cc` that redirects a visitor to other page of webtoons.com.

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
