### PR TITLE
Add a new regex filter to cover another class of revolving adservers

### PR DESCRIPTION
**Pull request by Yuki2718**
https://github.com/easylist/easylist/issues/6476
`https://regex101.com/r/1g9Jh6/1`
Once mentioned in Slack, then FP reported in https://github.com/uBlockOrigin/uAssets/issues/8280 so improved with `$match-case`. So far no FP report in this version and I think it's worth being added to AG too.

### CODE REVIEW

**Comment by Alex-302** [comment]
@Yuki2718 Could you please show full URLs from tests?

**Comment by Yuki2718** [comment]
@Alex-302 They're full URL (`https://www.animefenix.com/` redirects me to `https://www.animefenix.com/?__cf_chl_managed_tk__=41b568f19d1bcedddec33d7360a9708377bc19ee-1622566576-0-AW5Hm8v9MHnJThTm1qPqRM6HTaoUlpfGL-mKQnADPk-Y1zkN3lYoyaONjuWWS6fg8v2JSwU88LrMi6DdFNPuRBOOV5HiKOGaEQJKVGy_HNeRqBW075P9ZmNy2FggIf-yIDQgesdXxUg3rR3L3qJykDU-FGY9ojyKJJrGBKy5sdiVGH-HjZvXg1WfKaRnTRNKmaitptzFV-ScfJ0XWnYT1kxjONFEyA4xaqlY0gf80SOvaJOa6VjgIjfcBewlI-YwoDddirTB19hZaEj04xmuWGQfEvqKCC1AuTm8VvZ-_P8cbt_0B62lHTO-6DQ7CDeU2ImQa1uTdFsKcyGbJB8n2qYaQaEHC7NCKbGmEMQNAXEPH_XLv_SoryBn9guwuo1coimgFh4bE_DDKOsA9pqNs_gMXu-qPxfrBba27UyzmBHGN776PvTBZ7m_XiWIMRdoEm0ZV6qXUGQwZ0FuSWvumw9lwCw1iue8t7VpZxsYPEYEcrUxc28qTjV4ghsLFxiYILZYXQJedAFwZ86449mgxHZNvRVk9Nyo05baAUlQCMI6OZY3cd7KQOHkePIFGPj_e7avFLRvjd_sezDjt99uTh-Mr85Y8rmyZnwZxZuAdYKo`) but ad servers were already changed. I'll update tests.

**Comment by Alex-302** [comment]
@ameshkov May we add it?

**Comment by ameshkov** [comment]
@Yuki2718 I've read the original issue, but I don't understand, why there's no `$domain` restriction? As I understand, it was tested on a limited number of websites anyway

**Comment by zloyden** [comment]
Maybe, there are many domains, but I prefer to use `$domain` for regex rules.
@Yuki2718 which sites need this rule? Please provide a list of them.

**Comment by Yuki2718** [comment]
@ameshkov @zloyden Because this is used by too many pirate sites, short links etc. and they change domain too often. URLs @ghajini listed were just a fraction, in fact animefenix is not included and, say, now in #84655 there are some more examples: `https://regex101.com/r/YdVN2W/1` Lucky to me as I wanted to show `(\?_=\d+)?` part is necessary. If it's limited to certain domain, there's no need to add another regex - just add them to `/^(?!.*(bootstrapcdn.com` filter.

**Comment by ghajini** [comment]
Its used on so many sites i mentioned (check comments,not just main start comment)
`https://github.com/easylist/easylist/issues/6476`
specifically mobile movie sites and pirated sites(torrent ,movie streaming sites etc)...as far i see no fp so far in ubo currently...

**Pull request merged**
