### PR TITLE
Fix #142793 substack.com

### LINKED ISSUE #142793: faridaily.substack.com
### Issue URL (Annoyance)
 [https://faridaily.substack.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Ffaridaily.substack.com%2F)
### Comment
Username: `@rakleed`
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.9.2.1234+release
Browser: | Safari
Stealth mode options: | Hide your search queries, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Disable cache for third-party requests, <br>Hide your Referrer from third-parties (), <br>Hide your User-Agent ()
DNS filtering: | server: `https://dns.cloudflare.com/dns-query`<br>
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Custom filters: | https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt
Userscripts: | IMDb+Tomatoes+(url:+https://greasyfork.org/scripts/15222-imdb-tomatoes/code/IMDb%20Tomatoes.user.js),<br>AdGuard+Extra+(url:+https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js)
Referrer: | [https://www.google.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.google.com%2F)

### PR DESCRIPTION
**Pull request by rakleed**
I tried to return the scroll through `substack.com#$?#body { overflow: auto !important; }`, but for this site the rule does not work, so I had to do it through the scriptlet.

### CODE REVIEW

**Comment by krystian3w** [comment]
Same on Windows + Chrome, the best scroll to bottom and possible see better nasty scrollbar:

image

**Comment by rakleed** [comment]
@jellizaveta remove scriplet as [suggested @krystian3w](https://github.com/AdguardTeam/AdguardFilters/pull/142882#issuecomment-1429877588)

**Comment by rakleed** [comment]
@Sergey-Lyapin fixed.

**Comment by jellizaveta** [comment]
I think this is more a subscription popup

**Pull request merged**
