### PR TITLE
Google search parameters

### PR DESCRIPTION
**Pull request by BlazDT**
Commented out parameters break the page, please check if the non-disabled ones break something. At first view for me not.
`!` is also used for a seperate page.

Examples for the first two blocks:

https://www.google.com/search?q=ol&rlz=1C1GCEB_enDE856DE856&oq=ol&ie=UTF-8&safe=active&ssui=on
https://www.google.com/search?q=ol&ie=UTF-8&tbs=lf:1,lf_ui:1&tbm=lcl&rflfq=1&num=10&rldimm=10061593434063055024&lqi=CgJvbEjrzeaZq6qAgAhaCBAAGAAiAm9skgEDYmFyqgEVCgkvbS8wYnBfd3kQASoGIgJvbCgF&phdesc=9KPrtnFi8T8&rlst=f&safe=active&ssui=on#rlfi=hd:;si:10061593434063055024,l,CgJvbEjrzeaZq6qAgAhaCBAAGAAiAm9skgEDYmFyqgEVCgkvbS8wYnBfd3kQASoGIgJvbCgF,y,9KPrtnFi8T8;mv:[[50.0100833,12.7745058],[48.076788099999995,8.6280284]];tbs:lrf:!1m4!1u3!2m2!3m1!1e1!2m1!1e3!2m4!1e17!4m2!17m1!1e2!3sIAE,lf:1,lf_ui:1

### CODE REVIEW

**Comment by Alex-302** [comment]
Not sure about parameters with short values, they can be responsible for the page and/or search settings
image
Better do not try to block all parameters on the verge of breakdown.

**Comment by BlazDT** [comment]
So you have not found an issue yet. Maybe to Experimental then?

**Comment by Alex-302** [comment]
I am not sure if non-tracking(with unknown purpose) parameters must be blocked, even if nothing broken at first sight.

**Comment by BlazDT** [comment]
That would mean we do not block any parameters at all as they may have unknown functions. But I understand your point.

**Pull request closed without merging**
