### PR TITLE
Remove redundant rules and fix typos

### PR DESCRIPTION
**Pull request by iam-py-test**
# Creating the pull request

> Please include a summary of the change and which issue is fixed\
> If the related issue does not exist in our repository, please create it before making pull request\
> It is highly recommended to use our [Web Reporting Tool](https://kb.adguard.com/en/technical-support/reporting-tool) instead of creating an issue on GitHub directly\
> Please note, that we verify every pull request manually, so it may take time to apply it

### To avoid invalid pull requests, please check and confirm following terms

- [X] This is not an ad/bug report;
- [X] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [X] I have performed a self-review of my own changes;
- [X] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

## What issue is being fixed?

Redundant entries and two typos.

- These two rules appear to be intended to apply to all websites _except_ those where they cause problems, but instead they are _only_ applied to one of the excluded websites. I assume this is not intended.
```adblock
/images/social/*$domain=~schonmagazine.com|~waymo.com|~liga-manager.de|~techspot.com|~sport1.de|~bett1.de|~smofast.com|~promin.cv.ua|~rsload.net|~esportsearnings.com|~vortez.net|~programmingwithmosh.com|~wasabiclassics.com|~kolodischi.by|pesstatsdatabase.com
/images/vk.png$domain=~russiancouncil.ru|~tapochek.net|~cheater-top.ru|~epicl2.com|~epicwow.com|~monolife.ru|~mos.ru|~playground.moscow|dev-source.ru
```
- The rule `~intersport.nl,~intersport.hu,~intersport.nl,~intersport.es,~intersport.at##.cookiewall:not(body):not(html)` includes `intersport.nl` twice
- `##.cookiealert.show` is made redundant by `##.cookiealert` and thus removed
- `##.delayed-module.alert-cookie.alert` is made redundant by `##.alert-cookie` and thus removed
- `iobit.com##body > .float-bar` is made redundant by `drivereasy.com,iobit.com##.float-bar` and thus removed
- `cgtrader.com##body > .notice` is made redundant by `hilltopads.com,cgtrader.com,foreground.com.au,revolver.news,outsideonline.com,phys.org##.notice` and thus removed
- `kadinlarbilir.com###root > button[class*="_StyledCookieConsentButton-"]` appears twice
- `~pinterest.com##a[href^="https://www.pinterest.com/pin/create/button"]` and `~pinterest.com##a[href^="//www.pinterest.com/pin/create/button"]` are made redundant by `~pinterest.com##a[href*="pinterest.com/pin/create/button"]`

Thank you.

### Enter the issue address

N/A

#### If possible, a screenshot of a page or application should not be cropped too much. Otherwise, it is not always clear where the element is located

0. **DO NOT** upload screenshots with sexually explicit material on GitHub directly.\
 Instead, upload it to a third-party image hosting and post the link to it without preview (!) here.\
 Also, mention if the link leads to NSFW content;

1. Add screenshots of the problem. You can drag and drop images or paste them from clipboard

    Use `<details> </details>` tag to hide screenshots under the spoiler;

2. Describe the issue in detail until it is absolutely clear from the screenshot what the problem is

    You can also indicate any other information that you think the developers should know.

**Warning:** Please remove personal information before uploading screenshots!

1. Your comment

2. Screenshots

<details>

<summary>Screenshot 1:</summary>

</details>

<details>

<summary>Screenshot N:</summary>

</details>

### Terms

- [X] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Comment by Yuki2718** [comment]
See https://github.com/AdguardTeam/AdguardFilters/commit/18ef864d8e8780bb67c6e884bbf0c56e47f9b33c

**Comment by iam-py-test** [comment]
Thank you @Yuki2718 
I was not aware of that. Fixed. Please tell me if there are any other similar cases I need to fix

**Comment by Yuki2718** [comment]
```
##.delayed-module.alert-cookie.alert
iobit.com##body > .float-bar
cgtrader.com##body > .notice
```
For the same reason

`kadinlarbilir.com###root > button[class*="_StyledCookieConsentButton-"]` better to remove one not under `!+ NOT_OPTIMIZED`.

`##a[title="Share on LinkedIn"]` no explanation is given?

**Comment by iam-py-test** [comment]
Fixed those four. 
Sorry about `##a[title="Share on LinkedIn"]`, it is made redundant by `##[title="Share on LinkedIn"]`, but probably that should be undone for the same reason as the rest, right? (something I need to take into account in the future.)

**Comment by Yuki2718** [comment]
> but probably that should be undone for the same reason as the rest, right? 

I think okay to remove.

**Comment by iam-py-test** [comment]
I added it back in just to be safe.

**Review by Yuki2718 — APPROVED** [review]

**Review by piquark6046 — APPROVED** [review]

**Pull request merged**
