### PR TITLE
obsolete filter

### PR DESCRIPTION
**Pull request by JobcenterTycoon**
All domains are completely dead

### CODE REVIEW

**Comment by Alex-302** [comment]
Did you take into account that for some advertising systems only subdomains are resolved?(f.e. `ads.example111.com` used for ads, but `example111.com` has no DNS records and looks like dead)

**Comment by Alex-302** [comment]
I don't trust to services like that:)

**Comment by JobcenterTycoon** [comment]
Ok and how you check a domain to be sure its really dead ?

**Comment by Alex-302** [comment]
I do not check)

**Review by zloyden — APPROVED** [review]

**Pull request merged**
