### PR TITLE
fix #8639 (uBO Assets) ijuinews.com.br

### LINKED ISSUE #8639: issuetracker.unity3d.com
### Issue URL (Incorrect Blocking)
[https://issuetracker.unity3d.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fissuetracker.unity3d.com%2F)
### Comment
Username: @UnityUser
> 
> Custom userscripts:
> https://cdn.adguard.com/public/Userscripts/AdguardAssistant/4.0/assistant.user.js
> https://cdn.adguard.com/public/Userscripts/AdguardPopupBlocker/2.1/popupblocker.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 6.2.437.2171
Browser: | Firefox
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Self-destructing third-party cookies(30), Block Location API
Filters: | English,<br>Spyware,<br>Social media,<br>Filter unblocking search ads and self-promotion,<br>Russian

### PR DESCRIPTION
**Pull request by wout-codes**
https://github.com/uBlockOrigin/uAssets/issues/8639

### CODE REVIEW

**Review by zloyden — APPROVED** [review]

**Comment by Yuki2718** [comment]
In this case fundo should be in main filter. Also there are some more staff to address - I'll fix them.

**Comment by wout-codes** [comment]
> In this case fundo should be in main filter. Also there are some more staff to address - I'll fix them.

Sure. It should be in Annoyances because it can be closed.

**Comment by Yuki2718** [comment]
Then don't use `||ijuinews.com.br/upload/banners/` as it blocks the contents of the modal. We occasionally address closable popups on main filters.

**Comment by wout-codes** [comment]
> Then don't use `||ijuinews.com.br/upload/banners/` as it blocks the contents of the modal - now the modal is just a leftover. We occasionally address closable popups on main filters.
> [d86ce49](https://github.com/AdguardTeam/AdguardFilters/commit/d86ce49aeb673f7fb1e93e17d4703d9131895615)

Okay. I agree your rules are better.

**Pull request merged**
