### PR TITLE
Show "Subscribe" button on diakov.net

### PR DESCRIPTION
**Pull request by Obegg**
Issue reference: diakov.net #74247

### CODE REVIEW

**Comment by Alex-302** [comment]
This is expected behavior, if AdGuard Annoyances filter is enabled.

**Comment by ObsessedHacker** [comment]
> This is expected behavior, if AdGuard Annoyances filter is enabled.

It's incorrect blocking, the subscribe button should be shown. It's not an annoyance.
Once you subscribe you receive email notifications for updates.

**Comment by Alex-302** [comment]
In AdGuard Annoyances filter we may block everything. It is not enabled by default.

**Comment by Alex-302** [comment]
You can add it by parts:
https://github.com/AdguardTeam/AdguardFilters/tree/master/AnnoyancesFilter/sections
Without `annoyances.txt` in your case.

**Pull request closed without merging**
