### PR TITLE
Fix #148312 gigafile.nu

### LINKED ISSUE #148312: 87.gigafile.nu
### Issue URL (Ads)
 [https://87.gigafile.nu/0421-db7ae316c0cbb1bd2ba59f9923e83fb97](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2F87.gigafile.nu%2F0421-db7ae316c0cbb1bd2ba59f9923e83fb97)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.4.5
Browser: | Safari
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Japanese

### PR DESCRIPTION
**Pull request by SKEIDs**
### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [x] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

### Enter the issue address

 Fix #148312 gigafile.nu

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Comment by Alex-302** [comment]
I check on real devices.

**Comment by SKEIDs** [comment]
If you do not mind, could you tell me which rule apply?

**Comment by SKEIDs** [comment]
I also checked on my real device and see the same cat image as in the issue. 
Does this mean that this is a bug on my side?

**Comment by Alex-302** [comment]
I see the same banner without AdGuard. 


> Does this mean that this is a bug on my side?

Maybe, or app's.

**Comment by SKEIDs** [comment]
I see.
If you set the user agent of PC browser to mobile, will the banner display? (with Adguard)

**Comment by SKEIDs** [comment]
> Same - I see without AG, do not see with AdGuard. With tablet or phone mode in dev tools.

I see, thank you.

**Comment by Yuki2718** [comment]
I can reproduce, will fix directly.

**Pull request closed without merging**
