### PR TITLE
fix #61890 linkbuk.in

### LINKED ISSUE #61890: linkbuk.in
### Issue URL (Anti Adblock Script)
 [https://linkbuk.in/WA3GvAES?token=iLwV6ZDkxkAljEVI9YV9mZSIAvSm1KkXZiKoAjCsz8EKYX638laYprRr4qV8g5wj](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Flinkbuk.in%2FWA3GvAES%3Ftoken%3DiLwV6ZDkxkAljEVI9YV9mZSIAvSm1KkXZiKoAjCsz8EKYX638laYprRr4qV8g5wj)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.12
Browser: | EdgeChromium
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Web Annoyances Ultralist<br/><br/><b>Security:</b><br/> Malware Domains Blocklist, <br/>Spam404<br/><br/><b>Language-specific:</b><br/> ABPVN List

### PR DESCRIPTION
**Pull request by Sergey-Lyapin**
#61890

### CODE REVIEW

**Comment by Alex-302** [comment]
'Force Adblock' is not bypassed

**Review by Alex-302 — CHANGES_REQUESTED** [review]
'Force Adblock' is not bypassed

**Comment by Sergey-Lyapin** [comment]
> 'Force Adblock' is not bypassed

Strange, in my local branch I see that domain was added to force adblock rules %)

**Comment by Sergey-Lyapin** [comment]
> 'Force Adblock' is not bypassed

Screenshot 2020-08-24 at 11 29 51

**Comment by Alex-302** [comment]
hm

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
