### PR TITLE
Fix #166653 news.meta.ua

### LINKED ISSUE #166653: news.meta.ua
### Issue URL (Ads)
 [https://news.meta.ua/news/otravilis-v-dvukh-zavedeniiakh-v-odesse-bolee-60-kursantov-okazalis-v-bolnitse-5317587/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fnews.meta.ua%2Fnews%2Fotravilis-v-dvukh-zavedeniiakh-v-odesse-bolee-60-kursantov-okazalis-v-bolnitse-5317587%2F)
Username: `@Spok1`

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | Value
--- | ---
AdGuard product: | AdGuard for Android v3.6.11 (54)
Browser: | Chrome
AdGuard mode: | VPN
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | server: `https://dns.cloudflare.com/dns-query`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Ukrainian, <br/>AdGuard Russian
Userscripts: | disabled

### PR DESCRIPTION
**Pull request by xglossyntx**
# Creating the pull request

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [x] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

### Enter the issue address

#166653

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Review by zloyden — CHANGES_REQUESTED** [review]
Another rule should be added to block the ad leftover.
Btw, the site has RU locale, so the rules should be in common section. I will do it.

**Comment by xglossyntx** [comment]
> Another rule should be added to block the ad leftover. Btw, the site has RU UI, so the rules should be in common section. I will do it.

Alright

**Comment by xglossyntx** [comment]
What's the Russian filter used for then?

**Comment by zloyden** [comment]
I couldn't do some changes in this branch, but mentioned you [here](https://github.com/AdguardTeam/AdguardFilters/commit/1e4cc5f151b8def5e64d9081249350209d18ad9f).

**Comment by zloyden** [comment]
> What's the Russian filter used for then?

It's described in the description of the filter, but if the site has RU and UA locales, the rules should be added to the `common-sections`.

**Comment by xglossyntx** [comment]
When I was reading this https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md#repository-structure I never saw anything about the common-sections filter

**Pull request closed without merging**
