### PR TITLE
spellchecker.lu missed ad

### PR DESCRIPTION
**Pull request by FauconSpartiate**
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

<details><summary>Screenshot:</summary>

image

</details>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

image
</details><br/>

### CODE REVIEW

**Comment by Sergey-Lyapin** [comment]
Hello @pirottedamien, it's better to add this rule:  `||reklammen.spellchecker.lu^` to English filter > foreign.txt.
We need to create a section for the luxembourgish language, just add this above Malaysian.
```
!
!---------------------------------------------------------------------
!--------------------------- Luxembourgish ------------------------
!---------------------------------------------------------------------
!
! spellchecker.lu ad
||reklammen.spellchecker.lu^
```

**Review by Sergey-Lyapin — CHANGES_REQUESTED** [review]
Hello @pirottedamien, it's better to add this rule: ||reklammen.spellchecker.lu^ to English filter > foreign.txt.
We need to create a section for the luxembourgish language, just add this above Malaysian.

!
!---------------------------------------------------------------------
!--------------------------- Luxembourgish ---------------------------
!---------------------------------------------------------------------
!
! spellchecker.lu ad
||reklammen.spellchecker.lu^

**Comment by pirottedamien** [comment]
Here you go, I made your changes 👍

**Comment by Sergey-Lyapin** [comment]
Thank you)

**Pull request merged**
