### PR TITLE
cbom.atozmath.com

### PR DESCRIPTION
**Pull request by jellizaveta**
https://github.com/AdguardTeam/AdguardFilters/issues/136197

<details><summary>Screenshot:</summary>

Screenshot 2022-11-30 at 12 18 26

</details><br/>

### CODE REVIEW

**Comment by Alex-302** [comment]
Solution is not working on my end.
@piquark6046 Please take a look.

**Comment by piquark6046** [comment]
Me too. The changes does not work well.

**Comment by Alex-302** [comment]
@piquark6046 Could you please help with this issue?

**Comment by piquark6046** [comment]
Please check `ifr_vi_31308698_2`.
<details><summary>Screenshot</summary>

Screenshot from 2022-11-30 13-48-17



</details>

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
