### PR TITLE
fix issue template

### PR DESCRIPTION
**Pull request by Sergey-Lyapin**
How about moving the issue URL in the template up so that it is visible in the popover when hovering over the issue number? That would be handy.

### CODE REVIEW

**Comment by Alex-302** [comment]
`What type of problem` also can be moved under `Where is the`.

**Comment by Alex-302** [comment]
`Prerequisites` must be the first in any case.

**Comment by Sergey-Lyapin** [comment]
@Alex-302 in this case the url will not be visible in the popover.
gffgsd

**Comment by Alex-302** [comment]
> in this case the url will not be visible in the popover.

Not a problem. Prerequisites in the middle look weird.

**Pull request closed without merging**
