### PR TITLE
fix #79228 kizlarsoruyor.com

### LINKED ISSUE #79228: www.kizlarsoruyor.com
### Issue URL (Anti Adblock Script)
 [https://www.kizlarsoruyor.com/flort-tanisma/q4009063-diyarbakirli-erkekler-nasil-olur](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.kizlarsoruyor.com%2Fflort-tanisma%2Fq4009063-diyarbakirli-erkekler-nasil-olur)
### Comment
Username: @omurcek01
> Adguard burada tespit ediliyor.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.34
Browser: | EdgeChromium
Stealth mode: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Turkish

### PR DESCRIPTION
**Pull request by wout-codes**
#79228

### CODE REVIEW

**Review by Sergey-Lyapin — CHANGES_REQUESTED** [review]
cookie popup is missed

**Comment by Sergey-Lyapin** [comment]
please also unblock share-bar at the left and  hide share-icon in it only

**Comment by Sergey-Lyapin** [comment]
and block share leftover under the question

**Comment by wout-codes** [comment]
I can't reproduce Cookie Popup.

**Comment by Sergey-Lyapin** [comment]
Screenshot 2021-04-05 at 15 22 23

**Comment by Sergey-Lyapin** [comment]
> I can't reproduce Cookie Popup.

try with german vpn

**Comment by wout-codes** [comment]
Added few rules.

**Pull request merged**
