### PR TITLE
fix #77374 medikalakademi.com.tr

### LINKED ISSUE #77374: medikalakademi.com.tr
### Issue URL (Ads)
 [https://www.medikalakademi.com.tr/serra-uluisik-pfizer-global-yetenek-havuzu-stratejileri-direktorue-oldu/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.medikalakademi.com.tr%2Fserra-uluisik-pfizer-global-yetenek-havuzu-stratejileri-direktorue-oldu%2F)
### Comment
Username: @RadicalNoise
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.31
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (2880)
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Security:</b><br/> NoCoin Filter List<br/><br/><b>Language-specific:</b><br/> AdGuard Turkish

### PR DESCRIPTION
**Pull request by wout-codes**
#77374

### CODE REVIEW

**Comment by Erengit** [comment]
Rules are wrong. Please do not merge without checking site. @AdguardTeam/filters-maintainers

**Comment by wout-codes** [comment]
> Rules are wrong. Please do not merge without checking site. @AdguardTeam/filters-maintainers

What's wrong? All ads/banners removed according to the report. Why don't you try the rules?

**Comment by wout-codes** [comment]
> Rules are wrong. Please do not merge without checking site. @AdguardTeam/filters-maintainers

@Erengit Can you check now?

**Comment by Sergey-Lyapin** [comment]
The rules look ok now

**Pull request merged**
