### PR TITLE
fix #63832 mundodonghua.com

### LINKED ISSUE #63832: mundodonghua.com
### Issue URL (Anti Adblock Script)
 [https://www.mundodonghua.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.mundodonghua.com%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.0.2
Browser: | Safari
System wide filtering: | disabled
Simplified filters: | disabled
AdGuard DNS: | Default
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads, <br/>EasyList, <br/>Peter Lowe's Blocklist<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection, <br/>EasyPrivacy, <br/>Fanboy's Enhanced Tracking List<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Adblock Warning Removal List, <br/>I don't care about cookies, <br/>EasyList Cookie List<br/><br/><b>Security:</b><br/> Spam404, <br/>NoCoin Filter List<br/><br/><b>Other:</b><br/> AdGuard Experimental, <br/>AdGuard DNS, <br/>BarbBlock<br/><br/><b>Language-specific:</b><br/> AdGuard Spanish/Portuguese

### PR DESCRIPTION
**Pull request by stanislav-atr**
#63832

### CODE REVIEW

**Review by BlazDT — CHANGES_REQUESTED** [review]
For iOS and CB:
mundodonghua.com#@#.adsbygoogle
@@||mundodonghua.com/banner.gif

Annoyances filter why? I could not hide it (or did not see the correct button). Only saw the [onclick] code to hide it.

**Comment by AdamWr** [comment]
>For iOS and CB:
mundodonghua.com#@#.adsbygoogle
@@||mundodonghua.com/banner.gif

As far as I can see, these rules for iOS and CB are already in Spanish filter.
What about re-adding this rule - https://github.com/AdguardTeam/AdguardFilters/commit/11e6975ef758bd00a7375df86cd50d486a78e383#diff-ea95cb0d94aa3a6e2065c327d4516c79L378?
`mundodonghua.com#%#//scriptlet("prevent-setTimeout", "/Tamamo_Blocker|aadb_recheck/")`

@Alex-302 Does this rule break something?

**Review by BlazDT — CHANGES_REQUESTED** [review]
Site is Spanish.

**Comment by stanislav-atr** [comment]
> 
> 
> Site is Spanish.

*facepalm*

**Comment by Alex-302** [comment]
@AdamWr 

> `mundodonghua.com#%#//scriptlet("prevent-setTimeout", "/Tamamo_Blocker|aadb_recheck/")`
> 
> @Alex-302 Does this rule break something?

No. Checked again - it works. Restored.

**Pull request closed without merging**
