### PR TITLE
fix #77840 poki.com

### LINKED ISSUE #77840: poki.com
### Issue URL (Ads)
 [https://poki.com/en/g/blocky-cars](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fpoki.com%2Fen%2Fg%2Fblocky-cars)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.6 nightly 23
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (180), <br>Block Push API, <br>Block Location API
DNS filtering: | server: `https://dns-unfiltered.adguard.com/dns-query`<br>filters: `User rules`
Filters: | <b>Ad Blocking:</b><br/> EasyList, <br/>Peter Lowe's Blocklist, <br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> EasyPrivacy, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> Adblock Warning Removal List, <br/>I don't care about cookies, <br/>EasyList Cookie List, <br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/> Online Malicious URL Blocklist, <br/>Spam404, <br/>NoCoin Filter List
Custom filter subscriptions: | https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt,<br>https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt

### PR DESCRIPTION
**Pull request by wout-codes**
#77840

### CODE REVIEW

**Comment by AdamWr** [comment]
It seems that these elements have "random" names, I don't see `.fd` on my side.
What about something like:
```
poki.com#?#div[class*=" "] > div[class] > div[style^="height:"] + div[class]:contains(/^Advertisement$/):upward(2)
```

Also please remove "old" rule - `poki.com#?#div.rd:upward(1)`, it seems that it stopped working.

**Comment by wout-codes** [comment]
> It seems that these elements have "random" names, I don't see `.fd` on my side.
> What about something like:
> 
> ```
> poki.com#?#div[class*=" "] > div[class] > div[style^="height:"] + div[class]:contains(/^Advertisement$/):upward(2)
> ```
> 
> Also please remove "old" rule - `poki.com#?#div.rd:upward(1)`, it seems that it stopped working.

Both works on my end.

**Review by AdamWr — APPROVED** [review]

**Comment by AdamWr** [comment]
There is no element like this on my side - `div[class*=" "] > div[class] > .fd`, but I see `div[class*=" "] > div[class] > .vd`

<details><summary>Screenshot</summary>

image

</details>


Thank you.

**Comment by wout-codes** [comment]
Looks like it varies by region.

**Pull request merged**
