### PR TITLE
The fifth large cleanup of Base

### PR DESCRIPTION
**Pull request by Yuki2718**
```
! ---------- added to EL (Base)
||0gw7e6s3wrao9y3q.pro^
||9content.com^$third-party,popup
||adrecreate.com^$third-party
||adtng.com^$third-party
||adversolutions.com^$third-party
||adxpansion.com^$third-party
||alxsite.com^$third-party
||betteradsystem.com^
||bcloudhost.com^$third-party
||bnrdom.com^$third-party
||boffinsoft.com^$third-party
||celeritascdn.com^$third-party
||clkrev.com^$third-party
||deloplen.com^
||fabolele.com^$popup
||foapsovi.net^
||hitcpm.com^$third-party
||idiafix.com^
||ivastoor.com^
||jujzh9va.com^$third-party
||megapopads.com^$third-party
||nanoadexchange.com^$popup
||networkmanag.com^$third-party
||njmaq.com^$third-party
||onclickmega.com^
||opsivesh.net^
||propellerclick.com^$third-party
||prpops.com^$popup
||pulpsbarndomed.com^
||rotumal.com^$popup
||slikslik.com^$third-party
||superfastcdn.com^
||terraclicks.com^$popup
||venturead.com^
||vipcpms.com^$third-party
||wellmov.com^$third-party
||wwwpromoter.com^$third-party
||wynather.com^$third-party
||xaxoro.com^$third-party
||xxlargepop.com^$third-party
||zedo.com^$third-party

||d3ithbwcmjcxl7.cloudfront.net^

||exdynsrv.com^$third-party

||greatdexchange.com^$popup
||lcwfabt1.com^$third-party

! ---------- Obsolete
! ###adBanner removed from EL
pcsteps.com#@##adBanner

! ##.adBanner removed from EL
dudestream.com#@#.adBanner
quackr.io#@#.adBanner
claimrbx.gg#@#.adBanner
drphil.com#@#.adBanner
beypazaricekici.com#@#.adBanner
wabetainfo.com#@#.adBanner
thewatchcartoononline.tv#@#.adBanner
wcoforever.com#@#.adBanner
lopteup.vip#@#.adBanner
truyentranhaudio.com#@#.adBanner
hentaihaven.xxx#@#.adBanner
gtamaxprofit.com#@#.adBanner
roya.tv#@#.adBanner
mangallama.com#@#.adBanner
loptelink.vip#@#.adBanner
easyload.io#@#.adBanner
crxne.de#@#.adBanner
eplayer.is#@#.adBanner
intl.startrek.com#@#.adBanner
qpython.club#@#.adBanner
uploader.xzy.pw#@#.adBanner
insideedition.com#@#.adBanner
physicsisbeautiful.com#@#.adBanner
thewatchcartoononline.tv,wco.tv,wcostream.com,wcoanimesub.tv,wcoanimedub.tv#@#.adBanner
satoshimonster.com#@#.adBanner
satoshihero.com#@#.adBanner
hitbits.io#@#.adBanner
hydrogenassociation.org#@#.adBanner
freevocabulary.com#@#.adBanner
windows4all.com#@#.adBanner
megaup.net#@#.adBanner
creditcardgenerator.com#@#.adBanner
creditcardrush.com#@#.adBanner
janjua.tv#@#.adBanner
lookmovie.ag#@#.adBanner
etonline.com#@#.adBanner
irobux.com#@#.adBanner
rubiks-cube-solver.com#@#.adBanner
html-online.com#@#.adBanner

v2rayssr.com#@#.adBanner
videakid.hu,videa.hu#@#.adBanner
haaretz.co.il#@#.adBanner
htnovo.net#@#.adBanner
joins.com#@#.adBanner
rynek-kolejowy.pl,transport-publiczny.pl,rynekinfrastruktury.pl,rynek-lotniczy.pl#@#.adBanner
phimgi.net#@#.adBanner

spin.com#@#.adBanner
```

### CODE REVIEW

**Comment by Yuki2718** [comment]
These are potentially obsolete scriptlet filters (needs further check):
```
givekey.ru#%#//scriptlet("prevent-bab")

collectionofbestporn.com#%#//scriptlet("abort-on-property-read", "__ads")
fastpic.ru#%#//scriptlet("prevent-addEventListener", "click", "popMagic")
vidlox.me#%#//scriptlet("abort-current-inline-script", "String.fromCharCode", "zfgloaded")
jawcloud.co#%#//scriptlet("abort-current-inline-script", "String.fromCharCode", "zfgloaded")
```

**Review by Alex-302 — APPROVED** [review]
```
! https://github.com/AdguardTeam/AdguardFilters/issues/8700
pcsteps.com#@##adBanner
```
this rule is still required(look at HTML), will be restored

**Comment by Yuki2718** [comment]
> this rule is still required(look at HTML), will be restored

Even without `###adBanner`? I don't get it. But okay.

**Comment by Alex-302** [comment]
Sure. Removed.

**Pull request merged**
