### PR TITLE
Fix #142813 youtube.com

### LINKED ISSUE #142813: www.youtube.com
### Issue URL (Incorrect Blocking)
 [https://www.youtube.com/watch?v=4cOX0WN7BO4&t=421s](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D4cOX0WN7BO4%26t%3D421s)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>
<details>
  <summary>Screenshot 2</summary>

  Screenshot 2
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.23
Browser: | YaBrowser
Stealth mode: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>AdGuard Chinese, <br/>AdGuard Dutch, <br/>Official Polish filters for AdBlock, uBlock Origin & AdGuard, <br/>Polish Anti Adblock Filters
Other extensions used: | нет

### PR DESCRIPTION
**Pull request by rakleed**
https://github.com/AdguardTeam/AdguardFilters/issues/142813#issuecomment-1430015026

### CODE REVIEW

**Comment by Yuki2718** [comment]
Way too aggressive, hiding Shorts and Trending.

**Comment by rakleed** [comment]
@Yuki2718 on what pages? I have Shorts displayed on https://www.youtube.com/shorts and in subscriptions, and Trending is displayed on https://www.youtube.com/feed/trending.

**Comment by Yuki2718** [comment]
HP:

yt

**Comment by rakleed** [comment]
After logging into your account, the Trending section disappears, and Shorts can be hidden (which I did).

In general, Shorts is not a main product of YouTube, and there is a separate page for them, the link to which is located directly under the Home in the left menu. And also for the Trending there is a separate page a little lower in this menu.

For me, Shorts are just an annoyance, since they are not the main product of YouTube, and the section with them takes up a significant part of the page. Therefore, I suggest adding this rule to self-promo.

**Comment by Alex-302** [comment]
Not annoying.

**Pull request closed without merging**
