### PR TITLE
www.jalan.net

### PR DESCRIPTION
**Pull request by gork7777**
issue: #112186

### CODE REVIEW

**Comment by Yuki2718** [comment]
Like your first comment, I can't reproduce on Android. Could you reproduce?

**Comment by gork7777** [comment]
@Yuki2718 I can't reproduce but there seems to be a banner standing there

ads

**Comment by Yuki2718** [comment]
@SKEIDs Can you please take a look on iOS? Looks the same as https://github.com/AdguardTeam/AdguardFilters/issues/112015 but want confirmation.

**Comment by SKEIDs** [comment]
@Yuki2718 
I can reproduce.
image

image

**Review by Yuki2718 — APPROVED** [review]

**Review by zloyden — APPROVED** [review]

**Pull request merged**
