### PR TITLE
add b-cdn.net to lockdown rules and lockdown (nsfw) everia.club

### PR DESCRIPTION
**Pull request by Yuki2718**
### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [x] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

### Enter the issue address

As or writing, [NSFW] `everia.club` looks to be hijacked with malicious script in `data:text/javascript` which calls `https://dns.google/resolve?name=...` to redirect visitor to scam. I wanted to lockdown the site which anyway has PopAds, but then only to find such a common CDN of `b-cdn.net` is not included in the lockdown rules.

#### If possible, a screenshot of a page or application should not be cropped too much. Otherwise, it is not always clear where the element is located

1. Your comment

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Comment by Yuki2718** [comment]
The injected code is mostly the same as `https://blog.sucuri.net/2023/08/from-google-dns-to-tech-support-scam-sites-unmasking-the-malware-trail.html` except for using data URI than atob and not using addEventListener. Whether the redirection to scam actually happens or not depends on various factors. I was redirected only on the first two visits. Of note the site was first reported by https://github.com/AdguardTeam/AdguardFilters/issues/89377

**Review by AdamWr — APPROVED** [review]

**Comment by AdamWr** [comment]
It looks like that currently it uses `web-hosts.io` for redirection - `hxxps://web-hosts[.]io/?cnmnmtijvq3fk5e6e9s0` (this part after `/?` seems to depends on IP, but I'm not sure), so maybe `web-hosts.io` could also be blocked.

**Comment by Yuki2718** [comment]
Sure, I'll block in EL.

**Comment by Yuki2718** [comment]
The script lockdown here doesn't block the redirect as it is based on xhr so needing xhr lockdown too, is it worth a new rule? I also added https://github.com/uBlockOrigin/uAssets/commit/94f060d36d696458448036544777769f076516b0 to uBO, but according to `https://blog.sucuri.net/2023/08/from-google-dns-to-tech-support-scam-sites-unmasking-the-malware-trail.html` the malicious actor used `tracker-cloud.com` in past so probably this part will change.

**Comment by AdamWr** [comment]
>The script lockdown here doesn't block the redirect as it is based on xhr so needing xhr lockdown too, is it worth a new rule?

There is already `$xmlhttprequest,third-party,denyallow=[...],domain=[...]` in Turkish filter, so if it block ads and doesn't cause any breakage, then I don't see any reason to not add similar rule to Base filter, I guess that it can be useful on other websites.

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
