### PR TITLE
Fix #165624 check-host.net

### PR DESCRIPTION
**Pull request by xglossyntx**
# Creating the pull request

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [x] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

### Enter the issue address

Fix #165624

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Comment by rodrigosambadesaa** [comment]
They continue to fight back because the four ads are still visible. However, [uBlock Origin](https://chromewebstore.google.com/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) blocks them.

**Review by xglossyntx — COMMENTED** [review]
``/^https:\/\/check-host\.net\/images\/ondguard+(_|[0-9]?[a-z-])+(s?ale|en|ru)?\.png\?[0-9]/$domain=check-host.net``

Feel free to improve this rule if you want.

**Comment by rodrigosambadesaa** [comment]
They updated again.

**Comment by xglossyntx** [comment]
> They updated again.

It's working just fine for me. Remember, this has not been merged yet, so you will need to add it as a user filter if you want to use it or wait for it to be merged.

**Review by Alex-302 — APPROVED** [review]

**Comment by Alex-302** [comment]
@rodrigosambadesaa It all depends on the filters set in the blocker. 
We also have AdGuard Extra extension/userscript, which block that ads in the other way.

**Comment by rodrigosambadesaa** [comment]
Hello again.

Using the Adguard Android 
Screenshot_20240415-155809
app with my license one of the ads is not blocked.

**Comment by Alex-302** [comment]
@rodrigosambadesaa Is HTTPS filtering enabled?

On my device it is clean with AdGuard for Android

<details>
<summary>Details</summary>

IMG_20240416_152003_491

</details>

**Comment by rodrigosambadesaa** [comment]
> @rodrigosambadesaa Is HTTPS filtering enabled?
> 
> On my device it is clean with AdGuard for Android
> 
> Details

Just enabled it and now all the ads are blocked. Thank you.

**Comment by rodrigosambadesaa** [comment]
Also, can I suggest, if possible, for an employee or a group or employees to keep an eye on this site daily or multiple times a day, if possible. Last year one day they updated multiple times to try to circunvent AdGuard's measures, with @xglossyntx saying it was a cat and mouse game. uBlock Origin does a much better job in blocking this site's ads, because it has been multiple months since I do not see them while using it, and they blocked the last one they implemented quickly when I told them. They fought back but only managing to get that last implemented ad to circunvent uBlock Origin's measures, but since I told them about two weeks ago they fixed it and I didn't see it again, however they easily circunvent AdGuard's measures, usually like every two weeks.

**Comment by rodrigosambadesaa** [comment]
Also, can I suggest, if possible, for an employee or a group or employees to keep an eye on this site daily or multiple times a day, if possible. Last year one day they updated multiple times to try to circunvent AdGuard's measures, with @xglossyntx saying it was a cat and mouse game. uBlock Origin does a much better job in blocking this site's ads, because it has been multiple months since I do not see them while using it, and they blocked the last one they implemented quickly when I told them. They fought back but only managing to get that last implemented ad to circunvent uBlock Origin's measures, but since I told them about two weeks ago they fixed it and I didn't see it again, however they easily circunvent AdGuard's measures, usually like every two weeks, managing to make all ads visible again.

**Comment by rodrigosambadesaa** [comment]
And for some reason https filtering is interfering with Firefox for Android behavior, which fails trying to establish secure connections for some sites.

**Comment by Alex-302** [comment]
> And for some reason https filtering is interfering with Firefox for Android behavior, which fails trying to establish secure connections for some sites.

https://adguard.com/kb/adguard-for-android/solving-problems/firefox-certificates/

**Pull request merged**
