### PR TITLE
fix #39480 youtube.name.tr

### LINKED ISSUE #39480: youtube.name.tr
### Issue URL (Ads)
[http://www.youtube.name.tr/2017/08/01/perde-ayn-i-cin/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwww.youtube.name.tr%2F2017%2F08%2F01%2Fperde-ayn-i-cin%2F)
### Comment
Username: @VivaLaVidaValeVoua
> 
> --
> Aşağıdaki bilgiler otomatik olarak oluşturuldu. Silmeyin.
> 
> Custom userscripts:
> https://userscripts.adtidy.org/beta/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/beta/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js
> https://adsbypasser.github.io/releases/adsbypasser.full.es5.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.2.2903.0
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Self-destructing third-party cookies (0), Block WebRTC, Block Push API, Block Location API
Filters: | EasyList,<br>AdGuard Turkish,<br>AdGuard Annoyances,<br>AdGuard Base,<br>Adblock Warning Removal List,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

### PR DESCRIPTION
**Pull request by zloyden**
https://github.com/AdguardTeam/AdguardFilters/issues/39480

### CODE REVIEW

**Review by BlazDT — CHANGES_REQUESTED** [review]
Please also hide the link in filmoncereklam, so user will not see the ad (I do not see a skip ad button aka "kapat" there).

**Comment by zloyden** [comment]
That domain doesn't load on my side, but it seems not an ad, just another source in video-player.

**Comment by zloyden** [comment]
Sadly, the site doesn't open on my side with/without VPN.

**Comment by Alex-302** [comment]
It has too few visitors.

**Pull request closed without merging**
