### PR TITLE
Hot-Fix: danawa.com

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/AdguardTeam/AdguardFilters/pull/76128

### CODE REVIEW

**Comment by piquark6046** [comment]
Screenshot1
Screenshot2

**Comment by piquark6046** [comment]
@Yuki2718  Cloud you please merge it?

**Review by Alex-302 — APPROVED** [review]

**Comment by Alex-302** [comment]
Any removed rule breaks that button?

**Comment by piquark6046** [comment]
> 
> 
> Any removed rule breaks that button?

Yes. `||prod.danawa.com/info/dpg/js/util/loggerUtils.js` breaks a button.

**Comment by Yuki2718** [comment]
@piquark6046 I was advised not to merge without review of the official member.

**Pull request merged**
