### PR TITLE
add twitter tracking parameters and update to include x.com

### PR DESCRIPTION
**Pull request by fenopa**
ref: https://github.com/Smile4ever/Neat-URL/blob/9e34d5944e26e936ea79adf7538c8e74dd117c5b/data/default-params-by-category.json#L42

### CODE REVIEW

**Comment by Alex-302** [comment]
But x.com is not uses as the main site.

**Comment by fenopa** [comment]
i see a lot of x.com links around.

**Comment by Alex-302** [comment]
Where? Need examples.

**Comment by fenopa** [comment]
in internet. forums etc. replace any twitter link with x.com and you have your examples jesus.

**Review by Alex-302 — APPROVED** [review]

**Comment by Alex-302** [comment]
ok, found one link
https://x.com/ASALifeline?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor

**Pull request merged**
