### PR TITLE
Update adservers_firstparty.txt

### PR DESCRIPTION
**Pull request by bkrucarci**
Added 2 advert networka for the sake of AdGuard DNS Filter.
-
Website: https://www.superhaber.tv/tag-otoyolunda-kaza-7-arac-birbirine-girdi-haber-385924
SS : https://i.imgur.com/XJsA0ZU.png
+
Website: https://www.yeniasir.com.tr/ + https://www.sabah.com.tr/
SS : https://i.imgur.com/iYBWLPZ.png

### CODE REVIEW

**Comment by bkrucarci** [comment]
Added another wide-spread ad network

**Comment by furt555nv** [comment]
They already exist in the filters

https://github.com/AdguardTeam/AdguardFilters/blob/270940c971b5206efb0812db22f8a967c8077447/TurkishFilter/sections/adservers.txt#L171

https://github.com/AdguardTeam/AdguardFilters/blob/270940c971b5206efb0812db22f8a967c8077447/TurkishFilter/sections/adservers.txt#L184

**Review by zloyden — COMMENTED** [review]
We already have these rules, but I have improved one rule. Thanks for opening the pull request.

**Comment by bkrucarci** [comment]
> We already have these rules, but I have improved one rule. Thanks for opening the pull request.

my submission is **ad-cdn.bilgin.pro**
adguard dns has **ad.bilgin.pro**

**Comment by bkrucarci** [comment]
> As I said above, I have improved the rule - please take a look here [9d5cb53](https://github.com/AdguardTeam/AdguardFilters/commit/9d5cb536226b90c31cc45149e0ec1c4e5ed09b04)

Is it going to work with DNS filtering?

**Comment by zloyden** [comment]
Yes, the rule matches such domains.

**Comment by bkrucarci** [comment]
> Yes, the rule matches such domains.

Great! Thanks

**Comment by zloyden** [comment]
You are welcome.

**Pull request closed without merging**
