### PR TITLE
fix #76907 imglin.xyz

### LINKED ISSUE #76907: imglin.xyz
### Issue URL (Ads)
[NSFW] [http://imglin.xyz/3x0wws65](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fimglin.xyz%2F3x0wws65)

### [NSFW] Screenshots
<details>
  <summary>Screenshot 1</summary>

  [Screenshot 1](https://reports-img.adguard.com/xACJuS7.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.6 nightly 22
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (180), <br>Block Push API, <br>Block Location API
DNS filtering: | server: `https://dns-unfiltered.adguard.com/dns-query`<br>filters: `User rules`
Filters: | <b>Ad Blocking:</b><br/> EasyList, <br/>Peter Lowe's Blocklist, <br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> EasyPrivacy, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> Adblock Warning Removal List, <br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/> Online Malicious URL Blocklist, <br/>Spam404, <br/>NoCoin Filter List
Custom filter subscriptions: | https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt,<br>https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt

### PR DESCRIPTION
**Pull request by wout-codes**
#76907

### CODE REVIEW

**Comment by wout-codes** [comment]
@Yuki2718 Shoud I add this domain to this rule? `http$third-party,~image,domain=`. It does nothing on my end. Yours?

**Comment by Yuki2718** [comment]
The filter doesn't do job as well, but good to have as lockdown since these sites changes ad servers frequently. But on my end `||imglin.xyz/shrinker/js/ionqs11.js` breaks the link completely as stated in https://github.com/AdguardTeam/AdguardFilters/issues/76298#issuecomment-788974704

**Comment by Yuki2718** [comment]
And again behavior is different between uBO and AG, I see these ad servers called on uBO:
```
||pedestrianneighbourly.com^
||thugitori.pro^
```

**Comment by wout-codes** [comment]
@Yuki2718 I fix FP's.

**Comment by wout-codes** [comment]
> And again behavior is different between uBO and AG, I see these ad servers called on uBO:
> 
> ```
> ||pedestrianneighbourly.com^
> ||thugitori.pro^
> ```

@Yuki2718 I will add these too.

**Review by Yuki2718 — APPROVED** [review]

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
