### PR TITLE
fix #75662 jameda.de

### LINKED ISSUE #75662: jameda.de
### Issue URL (Annoyance)
 [https://www.jameda.de/arztsuche/?fachgebiet=S53&gruppe=HA&new_search=1&version=5.0.0&where=](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.jameda.de%2Farztsuche%2F%3Ffachgebiet%3DS53%26gruppe%3DHA%26new_search%3D1%26version%3D5.0.0%26where%3D)
### Comment
Username: `@andy-kl`
> 
> --
> Die folgenden Informationen werden automatisch generiert. Bitte löschen Sie sie nicht.
> 
> Referrer:
> https://www.jameda.de/
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  Screenshot 1
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.3
Browser: | Chrome
AdGuard driver: | WFP
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> Fanboy's Anti-Facebook List, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> Fanboy's Social Blocking List, <br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> Adblock Warning Removal List, <br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/> NoCoin Filter List<br/><br/><b>Other:</b><br/> AdGuard Experimental<br/><br/><b>Language-specific:</b><br/> AdGuard German
Custom filter subscriptions: | https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

### PR DESCRIPTION
**Pull request by wout-codes**
#75662

### CODE REVIEW

**Review by AdamWr — APPROVED** [review]

**Comment by wout-codes** [comment]
@AdamWr There is an `Anzeige` which I don't know how to fix.

**Comment by AdamWr** [comment]
I saw it, but to be honest I'm not sure if it should be blocked.
You can add for example this rule to user filter:
```
jameda.de#?##result-list > li[data-testid="top-module"]:has(div[data-testid="advertisementSign-flag"])
```
to hide this element.

**Comment by wout-codes** [comment]
> ```
> jameda.de#?##result-list > li[data-testid="top-module"]:has(div[data-testid="advertisementSign-flag"])
> ```

@AdamWr I think it should be blocked. `Anzeige` means Advertisement. So I think it should be blocked.

**Comment by AdamWr** [comment]
I know that "Anzeige" means "Advertisement", but it doesn't mean that it should be blocked. It doesn't redirect to any ads, there are just links to doctors from jameda premium or something like that (I might be wrong).
I guess that optionaly it could be blocked in Annoyances filter, but I'm still not sure if it should be.

@BlazDT Could you please take a look?

**Comment by wout-codes** [comment]
> be blocked. It doesn't redirect to any ads, there are just links to doctors from jameda premium or something like that (I might be wrong).
> I guess that optionaly it could be blocked in Annoyances filter, but I'm still not sure if it should be.

It's up to both of you [:

**Pull request merged**
